# SPDX-License-Identifier: GPL-2.0-only
# AXERA Platform Support
obj-$(CONFIG_SND_AXERA_I2S) += axera_i2s.o

axera_i2s-y := ax-misc.o dwc-i2s.o dwc-tdm.o ax-actt.o
axera_i2s-$(CONFIG_SND_AXERA_PCM) += dwc-pcm.o dwc-tdm-pcm.o
