#ifndef __AX620E_PM_REG_H__
#define __AX620E_PM_REG_H__

/* PMU GLB REG */
#define PMU_GLB_BASE_PHY_ADDR		0x02100000    /* physical addr */
#define PMU_GLB_PWR_WAIT0_ADDR		(0x10)
#define PMU_GLB_PWR_WAIT1_ADDR		(0x14)
#define PMU_GLB_PWR_WAITON0_ADDR	(0x18)
#define PMU_GLB_PWR_WAITON1_ADDR	(0x1C)
#define PMU_GLB_INT_CLR_SET_ADDR	(0x114)
#define PMU_GLB_PWR_STATE_ADDR		(0x0C)
#define PMU_GLB_SLP_EN_SET_ADDR		(0x6C)
#define PMU_GLB_SLP_EN_CLR_ADDR		(0x70)
#define PMU_GLB_CPU_SYS_SLP_REQ_ADDR	(0x64)
#define BIT_PMU_GLB_CPU_SYS_SLP_REQ_MASK (1 << 0)
#define PMU_GLB_PWR_BYPASS_ADDR		(0x8)
#define PMU_GLB_WAKUP_SET_ADDR		(0x74)
#define PMU_GLB_WAKUP_CLR_ADDR		(0x78)
#define PMU_GLB_RST_FRC_EN_SET_ADDR	(0xEC)
#define BIT_PMU_GLB_RST_FRC_EN_FLASH_SET (2 << 1)
#define PMU_GLB_RST_FRC_SW_SET_ADDR	(0xF4)
#define BIT_PMU_GLB_RST_FRC_SW_FLASH_SET (2 << 1)
#define PMU_GLB_CLK_FRC_EN_ADDR		(0x38)
#define PMU_GLB_CLK_FRC_SW_ADDR		(0x3C)
#define BIT_PMU_GLB_PERIPH_SYS_CLK_FRC_EN	(1 << 7)
#define PMU_GLB_LIGHT_SLEEP_FRC_ADDR  (0x48)
#define PMU_GLB_LIGHT_SLEEP_SW_ADDR   (0x4C)

/* COMMON SYS GLB REG */
#define COMMON_SYS_GLB_PHY_BASE				0x02340000  /* physical addr */
#define COMMON_SYS_CLK_MUX_0_ADDR			(0x0)
#define COMMON_SYS_CLK_MUX_2_ADDR			(0x18)
#define COMMON_SYS_PAD_SLEEP_BYP_ADDR			(0x188)
#define COMMON_SYS_PLL_SLEEP_BYP_ADDR			(0x18C)
#define COMMON_SYS_EIC_MASK_ENABLE_SET_ADDR		(0x198)
#define COMMON_SYS_EIC_MASK_ENABLE_CLR_ADDR		(0x19C)
#define BIT_COMMON_SYS_EIC_MASK_ENABLE_SET		BIT(0)
#define COMMON_SYS_DEB_GPIO_31_0_INT_CLR_SET_ADDR	(0x15C)
#define COMMON_SYS_DEB_GPIO_31_0_INT_MASK_SET_ADDR	(0x138)
#define COMMON_SYS_DEB_GPIO_63_32_INT_CLR_SET_ADDR	(0x150)
#define COMMON_SYS_DEB_GPIO_63_32_INT_MASK_SET_ADDR	(0x12C)
#define COMMON_SYS_DEB_GPIO_89_64_INT_CLR_SET_ADDR	(0x144)
#define COMMON_SYS_DEB_GPIO_89_64_INT_MASK_SET_ADDR	(0x120)
#define BIT_COMMON_SYS_DEB_GPIO_MASK_ALL		0xffffffff
#define COMMON_SYS_XTAL_SLEEP_BYP_ADDR			(0x190)
#define EIC_EN_CLR					(0x218)
#define EIC_EN_MASK_ALL					0x7F
#define EIC_RISCV_EN					(0x248)
#define COMMON_SYS_USB_INT_CTRL_SET_ADDR		(0x3F8)
#define BIT_COMMON_SYS_USB_WAKE_UP_INT_MASK_SET		BIT(1)
#define BIT_COMMON_SYS_USB_WAKE_UP_INT_CLR_SET		BIT(0)
#define MISC_CTRL					(0x380)
#define MISC_CTRL_VAL					0x4
#define COMMON_SYS_COMMON2_DDR_BUS_IDLE_SW_ADDR		(0x490)
#define BIT_COMMON_SYS_COMMON2_DDR_BUS_IDLE_SW		BIT(0)
#define COMMON_SYS_COMMON2_DDR_BUS_IDLE_MASK_ADDR	(0x494)
#define BIT_COOMON_SYS_COMMON2_DDR_BUS_IDLE_MASK	BIT(0)
#define COMMON_SYS_EIC_EN_SET_ADDR			(0x214)
#define BIT_COMMON_TMR32_EIC_EN_SET			BIT(1)
#define BIT_COMMON_GPIO_LP_EIC_EN_SET			BIT(5)
#define COMMON_SYS_SW_RST_0_ADDR			(0x54)
#define BIT_COMMON_SYS_TIMER32_SW_RST			BIT(22)
#define BIT_COMMON_SYS_TIMER32_SW_PRST			BIT(21)
#define COMMON_SYS_CLK_MUX1_ADDR			(0xc)
#define BIT_COMMON_SYS_CLK_TIMER32_SEL_24M		BIT(26)
#define COMMON_SYS_CLK_EB_0_ADDR			(0x24)
#define BIT_COMMON_SYS_CLK_TIMER32_EB			BIT(14)
#define COMMON_SYS_CLK_EB_1_ADDR			(0x30)
#define BIT_COMMON_SYS_PCLK_TMR32_EB			BIT(15)
#define COMMON_SYS_AUX_CFG1_SET_ADDR			(0x1BC)
#define COMMON_SYS_AUX_CFG1_CLR_ADDR			(0x1C0)

/* PINMUX REG */
#define PINMUX_G6_BASE_PHY_ADDR	0x2304000
#define PINMUX_G6_MISC_SET_ADDR (0xA8)
#define PINMUX_G6_CTRL_SET_SET	BIT(0)
#define PINMUX_G6_MISC_CLR_ADDR (0xAC)
#define PINMUX_G6_CTRL_CLR_CLR	BIT(0)

/* CPU SYS REG */
#define CPU_SYS_GLB_BASE_PHY_ADDR			0x1900000  /* physical addr */
#define CPU_SYS_CLK_MUX_0_ADDR				(0x0)
#define CPU_SYS_CLK_EB_0_ADDR				(0x04)
#define CPU_SYS_CLK_EB_1_ADDR				(0x08)
#define CPU_SYS_CLK_DIV_0_ADDR				(0x0C)
#define CPU_SYS_INT_MSK_SET_ADDR			(0x10D0)
#define BIT_CPU_SYS_CA53_CLUSTER_INT_DISABLE_SET 	BIT(0)
#define BIT_CPU_SYS_CA53_CPU_INT_DISABLE_SET		(3 << 4)
#define CPU_SYS_INT_MSK_CLR_ADDR			(0x20D0)
#define BIT_CPU_SYS_CA53_CLUSTER_INT_DISABLE_CLR	BIT(0)
#define BIT_CPU_SYS_CA53_CPU_INT_DISABLE_CLR		(3 << 4)
#define CPU_SYS_CLK_EB_1_CLR_ADDR			(0x2008)
#define BIT_CPU_SYS_PCLK_CPU_DBGMNR_EB_CLR		BIT(9)
#define BIT_CPU_SYS_ACLK_CPU_DBGMNR_EB_CLR		BIT(0)
#define BIT_CPU_SYS_PCLK_CPU_PERFMNR_EB_CLR		BIT(10)
#define BIT_CPU_SYS_ACLK_CPU_PERFMNR_EB_CLR		BIT(1)
#define BIT_CPU_SYS_CLK_PERFMNR_24M_EB_CLR		BIT(6)
#define BIT_CPU_SYS_HCLK_SPI_EB_CLR			BIT(8)
#define BIT_CPU_SYS_CLK_EMMC_EB_CLR			BIT(4)
#define BIT_CPU_SYS_CLK_ROSC_EB_CLR			BIT(7)
#define CPU_SYS_CLK_EB_0_CLR_ADDR			(0x2004)
#define BIT_CPU_SYS_CLK_H_SSI_EB_CLR			BIT(3)
#define BIT_CPU_SYS_CLK_EMMC_CARD_EB_CLR		BIT(2)
#define BIT_CPU_SYS_CLK_BROM_EB_CLR			BIT(0)
#define CPU_SYS_LPC_CFG_2_SET_ADDR			(0x10F8)
#define BIT_CPU_SYS_SLP_EN_SET 				BIT(0)
#define BIT_CPU_SYS_DATA_IDLE_EN_SET			BIT(2)
#define CPU_SYS_LPC_CFG_1_SET_ADDR			(0x10F4)
#define BIT_CPU_SYS_DATA_BUS_IDLE_EN_SET 		BIT(0)
#define BIT_CPU_SYS_DATA_NOC_TIMEOUT_EN_SET		BIT(3)
#define CPU_SYS_LPC_CFG_0_SET_ADDR			(0x10F0)
#define BIT_CPU_SYS_CFG_BUS_IDLE_EN_SET			BIT(0)
#define BIT_CPU_SYS_CFG_NOC_TIMEOUT_EN_SET		BIT(3)
#define CPU_SYS_RSP2INT_CTRL_SET_ADDR			(0x1124)
#define BITS_CPU_ERR_INT_CLEAR_SET			(3 << 0)
#define BIT_CPU_SYS_CFG_BUS_IDLE_EN_CLR			BIT(0)
#define BIT_CPU_SYS_CFG_NOC_TIMEOUT_EN_CLR		BIT(3)
#define CPU_SYS_LPC_CFG_0_CLR_ADDR			(0x20F0)
#define BIT_CPU_SYS_DATA_BUS_IDLE_EN_CLR		BIT(0)
#define BIT_CPU_SYS_DATA_NOC_TIMEOUT_EN_CLR		BIT(3)
#define CPU_SYS_LPC_CFG_1_CLR_ADDR			(0x20F4)
#define CPU_SYS_LPC_CFG_2_CLR_ADDR			(0x20F8)
#define BIT_CPU_SYS_SLP_EN_CLR 				BIT(0)
#define BIT_CPU_SYS_DATA_IDLE_EN_CLR			BIT(2)
#define CPU_SYS_FAB_GT_CTRL0_ADDR			(0x104)
#define CPU_SYS_FAB_GT_CTRL0_VAL			BIT(0)

/* DBG SYS REG */
#define DEBUG_SYS_AUTO_GT_EN		(0x14)
#define DEBUG_SYS_AUTO_GT_EN_VAL	0x1

/* DDRC REG */
#define DDRC_GLB_BASE_PHY_ADDR			0x100000    /* physical addr */
#define DDRC_DDRMC_PORT0_CFG0_ADDR		(0x0)
#define BIT_DDRC_RF_AUTO_SLP_EN_PORT0		BIT(16)
#define DDRC_DDRMC_PORT1_CFG0_ADDR		(0x10)
#define BIT_DDRC_RF_AUTO_SLP_EN_PORT1		BIT(16)
#define DDRC_DDRMC_PORT2_CFG0_ADDR		(0x20)
#define BIT_DDRC_RF_AUTO_SLP_EN_PORT2		BIT(16)
#define DDRC_DDRMC_PORT3_CFG0_ADDR		(0x30)
#define BIT_DDRC_RF_AUTO_SLP_EN_PORT3		BIT(16)
#define DDRC_DDRMC_PORT4_CFG0_ADDR		(0x40)
#define BIT_DDRC_RF_AUTO_SLP_EN_PORT4		BIT(16)
#define DDRC_DDRMC_CFG22_ADDR			(0xD8)
#define BIT_DDRC_RF_AUTO_SLP_EN			BIT(0)
#define D_DDRPHYB_AC_CFG9_ADDR			0x121024
#define	D_DDRIOMUX_CLK_OUT				BIT(15)
#define	D_DDRIOMUX_CLK_OE				BIT(31)
#define D_DDRPHYB_AC_CFG8_ADDR			0x121020
#define	D_DDRIOMUX_CLK_SEL				BIT(15)
#define	D_DDRIOMUX_CLK_IE				BIT(31)
#define D_DDRPHYB_AC_CFG7_ADDR			0x12101c
#define	D_DDRIOMUX_CKE_OUT				BIT(6)
#define	D_DDRIOMUX_CKE_OE				BIT(22)
#define D_DDRPHYB_AC_CFG6_ADDR			0x121018
#define	D_DDRIOMUX_CKE_SEL				BIT(6)
#define	D_DDRIOMUX_CKE_IE				BIT(22)
#define D_DDRMC_CFG18_ADDR				0x1000c8
#define D_DDRMC_AUTO_GATE_EN_PHY		0xffffffff
#define D_DDRMC_TMG18_F0_ADDR			0x1001c8
#define D_DDRMC_TMG18_F1_ADDR			0x100248
#define D_DDRMC_CA_CS_CLK_OE			(0xf << 24)

/* FLASH SYS GLB REG */
#define FLASH_SYS_CLK_MUX_0_ADDR		(0x0)
#define FLASH_SYS_CLK_EB_0_ADDR			(0x4)
#define BITS_FLASH_SYS_CLK_EB_0			(1 << 5)
#define FLASH_SYS_CLK_EB_1_ADDR			(0x8)
#define BITS_FLASH_SYS_CLK_EB_1			0x00800
#define FLASH_SYS_CLK_DIV_0_ADDR		(0xC)
#define FLASH_SYS_CLK_DIV_1_ADDR		(0x10)
#define FLASH_SYS_LPC_CFG_SET_ADDR		(0x4148)
#define BIT_FLASH_LPC_CFG_BUS_IDLE_EN_SET	BIT(0)
#define FLASH_SYS_LPC_DATA_ADDR			(0x14C)
#define BIT_FLASH_LPC_DATA_BUS_FRC_WORK		BIT(2)
#define FLASH_SYS_LPC_CFG_SET_ADDR		(0x4148)
#define BIT_FLASH_LPC_CFG_BUS_IDLE_EN_SET	BIT(0)
#define FLASH_SYS_FAB_BUSY_ADDR			(0x178)
#define FLASH_SYS_LPC_DATA_SET_ADDR		(0x414C)
#define BIT_FLASH_LPC_DATA_BUS_IDLE_EN_SET	BIT(0)
#define FLASH_SYS_LPC_SET_ADDR			(0x4150)
#define BIT_FLASH_LPC_SLP_EN_SET		BIT(2)
#define BIT_FLASH_LPC_DATA_IDLE_EN_SET		BIT(3)
#define BIT_FLASH_LPC_BP_CLK_EB_SET		BIT(0)
#define FLASH_SYS_LPC_CFG_CLR_ADDR		(0x8148)
#define BIT_FLASH_LPC_CFG_BUS_IDLE_EN_CLR	BIT(0)
#define FLASH_SYS_LPC_DATA_CLR_ADDR		(0x814C)
#define BIT_FLASH_LPC_DATA_BUS_IDLE_EN_CLR	BIT(0)
#define FLASH_SYS_LPC_CLR_ADDR			(0x8150)
#define BIT_FLASH_LPC_SLP_EN_CLR		BIT(2)
#define BIT_FLASH_LPC_DATA_IDLE_EN_CLR		BIT(3)

/* ISP SYS GLB REG */
#define ISP_SYS_CLK_MUX_0_ADDR			(0x0)
#define ISP_SYS_CLK_EB_0_ADDR			(0x4)
#define BITS_ISP_CLK_EB_0				0x08
#define ISP_SYS_CLK_EB_1_ADDR			(0x8)
#define BITS_ISP_CLK_EB_1				0x8
#define ISP_SYS_LPC_DATA_SET_ADDR		(0x100)
#define BIT_ISP_LPC_DATA_BUS_IDLE_EN_SET	BIT(2)
#define ISP_SYS_LPC_CFG_SET_ADDR		(0x110)
#define BIT_ISP_LPC_CFG_BUS_IDLE_EN_SET		BIT(2)
#define ISP_SYS_LPC_DATA_SET_ADDR		(0x100)
#define BIT_ISP_LPC_DATA_IDLE_EN_SET		BIT(3)
#define ISP_SYS_SW_RST_1_CLR_ADDR		(0xEC)
#define BIT_ISP_SYS_LPC_SW_RST_CLR		BIT(18)
#define ISP_SYS_SLEEP_EN_SET_ADDR		(0xF8)
#define BIT_ISP_SLEEP_EN_SET			BIT(1)
#define ISP_SYS_LPC_DATA_CLR_ADDR		(0x104)
#define BIT_ISP_LPC_DATA_BUS_IDLE_EN_CLR	BIT(2)
#define ISP_SYS_LPC_CFG_CLR_ADDR		(0x114)
#define BIT_ISP_LPC_CFG_BUS_IDLE_EN_CLR		BIT(2)
#define ISP_SYS_LPC_DATA_CLR_ADDR		(0x104)
#define BIT_ISP_LPC_DATA_BUS_IDLE_EN_CLR	BIT(2)
#define BIT_ISP_LPC_DATA_IDLE_EN_CLR		BIT(3)
#define ISP_SYS_SLEEP_EN_CLR_ADDR		(0xFC)
#define BIT_ISP_SLEEP_EN_CLR			BIT(1)

/* MM SYS GLB REG */
#define MM_SYS_CLK_MUX_0_ADDR		(0x0)
#define MM_SYS_CLK_EB_0_ADDR		(0x4)
#define BITS_MM_SYS_CLK_EB_0		0x8
#define MM_SYS_CLK_EB_1_ADDR		(0x8)
#define BITS_MM_SYS_CLK_EB_1		0x400
#define MM_SYS_CLK_DIV_0_ADDR		(0xC)
#define MM_SYS_LPC1_SET_ADDR		(0x17C)
#define BIT_MM_LPC_CFG_BUS_IDLE_EN_SET	BIT(0)
#define MM_SYS_LPC2_SET_ADDR		(0x184)
#define BIT_MM_LPC_DATA_BUS_IDLE_EN_SET	BIT(0)
#define MM_SYS_LPC0_SET_ADDR		(0x174)
#define BIT_MM_LPC_SLP_EN_SET		BIT(0)
#define BIT_MM_DATA_IDLE_EN_SET		BIT(3)
#define MM_SYS_SW_RST_0_CLR_ADDR	(0xc8)
#define BIT_MM_SYS_LPC_SW_RST_CLR	BIT(18)
#define MM_SYS_LPC1_CLR_ADDR		(0x180)
#define BIT_MM_LPC_CFG_BUS_IDLE_EN_CLR	BIT(0)
#define MM_SYS_LPC2_CLR_ADDR		(0x188)
#define BIT_MM_LPC_DATA_BUS_IDLE_EN_CLR	BIT(0)
#define MM_SYS_LPC0_CLR_ADDR		(0x178)
#define BIT_MM_LPC_SLP_EN_CLR		BIT(0)
#define BIT_MM_DATA_IDLE_EN_CLR		BIT(3)

/* NPU SYS GLB REG */
#define NPU_SYS_CLK_MUX_0_ADDR			(0x0)
#define NPU_SYS_CLK_EB_0_ADDR			(0x4)
#define BITS_NPU_SYS_CLK_EB_0			0x1
#define NPU_SYS_CLK_EB_1_ADDR			(0x8)
#define BITS_NPU_SYS_CLK_EB_1			0x2
#define NPU_SYS_LPC_CFG_SETTING_SET_ADDR	(0x84)
#define BIT_NPU_SYS_CFG_BUS_IDLE_EN_SET		BIT(0)
#define NPU_SYS_LPC_DATA_SETTING_SET_ADDR	(0x8C)
#define BIT_NPU_SYS_DATA_BUS_IDLE_EN_SET	BIT(0)
#define NPU_SYS_LPC_SETTING_SET_ADDR		(0x7C)
#define BIT_NPU_SYS_SLP_EN_SET			BIT(0)
#define BIT_NPU_SYS_DATA_IDLE_EB_SET		BIT(3)
#define NPU_SYS_SW_RST_0_CLR_ADDR		(0x78)
#define BIT_NPU_SYS_LPC_SW_RST_CLR		BIT(0)
#define NPU_SYS_EU_IDLE_STS_ADDR		(0x48)
#define NPU_SYS_LPC_CFG_SETTING_CLR_ADDR	(0x88)
#define BIT_NPU_SYS_CFG_BUS_IDLE_EN_CLR		BIT(0)
#define NPU_SYS_LPC_DATA_SETTING_CLR_ADDR	(0x90)
#define BIT_NPU_SYS_DATA_BUS_IDLE_EN_CLR	BIT(0)
#define NPU_SYS_LPC_SETTING_CLR_ADDR		(0x80)
#define BIT_NPU_SYS_SLP_EN_CLR			BIT(0)
#define BIT_NPU_SYS_DATA_IDLE_EB_CLR		BIT(3)

/* VPU SYS GLB REG */
#define VPU_SYS_CLK_MUX_0_ADDR			(0x0)
#define VPU_SYS_CLK_EB_0_ADDR			(0x4)
#define BITS_VPU_SYS_CLK_EB_0			0x1
#define VPU_SYS_CLK_EB_1_ADDR			(0x8)
#define BITS_VPU_SYS_CLK_EB_1			0x20
#define VPU_SYS_VENC1_LPC1_SET_ADDR		(0x22C)
#define BIT_VPU_LPC_CFG_BUS_IDLE_EN_SET		BIT(0)
#define VPU_SYS_VENC1_LPC2_SET_ADDR		(0x234)
#define BIT_VPU_LPC_DATA_BUS_IDLE_EN_SET	BIT(0)
#define VPU_SYS_VENC1_LPC0_SET_ADDR		(0x224)
#define BIT_VPU_LPC_SLP_EN_SET			BIT(0)
#define BIT_VPU_DATA_IDLE_EN_SET		BIT(3)
#define VPU_SYS_SW_RST_0_CLR_ADDR		(0x120)
#define BIT_VPU_SYS_LPC_SW_RST_CLR		BIT(5)
#define VPU_SYS_VENC1_LPC0_CLR_ADDR		(0x228)
#define BIT_VPU_LPC_SLP_EN_CLR			BIT(0)
#define BIT_VPU_DATA_IDLE_EN_CLR		BIT(3)
#define VPU_SYS_VENC1_LPC1_CLR_ADDR		(0x230)
#define BIT_VPU_LPC_CFG_BUS_IDLE_EN_CLR		BIT(0)
#define VPU_SYS_VENC1_LPC2_CLR_ADDR		(0x238)
#define BIT_VPU_LPC_DATA_BUS_IDLE_EN_CLR	BIT(0)

/* PERIPH SYS GLB REG */
#define PERIPH_SYS_CLK_MUX_0_ADDR			(0x00)
#define PERIPH_SYS_CLK_EB_0_ADDR			(0x04)
#define PERIPH_SYS_CLK_EB_0_CLR_ADDR			(0xB4)
#define BITS_PERIPH_SYS_CLK_EB_0			(0x37FDF) /* dont't clr clk_periph_24m and clk_wdt2_eb */
#define PERIPH_SYS_CLK_EB_1_ADDR			(0x08)
#define BITS_PERIPH_SYS_CLK_EB_1			(1 << 18)
#define PERIPH_SYS_CLK_EB_2_ADDR			(0x0C)
#define BITS_PERIPH_SYS_CLK_EB_2			0x0
#define PERIPH_SYS_CLK_EB_3_ADDR			(0x10)
#define BITS_PERIPH_SYS_CLK_EB_3			0x0
#define PERIPH_SYS_CLK_DIV_0_ADDR			(0x14)
#define PERIPH_SYS_LPC_CFG_SET_ADDR			(0x178)
#define BIT_PERIPH_SYS_LPC_CFG_BUS_IDLE_EN_SET		BIT(0)
#define PERIPH_SYS_LPC_CFG_CLR_ADDR			(0x17C)
#define BIT_PERIPH_SYS_LPC_CFG_BUS_IDLE_EN_CLR		BIT(0)
#define PERIPH_SYS_LPC_DATA_SET_ADDR			(0x180)
#define BIT_PERIPH_SYS_LPC_DATA_BUS_IDLE_EN_SET		BIT(0)
#define BIT_PERIPH_SYS_LPC_DATA_BUS_FRC_WORK_SET	BIT(2)
#define PERIPH_SYS_LPC_DATA_CLR_ADDR			(0x184)
#define BIT_PERIPH_SYS_LPC_DATA_BUS_IDLE_EN_CLR		BIT(0)
#define BIT_PERIPH_SYS_LPC_DATA_BUS_FRC_WORK_CLR	BIT(2)
#define PERIPH_SYS_LPC_SET_ADDR				(0x188)
#define BIT_PERIPH_SYS_LPC_BP_CLK_EB_SET		BIT(0)
#define BIT_PERIPH_SYS_LPC_SLP_EN_SET			BIT(16)
#define BIT_PERIPH_SYS_LPC_DATA_IDLE_EN_SET		BIT(24)
#define PERIPH_SYS_LPC_CLR_ADDR				(0x18C)
#define BIT_PERIPH_SYS_LPC_SLP_EN_CLR			BIT(16)
#define BIT_PERIPH_SYS_LPC_DATA_IDLE_EN_CLR		BIT(24)
#define PERIPH_SYS_SW_RST_1_CLR_ADDR			(0xE4)
#define BIT_PERIPH_SYS_LPC_SW_RST_CLR			BIT(14)

/* DDR SYS GLB REG */
#define DDR_SYS_GLB_BASE_PHY_ADDR			0x210000    /* physical addr */
#define DDR_SYS_AXICLK_OFF_SET_ADDR		(0x180)
#define BIT_DDR_SYS_AXICLK_OFF_HW_EN_SET	BIT(1)
#define DDR_SYS_AXICLK_OFF_CLR_ADDR		(0x184)
#define BIT_DDR_SYS_AXICLK_OFF_HW_EN_CLR	BIT(1)
#define DDR_SYS_CORECLK_OFF_SET_ADDR		(0x188)
#define BIT_DDR_SYS_CORECLK_OFF_HW_EN_SET	BIT(1)
#define DDR_SYS_CORECLK_OFF_CLR_ADDR		(0x18C)
#define BIT_DDR_SYS_CORECLK_OFF_HW_EN_CLR	BIT(1)
#define DDR_SYS_DDRC_WAKEUP_SET_ADDR		(0x168)
#define BIT_DDR_SYS_DDRC_WAKEUP_SW_SET		BIT(0)
#define DDR_SYS_DDRC_WAKEUP_CLR_ADDR		(0x16C)
#define DDR_SYS_DDR_DEEP_SLEEP_LATCH_CLR_ADDR	(0xAC)
#define BIT_DDR_SYS_DPLL_LPC_OFF_CLR		BIT(1)
#define BIT_DDR_SYS_DDRC_WAKEUP_SW_CLR		BIT(0)
#define DDR_SYS_LPC_DATA_SET_ADDR		(0x170)
#define BIT_DDR_SYS_LPC_DATA_BUS_FORCE_IDLE_SET_LSB    BIT(1)
#define BIT_DDR_SYS_LPC_DATA_BUS_IDLE_EN_SET	BIT(0)
#define DDR_SYS_LPC_DATA_CLR_ADDR		(0x174)
#define BIT_DDR_SYS_LPC_DATA_BUS_FORCE_IDLE_CLR_LSB    BIT(1)
#define BIT_DDR_SYS_LPC_DATA_BUS_IDLE_EN_CLR	BIT(0)
#define DDR_SYS_SLP_IGNORE_CPU_SET_ADDR		(0x178)
#define BIT_DDR_SYS_SLP_IGNORE_CPU_EN_SET	BIT(0)
#define DDR_SYS_DDR_AXI_SET_ADDR		(0x158)
#define BITS_DDR_SYS_DDR_AXI_LP_REQ_SET		(0x1F << 0)
#define DDR_SYS_DDR_AXI_CLR_ADDR		(0x15C)
#define BITS_DDR_SYS_DDR_AXI_LP_REQ_CLR		(0x1F << 0)
#define DDR_SYS_DDRC_SLP_SET_ADDR		(0x160)
#define BIT_DDR_SYS_DDRC_SLP_SW_SET		BIT(0)
#define DDR_SYS_DDRC_SLP_CLR_ADDR		(0x164)
#define BIT_DDR_SYS_DDRC_SLP_SW_CLR		BIT(0)
#define DDR_SYS_LP_DDRC_ADDR			(0x80)
#define BITS_DDR_SYS_LP_DDRC_STATE		(0x3F << 0)
#define DDR_SYS_LP_DDRC_ENTER_LIGHT_SLP		0x23
#define DDR_SYS_LP_DDRC_EXIT_LIGHT_SLP		0x0
#define DDR_SYS_DDR_DEEP_SLP_LATCH_CLR_SET_ADDR	(0x208)
#define BIT_DDR_SYS_DDRPHY_PD_LATCH_CLR_SET	BIT(0)
#define DDR_SYS_CLKG_BYPASS_CLR_ADDR		(0x154)
#define BIT_DDR_SYS_CLKG_BYPASS_DDRC_REF_CLR	BIT(3)
#define BIT_DDR_SYS_CLKG_BYPASS_AXI_CLR		BIT(2)
#define BIT_DDR_SYS_CLKG_BYPASS_DDRPHY_CLR	BIT(1)
#define BIT_DDR_SYS_CLKG_BYPASS_DDRC_CLR	BIT(0)

/* DPLL B */
#define DPLL_BASE_PHY_ADDR			0x265000
#define DDR_SYS_PLL_RDY_STS_ADDR		(0x40)
#define BIT_DDR_STS_DPLL_RSY			BIT(0)

/* COMMON CPU GLB REG */
#define CA53_CFG_RVBARADDR0_H				(0x4)
#define CA53_CFG_RVBARADDR0_L				(0x8)
#define CA53_CFG_RVBARADDR1_H				(0xC)
#define CA53_CFG_RVBARADDR1_L				(0x10)

/* GTIMER REG */
#define GTMR_BASE_PHY_ADDR		0x1b30000
#define GTMR_CNTCR           		0x0
#define GTMR_CNTCVL          		0x8
#define GTMR_CNTCVU          		0xC
#define GTMR_CNTFID0         		0x20
#define BITS_ENABLE_GTMR    	 	0x11
#define GTMR_FREQ			0x16e3600

/* TIMER32 REG */
#define TIMER32_BASE_PHY_ADDR		0x2240000
#define TIMER32_CNT_CCVR		(0x0)
#define TIMER32_CMR			(0x4)
#define TIMER32_CMR_START		(0x10)
#define TIMER32_INTR_STATUS		(0x28)
#define BIT_TIMER32_CMR_START		BIT(0)
#define TIMER32_INTR_CTRL		(0x1C)
#define BIT_TIMER32_INTR_EOI		BIT(2)
#define BIT_TIMER32_INTR_MASK		BIT(1)
#define BIT_TIMER32_INTR_EN		BIT(0)

/* TIMER64 REG */
#define TIMER64_CNT_LOW_ADDR		0x2250000
#define TIMER64_CNT_HIGH_ADDR		0x2250004

/* PLLC GLB REG */
#define PLLC_GLB_REG_BASE		0x2210000
#define PLL_GRP_PLL_FRC_EN_SW_SET_ADDR	(0x228)
#define BIT_PLL_GRP_PLL_FRC_EN_SW_SET	0x1
#define PLL_GRP_PLL_FRC_EN_SET_ADDR	(0x21C)
#define BIT_PLL_GRP_PLL_FRC_EN_SET	0x1
#define PLL_CPLL_ON_CFG_CLR_ADDR	(0x1CC)
#define BITS_PLL_CPLL_ON_CFG_CLR	(0xffffff << 1)
#define PLL_CPUPLL_ON_CFG_CLR_ADDR	(0x1F0)
#define BITS_PLL_CPUPLL_ON_CFG_CLR	(0xff << 9)
#define PLL_EPLL_ON_CFG_CLR_ADDR	(0x1FC)
#define BITS_PLL_EPLL_ON_CFG_CLR	(0xff << 9)
#define PLL_HPLL_ON_CFG_CLR_ADDR	(0x214)
#define BITS_PLL_HPLL_ON_CFG_CLR	(0xff << 9)
#define PLL_NPLL_ON_CFG_CLR_ADDR	(0x208)
#define BITS_PLL_NPLL_ON_CFG_CLR	(0xff << 9)
#define PLL_VPLL0_ON_CFG_CLR_ADDR	(0x1D8)
#define BITS_PLL_VPLL0_ON_CFG_CLR	(0xff << 9)
#define PLL_VPLL1_ON_CFG_CLR_ADDR	(0x1E4)
#define BITS_PLL_VPLL1_ON_CFG_CLR	(0xff << 9)
#define PLL_GRP_PLL_RE_OPEN_SET_ADDR	(0x234)
#define PLL_GRP_PLL_RE_OPEN_CLR_ADDR	(0x238)

/* DPLL_CTRL GLB REG */
#define DPLL_CTRL_GLB_BASE_ADDR			0x265000
#define DPLL_ON_CFG_CLR_ADDR			(0x4C)
#define BITS_DPLL_ON_CFG_CLR			(0xff << 9)
#define DPLL_PLL_RE_OPEN_ADDR			(0x68)

/* IRAM SPACE: iram start addr is 0, offset = phyaddr*/
#define IRAM_BASE_PHY_ADDR			0x0
/* as tuning guys dont't want to change hardware to support pll work around code,
 *so we have to set a flag under below addr to judge if we can use pll work around code or not.
*/
#define PLL_ALWAYS_ON_ADDR	0x10F4
#define TIMER_EB_ADDR				0x10F8   /* enable auto timer wake */
#define TIMER_COUNT_ADDR 			0x10FC
#define A64_WARMRST_A32_ADDR			0x3000
#define CPU_SYS_SLEEP_CODE_ADDR			0x3400
#define DDR_SYS_SLEEP_CODE_ADDR			0x3A00
#define CPU_CLK_MUX_0_BAK_ADDR			0x4000
#define CPU_CLK_EB_0_BAK_ADDR			0x4004
#define CPU_CLK_EB_1_BAK_ADDR			0x4008
#define CPU_CLK_DIV_0_BAK_ADDR			0x400C
#define CPU_RESUME_PHY_ADDR			0x4010		/* cpu_resume physical addr backup here */
#define PEN_RELEASE_PHY_ADDR			0x4014		/* pen release physical addr backup here */
#define SECONDARY_STARTUP_PHY_ADDR		0x4018		/* secondary_startup physical addr backup here */
#define A64_TO_A32_CNT_ADDR			0x401C
#define COMMON_CLK_MUX_0_BAK_ADDR		0x4020
#define COMMON_CLK_MUX_2_BAK_ADDR		0x4024
#define WAKEUP_START_TIMESTAMP_ADDR		0x4028
#define IRAM_SP_TEMP_ADDR			0x4FFC
#define IRAM_SLP_WAKE_CODE_SZ_MAX		0x700
#define IRAM_CHIP_TYPE_ADDR				0x784
#define IRAM_CHIP_TYPE_Q				0x1
#endif
