#ifndef __AX620E_PM_H__
#define __AX620E_PM_H__

typedef enum {
	AX_KERNEL_SLEEP_STAGE_00 = 0xFF00,
	AX_KERNEL_SLEEP_STAGE_01,
	AX_KERNEL_SLEEP_STAGE_02,
	AX_KERNEL_SLEEP_STAGE_03,
	AX_KERNEL_SLEEP_STAGE_04,
	AX_KERNEL_SLEEP_STAGE_05,
	AX_KERNEL_SLEEP_STAGE_06,
	AX_KERNEL_SLEEP_STAGE_07,
	AX_KERNEL_SLEEP_STAGE_08,
	AX_KERNEL_SLEEP_STAGE_09,
	AX_KERNEL_SLEEP_STAGE_0A,
	AX_KERNEL_SLEEP_STAGE_0B,
	AX_KERNEL_SLEEP_STAGE_0C,
	AX_KERNEL_SLEEP_STAGE_0D,
	AX_KERNEL_WAKEUP_STAGE_0E,
	AX_KERNEL_WAKEUP_STAGE_0F,
	AX_KERNEL_WAKEUP_STAGE_10,
	AX_KERNEL_WAKEUP_STAGE_11,
	AX_KERNEL_WAKEUP_STAGE_12,
	AX_KERNEL_WAKEUP_STAGE_13,
	AX_KERNEL_WAKEUP_STAGE_14,
	AX_KERNEL_WAKEUP_STAGE_15,
	AX_KERNEL_WAKEUP_STAGE_16,
	AX_KERNEL_WAKEUP_STAGE_17,
	AX_KERNEL_WAKEUP_STAGE_18,
	AX_KERNEL_WAKEUP_STAGE_19,
	AX_KERNEL_WAKEUP_STAGE_1A,
	AX_KERNEL_WAKEUP_STAGE_1B,
	AX_KERNEL_WAKEUP_STAGE_1C,
	AX_KERNEL_WAKEUP_STAGE_1D,
	AX_KERNEL_WAKEUP_STAGE_1E,
	AX_KERNEL_WAKEUP_STAGE_1F,
} AX_KERNEL_SLEEP_STAGE_E;

#ifdef CONFIG_ARCH_AX620E
int ax620e_suspend_enter(suspend_state_t state);
int ax620e_suspend_prepare(void);
void ax620e_suspend_finish(void);
int ax620e_suspend_init(struct device_node *np);
#else
int ax620e_suspend_enter(suspend_state_t state)
{}
int ax620e_suspend_prepare(void)
{}
void ax620e_suspend_finish(void)
{}
int ax620e_suspend_init(struct device_node *np)
{}
#endif
#endif
