#ifndef __RTC_AXERA_H__
#define __RTC_AXERA_H__
// BASE ADDRESS

#define RTC_BASE_ADDR    0X0

// REGISTER : PASSWORD

#define RTC_PASSWORD_ADDR      RTC_BASE_ADDR + 0X0
#define RTC_PASSWORD_RSTVAL    0X0
#define RTC_PASSWORD_ALL1      0XFFFFFFFF
#define RTC_PASSWORD_ALL0      0X0
#define RTC_PASSWORD_ALL5A     0X5A5A5A5A
#define RTC_PASSWORD_ALLA5     0XA5A5A5A5

// FIELD IN REGISTER : PASSWORD

#define RTC_PASSWORD_POS      0
#define RTC_PASSWORD_LEN      32
#define RTC_PASSWORD_MASK     0XFFFFFFFF
#define RTC_PASSWORD_VAL(w)   (((w) & 0XFFFFFFFF) >> 0)
#define RTC_PASSWORD_SET(w)   w |= ( 0XFFFFFFFF << 0)
#define RTC_PASSWORD_CLR(w)   w &= ~( 0XFFFFFFFF << 0)

// REGISTER : X32K_XIN_EN

#define RTC_X32K_XIN_EN_ADDR      RTC_BASE_ADDR + 0X4
#define RTC_X32K_XIN_EN_RSTVAL    0X1
#define RTC_X32K_XIN_EN_ALL1      0X1
#define RTC_X32K_XIN_EN_ALL0      0X0
#define RTC_X32K_XIN_EN_ALL5A     0X0
#define RTC_X32K_XIN_EN_ALLA5     0X1

// FIELD IN REGISTER : X32K_XIN_EN

#define RTC_X32K_XIN_EN_POS      0
#define RTC_X32K_XIN_EN_LEN      1
#define RTC_X32K_XIN_EN_MASK     0X00000001
#define RTC_X32K_XIN_EN_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_X32K_XIN_EN_SET(w)   w |= ( 0X1 << 0)
#define RTC_X32K_XIN_EN_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : X32K_XIN_EN_SET

#define RTC_X32K_XIN_EN_SET_ADDR      RTC_BASE_ADDR + 0X8
#define RTC_X32K_XIN_EN_SET_RSTVAL    0X0
#define RTC_X32K_XIN_EN_SET_ALL1      0X0
#define RTC_X32K_XIN_EN_SET_ALL0      0X0
#define RTC_X32K_XIN_EN_SET_ALL5A     0X0
#define RTC_X32K_XIN_EN_SET_ALLA5     0X0

// FIELD IN REGISTER : X32K_XIN_EN_SET

#define RTC_X32K_XIN_EN_SET_POS      0
#define RTC_X32K_XIN_EN_SET_LEN      1
#define RTC_X32K_XIN_EN_SET_MASK     0X00000001
#define RTC_X32K_XIN_EN_SET_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_X32K_XIN_EN_SET_SET(w)   w |= ( 0X1 << 0)
#define RTC_X32K_XIN_EN_SET_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : X32K_XIN_EN_CLR

#define RTC_X32K_XIN_EN_CLR_ADDR      RTC_BASE_ADDR + 0XC
#define RTC_X32K_XIN_EN_CLR_RSTVAL    0X0
#define RTC_X32K_XIN_EN_CLR_ALL1      0X0
#define RTC_X32K_XIN_EN_CLR_ALL0      0X0
#define RTC_X32K_XIN_EN_CLR_ALL5A     0X0
#define RTC_X32K_XIN_EN_CLR_ALLA5     0X0

// FIELD IN REGISTER : X32K_XIN_EN_CLR

#define RTC_X32K_XIN_EN_CLR_POS      0
#define RTC_X32K_XIN_EN_CLR_LEN      1
#define RTC_X32K_XIN_EN_CLR_MASK     0X00000001
#define RTC_X32K_XIN_EN_CLR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_X32K_XIN_EN_CLR_SET(w)   w |= ( 0X1 << 0)
#define RTC_X32K_XIN_EN_CLR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : RST_CTRL_SW

#define RTC_RST_CTRL_SW_ADDR      RTC_BASE_ADDR + 0X10
#define RTC_RST_CTRL_SW_RSTVAL    0X1
#define RTC_RST_CTRL_SW_ALL1      0X1
#define RTC_RST_CTRL_SW_ALL0      0X0
#define RTC_RST_CTRL_SW_ALL5A     0X0
#define RTC_RST_CTRL_SW_ALLA5     0X1

// FIELD IN REGISTER : RST_CTRL_SW

#define RTC_RST_CTRL_SW_POS      0
#define RTC_RST_CTRL_SW_LEN      1
#define RTC_RST_CTRL_SW_MASK     0X00000001
#define RTC_RST_CTRL_SW_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_RST_CTRL_SW_SET(w)   w |= ( 0X1 << 0)
#define RTC_RST_CTRL_SW_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : RST_CTRL_SW_SET

#define RTC_RST_CTRL_SW_SET_ADDR      RTC_BASE_ADDR + 0X14
#define RTC_RST_CTRL_SW_SET_RSTVAL    0X0
#define RTC_RST_CTRL_SW_SET_ALL1      0X0
#define RTC_RST_CTRL_SW_SET_ALL0      0X0
#define RTC_RST_CTRL_SW_SET_ALL5A     0X0
#define RTC_RST_CTRL_SW_SET_ALLA5     0X0

// FIELD IN REGISTER : RST_CTRL_SW_SET

#define RTC_RST_CTRL_SW_SET_POS      0
#define RTC_RST_CTRL_SW_SET_LEN      1
#define RTC_RST_CTRL_SW_SET_MASK     0X00000001
#define RTC_RST_CTRL_SW_SET_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_RST_CTRL_SW_SET_SET(w)   w |= ( 0X1 << 0)
#define RTC_RST_CTRL_SW_SET_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : RST_CTRL_SW_CLR

#define RTC_RST_CTRL_SW_CLR_ADDR      RTC_BASE_ADDR + 0X18
#define RTC_RST_CTRL_SW_CLR_RSTVAL    0X0
#define RTC_RST_CTRL_SW_CLR_ALL1      0X0
#define RTC_RST_CTRL_SW_CLR_ALL0      0X0
#define RTC_RST_CTRL_SW_CLR_ALL5A     0X0
#define RTC_RST_CTRL_SW_CLR_ALLA5     0X0

// FIELD IN REGISTER : RST_CTRL_SW_CLR

#define RTC_RST_CTRL_SW_CLR_POS      0
#define RTC_RST_CTRL_SW_CLR_LEN      1
#define RTC_RST_CTRL_SW_CLR_MASK     0X00000001
#define RTC_RST_CTRL_SW_CLR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_RST_CTRL_SW_CLR_SET(w)   w |= ( 0X1 << 0)
#define RTC_RST_CTRL_SW_CLR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : FAKE_32K_EB

#define RTC_FAKE_32K_EB_ADDR      RTC_BASE_ADDR + 0X1C
#define RTC_FAKE_32K_EB_RSTVAL    0X0
#define RTC_FAKE_32K_EB_ALL1      0X1
#define RTC_FAKE_32K_EB_ALL0      0X0
#define RTC_FAKE_32K_EB_ALL5A     0X0
#define RTC_FAKE_32K_EB_ALLA5     0X1

// FIELD IN REGISTER : FAKE_32K_EB

#define RTC_FAKE_32K_EB_POS      0
#define RTC_FAKE_32K_EB_LEN      1
#define RTC_FAKE_32K_EB_MASK     0X00000001
#define RTC_FAKE_32K_EB_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_FAKE_32K_EB_SET(w)   w |= ( 0X1 << 0)
#define RTC_FAKE_32K_EB_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : FAKE_32K_EB_SET

#define RTC_FAKE_32K_EB_SET_ADDR      RTC_BASE_ADDR + 0X20
#define RTC_FAKE_32K_EB_SET_RSTVAL    0X0
#define RTC_FAKE_32K_EB_SET_ALL1      0X0
#define RTC_FAKE_32K_EB_SET_ALL0      0X0
#define RTC_FAKE_32K_EB_SET_ALL5A     0X0
#define RTC_FAKE_32K_EB_SET_ALLA5     0X0

// FIELD IN REGISTER : FAKE_32K_EB_SET

#define RTC_FAKE_32K_EB_SET_POS      0
#define RTC_FAKE_32K_EB_SET_LEN      1
#define RTC_FAKE_32K_EB_SET_MASK     0X00000001
#define RTC_FAKE_32K_EB_SET_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_FAKE_32K_EB_SET_SET(w)   w |= ( 0X1 << 0)
#define RTC_FAKE_32K_EB_SET_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : FAKE_32K_EB_CLR

#define RTC_FAKE_32K_EB_CLR_ADDR      RTC_BASE_ADDR + 0X24
#define RTC_FAKE_32K_EB_CLR_RSTVAL    0X0
#define RTC_FAKE_32K_EB_CLR_ALL1      0X0
#define RTC_FAKE_32K_EB_CLR_ALL0      0X0
#define RTC_FAKE_32K_EB_CLR_ALL5A     0X0
#define RTC_FAKE_32K_EB_CLR_ALLA5     0X0

// FIELD IN REGISTER : FAKE_32K_EB_CLR

#define RTC_FAKE_32K_EB_CLR_POS      0
#define RTC_FAKE_32K_EB_CLR_LEN      1
#define RTC_FAKE_32K_EB_CLR_MASK     0X00000001
#define RTC_FAKE_32K_EB_CLR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_FAKE_32K_EB_CLR_SET(w)   w |= ( 0X1 << 0)
#define RTC_FAKE_32K_EB_CLR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : SET_SEC

#define RTC_SET_SEC_ADDR      RTC_BASE_ADDR + 0X28
#define RTC_SET_SEC_RSTVAL    0X0
#define RTC_SET_SEC_ALL1      0XFF
#define RTC_SET_SEC_ALL0      0X0
#define RTC_SET_SEC_ALL5A     0X5A
#define RTC_SET_SEC_ALLA5     0XA5

// FIELD IN REGISTER : SET_SEC

#define RTC_SET_SEC_POS      0
#define RTC_SET_SEC_LEN      8
#define RTC_SET_SEC_MASK     0X000000FF
#define RTC_SET_SEC_VAL(w)   (((w) & 0X000000FF) >> 0)
#define RTC_SET_SEC_SET(w)   w |= ( 0XFF << 0)
#define RTC_SET_SEC_CLR(w)   w &= ~( 0XFF << 0)

// REGISTER : SET_SEC_SET

#define RTC_SET_SEC_SET_ADDR      RTC_BASE_ADDR + 0X2C
#define RTC_SET_SEC_SET_RSTVAL    0X0
#define RTC_SET_SEC_SET_ALL1      0X0
#define RTC_SET_SEC_SET_ALL0      0X0
#define RTC_SET_SEC_SET_ALL5A     0X0
#define RTC_SET_SEC_SET_ALLA5     0X0

// FIELD IN REGISTER : SET_SEC_SET

#define RTC_SET_SEC_SET_POS      0
#define RTC_SET_SEC_SET_LEN      8
#define RTC_SET_SEC_SET_MASK     0X000000FF
#define RTC_SET_SEC_SET_VAL(w)   (((w) & 0X000000FF) >> 0)
#define RTC_SET_SEC_SET_SET(w)   w |= ( 0XFF << 0)
#define RTC_SET_SEC_SET_CLR(w)   w &= ~( 0XFF << 0)

// REGISTER : SET_SEC_CLR

#define RTC_SET_SEC_CLR_ADDR      RTC_BASE_ADDR + 0X30
#define RTC_SET_SEC_CLR_RSTVAL    0X0
#define RTC_SET_SEC_CLR_ALL1      0X0
#define RTC_SET_SEC_CLR_ALL0      0X0
#define RTC_SET_SEC_CLR_ALL5A     0X0
#define RTC_SET_SEC_CLR_ALLA5     0X0

// FIELD IN REGISTER : SET_SEC_CLR

#define RTC_SET_SEC_CLR_POS      0
#define RTC_SET_SEC_CLR_LEN      8
#define RTC_SET_SEC_CLR_MASK     0X000000FF
#define RTC_SET_SEC_CLR_VAL(w)   (((w) & 0X000000FF) >> 0)
#define RTC_SET_SEC_CLR_SET(w)   w |= ( 0XFF << 0)
#define RTC_SET_SEC_CLR_CLR(w)   w &= ~( 0XFF << 0)

// REGISTER : SET_MIN

#define RTC_SET_MIN_ADDR      RTC_BASE_ADDR + 0X34
#define RTC_SET_MIN_RSTVAL    0X0
#define RTC_SET_MIN_ALL1      0X3F
#define RTC_SET_MIN_ALL0      0X0
#define RTC_SET_MIN_ALL5A     0X1A
#define RTC_SET_MIN_ALLA5     0X25

// FIELD IN REGISTER : SET_MIN

#define RTC_SET_MIN_POS      0
#define RTC_SET_MIN_LEN      6
#define RTC_SET_MIN_MASK     0X0000003F
#define RTC_SET_MIN_VAL(w)   (((w) & 0X0000003F) >> 0)
#define RTC_SET_MIN_SET(w)   w |= ( 0X3F << 0)
#define RTC_SET_MIN_CLR(w)   w &= ~( 0X3F << 0)

// REGISTER : SET_MIN_SET

#define RTC_SET_MIN_SET_ADDR      RTC_BASE_ADDR + 0X38
#define RTC_SET_MIN_SET_RSTVAL    0X0
#define RTC_SET_MIN_SET_ALL1      0X0
#define RTC_SET_MIN_SET_ALL0      0X0
#define RTC_SET_MIN_SET_ALL5A     0X0
#define RTC_SET_MIN_SET_ALLA5     0X0

// FIELD IN REGISTER : SET_MIN_SET

#define RTC_SET_MIN_SET_POS      0
#define RTC_SET_MIN_SET_LEN      6
#define RTC_SET_MIN_SET_MASK     0X0000003F
#define RTC_SET_MIN_SET_VAL(w)   (((w) & 0X0000003F) >> 0)
#define RTC_SET_MIN_SET_SET(w)   w |= ( 0X3F << 0)
#define RTC_SET_MIN_SET_CLR(w)   w &= ~( 0X3F << 0)

// REGISTER : SET_MIN_CLR

#define RTC_SET_MIN_CLR_ADDR      RTC_BASE_ADDR + 0X3C
#define RTC_SET_MIN_CLR_RSTVAL    0X0
#define RTC_SET_MIN_CLR_ALL1      0X0
#define RTC_SET_MIN_CLR_ALL0      0X0
#define RTC_SET_MIN_CLR_ALL5A     0X0
#define RTC_SET_MIN_CLR_ALLA5     0X0

// FIELD IN REGISTER : SET_MIN_CLR

#define RTC_SET_MIN_CLR_POS      0
#define RTC_SET_MIN_CLR_LEN      6
#define RTC_SET_MIN_CLR_MASK     0X0000003F
#define RTC_SET_MIN_CLR_VAL(w)   (((w) & 0X0000003F) >> 0)
#define RTC_SET_MIN_CLR_SET(w)   w |= ( 0X3F << 0)
#define RTC_SET_MIN_CLR_CLR(w)   w &= ~( 0X3F << 0)

// REGISTER : SET_HOUR

#define RTC_SET_HOUR_ADDR      RTC_BASE_ADDR + 0X40
#define RTC_SET_HOUR_RSTVAL    0X0
#define RTC_SET_HOUR_ALL1      0X1F
#define RTC_SET_HOUR_ALL0      0X0
#define RTC_SET_HOUR_ALL5A     0X1A
#define RTC_SET_HOUR_ALLA5     0X5

// FIELD IN REGISTER : SET_HOUR

#define RTC_SET_HOUR_POS      0
#define RTC_SET_HOUR_LEN      5
#define RTC_SET_HOUR_MASK     0X0000001F
#define RTC_SET_HOUR_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_SET_HOUR_SET(w)   w |= ( 0X1F << 0)
#define RTC_SET_HOUR_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : SET_HOUR_SET

#define RTC_SET_HOUR_SET_ADDR      RTC_BASE_ADDR + 0X44
#define RTC_SET_HOUR_SET_RSTVAL    0X0
#define RTC_SET_HOUR_SET_ALL1      0X0
#define RTC_SET_HOUR_SET_ALL0      0X0
#define RTC_SET_HOUR_SET_ALL5A     0X0
#define RTC_SET_HOUR_SET_ALLA5     0X0

// FIELD IN REGISTER : SET_HOUR_SET

#define RTC_SET_HOUR_SET_POS      0
#define RTC_SET_HOUR_SET_LEN      5
#define RTC_SET_HOUR_SET_MASK     0X0000001F
#define RTC_SET_HOUR_SET_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_SET_HOUR_SET_SET(w)   w |= ( 0X1F << 0)
#define RTC_SET_HOUR_SET_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : SET_HOUR_CLR

#define RTC_SET_HOUR_CLR_ADDR      RTC_BASE_ADDR + 0X48
#define RTC_SET_HOUR_CLR_RSTVAL    0X0
#define RTC_SET_HOUR_CLR_ALL1      0X0
#define RTC_SET_HOUR_CLR_ALL0      0X0
#define RTC_SET_HOUR_CLR_ALL5A     0X0
#define RTC_SET_HOUR_CLR_ALLA5     0X0

// FIELD IN REGISTER : SET_HOUR_CLR

#define RTC_SET_HOUR_CLR_POS      0
#define RTC_SET_HOUR_CLR_LEN      5
#define RTC_SET_HOUR_CLR_MASK     0X0000001F
#define RTC_SET_HOUR_CLR_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_SET_HOUR_CLR_SET(w)   w |= ( 0X1F << 0)
#define RTC_SET_HOUR_CLR_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : SET_DAY

#define RTC_SET_DAY_ADDR      RTC_BASE_ADDR + 0X4C
#define RTC_SET_DAY_RSTVAL    0X0
#define RTC_SET_DAY_ALL1      0XFFFF
#define RTC_SET_DAY_ALL0      0X0
#define RTC_SET_DAY_ALL5A     0X5A5A
#define RTC_SET_DAY_ALLA5     0XA5A5

// FIELD IN REGISTER : SET_DAY

#define RTC_SET_DAY_POS      0
#define RTC_SET_DAY_LEN      16
#define RTC_SET_DAY_MASK     0X0000FFFF
#define RTC_SET_DAY_VAL(w)   (((w) & 0X0000FFFF) >> 0)
#define RTC_SET_DAY_SET(w)   w |= ( 0XFFFF << 0)
#define RTC_SET_DAY_CLR(w)   w &= ~( 0XFFFF << 0)

// REGISTER : SET_DAY_SET

#define RTC_SET_DAY_SET_ADDR      RTC_BASE_ADDR + 0X50
#define RTC_SET_DAY_SET_RSTVAL    0X0
#define RTC_SET_DAY_SET_ALL1      0X0
#define RTC_SET_DAY_SET_ALL0      0X0
#define RTC_SET_DAY_SET_ALL5A     0X0
#define RTC_SET_DAY_SET_ALLA5     0X0

// FIELD IN REGISTER : SET_DAY_SET

#define RTC_SET_DAY_SET_POS      0
#define RTC_SET_DAY_SET_LEN      16
#define RTC_SET_DAY_SET_MASK     0X0000FFFF
#define RTC_SET_DAY_SET_VAL(w)   (((w) & 0X0000FFFF) >> 0)
#define RTC_SET_DAY_SET_SET(w)   w |= ( 0XFFFF << 0)
#define RTC_SET_DAY_SET_CLR(w)   w &= ~( 0XFFFF << 0)

// REGISTER : SET_DAY_CLR

#define RTC_SET_DAY_CLR_ADDR      RTC_BASE_ADDR + 0X54
#define RTC_SET_DAY_CLR_RSTVAL    0X0
#define RTC_SET_DAY_CLR_ALL1      0X0
#define RTC_SET_DAY_CLR_ALL0      0X0
#define RTC_SET_DAY_CLR_ALL5A     0X0
#define RTC_SET_DAY_CLR_ALLA5     0X0

// FIELD IN REGISTER : SET_DAY_CLR

#define RTC_SET_DAY_CLR_POS      0
#define RTC_SET_DAY_CLR_LEN      16
#define RTC_SET_DAY_CLR_MASK     0X0000FFFF
#define RTC_SET_DAY_CLR_VAL(w)   (((w) & 0X0000FFFF) >> 0)
#define RTC_SET_DAY_CLR_SET(w)   w |= ( 0XFFFF << 0)
#define RTC_SET_DAY_CLR_CLR(w)   w &= ~( 0XFFFF << 0)

// REGISTER : SEC_CCVR

#define RTC_SEC_CCVR_ADDR      RTC_BASE_ADDR + 0X58
#define RTC_SEC_CCVR_RSTVAL    0X0
#define RTC_SEC_CCVR_ALL1      0XFF
#define RTC_SEC_CCVR_ALL0      0X0
#define RTC_SEC_CCVR_ALL5A     0X5A
#define RTC_SEC_CCVR_ALLA5     0XA5

// FIELD IN REGISTER : SEC_CCVR

#define RTC_SEC_CCVR_POS      0
#define RTC_SEC_CCVR_LEN      8
#define RTC_SEC_CCVR_MASK     0X000000FF
#define RTC_SEC_CCVR_VAL(w)   (((w) & 0X000000FF) >> 0)
#define RTC_SEC_CCVR_SET(w)   w |= ( 0XFF << 0)
#define RTC_SEC_CCVR_CLR(w)   w &= ~( 0XFF << 0)

// REGISTER : MIN_CCVR

#define RTC_MIN_CCVR_ADDR      RTC_BASE_ADDR + 0X5C
#define RTC_MIN_CCVR_RSTVAL    0X0
#define RTC_MIN_CCVR_ALL1      0X3F
#define RTC_MIN_CCVR_ALL0      0X0
#define RTC_MIN_CCVR_ALL5A     0X1A
#define RTC_MIN_CCVR_ALLA5     0X25

// FIELD IN REGISTER : MIN_CCVR

#define RTC_MIN_CCVR_POS      0
#define RTC_MIN_CCVR_LEN      6
#define RTC_MIN_CCVR_MASK     0X0000003F
#define RTC_MIN_CCVR_VAL(w)   (((w) & 0X0000003F) >> 0)
#define RTC_MIN_CCVR_SET(w)   w |= ( 0X3F << 0)
#define RTC_MIN_CCVR_CLR(w)   w &= ~( 0X3F << 0)

// REGISTER : HOUR_CCVR

#define RTC_HOUR_CCVR_ADDR      RTC_BASE_ADDR + 0X60
#define RTC_HOUR_CCVR_RSTVAL    0X0
#define RTC_HOUR_CCVR_ALL1      0X1F
#define RTC_HOUR_CCVR_ALL0      0X0
#define RTC_HOUR_CCVR_ALL5A     0X1A
#define RTC_HOUR_CCVR_ALLA5     0X5

// FIELD IN REGISTER : HOUR_CCVR

#define RTC_HOUR_CCVR_POS      0
#define RTC_HOUR_CCVR_LEN      5
#define RTC_HOUR_CCVR_MASK     0X0000001F
#define RTC_HOUR_CCVR_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_HOUR_CCVR_SET(w)   w |= ( 0X1F << 0)
#define RTC_HOUR_CCVR_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : DAY_CCVR

#define RTC_DAY_CCVR_ADDR      RTC_BASE_ADDR + 0X64
#define RTC_DAY_CCVR_RSTVAL    0X0
#define RTC_DAY_CCVR_ALL1      0XFFFF
#define RTC_DAY_CCVR_ALL0      0X0
#define RTC_DAY_CCVR_ALL5A     0X5A5A
#define RTC_DAY_CCVR_ALLA5     0XA5A5

// FIELD IN REGISTER : DAY_CCVR

#define RTC_DAY_CCVR_POS      0
#define RTC_DAY_CCVR_LEN      16
#define RTC_DAY_CCVR_MASK     0X0000FFFF
#define RTC_DAY_CCVR_VAL(w)   (((w) & 0X0000FFFF) >> 0)
#define RTC_DAY_CCVR_SET(w)   w |= ( 0XFFFF << 0)
#define RTC_DAY_CCVR_CLR(w)   w &= ~( 0XFFFF << 0)

// REGISTER : SET_SW

#define RTC_SET_SW_ADDR      RTC_BASE_ADDR + 0X68
#define RTC_SET_SW_RSTVAL    0X0
#define RTC_SET_SW_ALL1      0X0
#define RTC_SET_SW_ALL0      0X0
#define RTC_SET_SW_ALL5A     0X0
#define RTC_SET_SW_ALLA5     0X0

// FIELD IN REGISTER : SET_SW

#define RTC_SET_SW_SEC_POS      3
#define RTC_SET_SW_SEC_LEN      1
#define RTC_SET_SW_SEC_MASK     0X00000008
#define RTC_SET_SW_SEC_VAL(w)   (((w) & 0X00000008) >> 3)
#define RTC_SET_SW_SEC_SET(w)   w |= ( 0X1 << 3)
#define RTC_SET_SW_SEC_CLR(w)   w &= ~( 0X1 << 3)

#define RTC_SET_SW_MIN_POS      2
#define RTC_SET_SW_MIN_LEN      1
#define RTC_SET_SW_MIN_MASK     0X00000004
#define RTC_SET_SW_MIN_VAL(w)   (((w) & 0X00000004) >> 2)
#define RTC_SET_SW_MIN_SET(w)   w |= ( 0X1 << 2)
#define RTC_SET_SW_MIN_CLR(w)   w &= ~( 0X1 << 2)

#define RTC_SET_SW_HOUR_POS      1
#define RTC_SET_SW_HOUR_LEN      1
#define RTC_SET_SW_HOUR_MASK     0X00000002
#define RTC_SET_SW_HOUR_VAL(w)   (((w) & 0X00000002) >> 1)
#define RTC_SET_SW_HOUR_SET(w)   w |= ( 0X1 << 1)
#define RTC_SET_SW_HOUR_CLR(w)   w &= ~( 0X1 << 1)

#define RTC_SET_SW_DAY_POS      0
#define RTC_SET_SW_DAY_LEN      1
#define RTC_SET_SW_DAY_MASK     0X00000001
#define RTC_SET_SW_DAY_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_SET_SW_DAY_SET(w)   w |= ( 0X1 << 0)
#define RTC_SET_SW_DAY_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : SET_SW_SET

#define RTC_SET_SW_SET_ADDR      RTC_BASE_ADDR + 0X6C
#define RTC_SET_SW_SET_RSTVAL    0X0
#define RTC_SET_SW_SET_ALL1      0X0
#define RTC_SET_SW_SET_ALL0      0X0
#define RTC_SET_SW_SET_ALL5A     0X0
#define RTC_SET_SW_SET_ALLA5     0X0

// FIELD IN REGISTER : SET_SW_SET

#define RTC_SET_SW_SEC_SET_POS      3
#define RTC_SET_SW_SEC_SET_LEN      1
#define RTC_SET_SW_SEC_SET_MASK     0X00000008
#define RTC_SET_SW_SEC_SET_VAL(w)   (((w) & 0X00000008) >> 3)
#define RTC_SET_SW_SEC_SET_SET(w)   w |= ( 0X1 << 3)
#define RTC_SET_SW_SEC_SET_CLR(w)   w &= ~( 0X1 << 3)

#define RTC_SET_SW_MIN_SET_POS      2
#define RTC_SET_SW_MIN_SET_LEN      1
#define RTC_SET_SW_MIN_SET_MASK     0X00000004
#define RTC_SET_SW_MIN_SET_VAL(w)   (((w) & 0X00000004) >> 2)
#define RTC_SET_SW_MIN_SET_SET(w)   w |= ( 0X1 << 2)
#define RTC_SET_SW_MIN_SET_CLR(w)   w &= ~( 0X1 << 2)

#define RTC_SET_SW_HOUR_SET_POS      1
#define RTC_SET_SW_HOUR_SET_LEN      1
#define RTC_SET_SW_HOUR_SET_MASK     0X00000002
#define RTC_SET_SW_HOUR_SET_VAL(w)   (((w) & 0X00000002) >> 1)
#define RTC_SET_SW_HOUR_SET_SET(w)   w |= ( 0X1 << 1)
#define RTC_SET_SW_HOUR_SET_CLR(w)   w &= ~( 0X1 << 1)

#define RTC_SET_SW_DAY_SET_POS      0
#define RTC_SET_SW_DAY_SET_LEN      1
#define RTC_SET_SW_DAY_SET_MASK     0X00000001
#define RTC_SET_SW_DAY_SET_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_SET_SW_DAY_SET_SET(w)   w |= ( 0X1 << 0)
#define RTC_SET_SW_DAY_SET_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : SET_SW_CLR

#define RTC_SET_SW_CLR_ADDR      RTC_BASE_ADDR + 0X70
#define RTC_SET_SW_CLR_RSTVAL    0X0
#define RTC_SET_SW_CLR_ALL1      0X0
#define RTC_SET_SW_CLR_ALL0      0X0
#define RTC_SET_SW_CLR_ALL5A     0X0
#define RTC_SET_SW_CLR_ALLA5     0X0

// FIELD IN REGISTER : SET_SW_CLR

#define RTC_SET_SW_SEC_CLR_POS      3
#define RTC_SET_SW_SEC_CLR_LEN      1
#define RTC_SET_SW_SEC_CLR_MASK     0X00000008
#define RTC_SET_SW_SEC_CLR_VAL(w)   (((w) & 0X00000008) >> 3)
#define RTC_SET_SW_SEC_CLR_SET(w)   w |= ( 0X1 << 3)
#define RTC_SET_SW_SEC_CLR_CLR(w)   w &= ~( 0X1 << 3)

#define RTC_SET_SW_MIN_CLR_POS      2
#define RTC_SET_SW_MIN_CLR_LEN      1
#define RTC_SET_SW_MIN_CLR_MASK     0X00000004
#define RTC_SET_SW_MIN_CLR_VAL(w)   (((w) & 0X00000004) >> 2)
#define RTC_SET_SW_MIN_CLR_SET(w)   w |= ( 0X1 << 2)
#define RTC_SET_SW_MIN_CLR_CLR(w)   w &= ~( 0X1 << 2)

#define RTC_SET_SW_HOUR_CLR_POS      1
#define RTC_SET_SW_HOUR_CLR_LEN      1
#define RTC_SET_SW_HOUR_CLR_MASK     0X00000002
#define RTC_SET_SW_HOUR_CLR_VAL(w)   (((w) & 0X00000002) >> 1)
#define RTC_SET_SW_HOUR_CLR_SET(w)   w |= ( 0X1 << 1)
#define RTC_SET_SW_HOUR_CLR_CLR(w)   w &= ~( 0X1 << 1)

#define RTC_SET_SW_DAY_CLR_POS      0
#define RTC_SET_SW_DAY_CLR_LEN      1
#define RTC_SET_SW_DAY_CLR_MASK     0X00000001
#define RTC_SET_SW_DAY_CLR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_SET_SW_DAY_CLR_SET(w)   w |= ( 0X1 << 0)
#define RTC_SET_SW_DAY_CLR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : TIMESTAMP_LOCK

#define RTC_TIMESTAMP_LOCK_ADDR      RTC_BASE_ADDR + 0X74
#define RTC_TIMESTAMP_LOCK_RSTVAL    0X0
#define RTC_TIMESTAMP_LOCK_ALL1      0X0
#define RTC_TIMESTAMP_LOCK_ALL0      0X0
#define RTC_TIMESTAMP_LOCK_ALL5A     0X0
#define RTC_TIMESTAMP_LOCK_ALLA5     0X0

// FIELD IN REGISTER : TIMESTAMP_LOCK

#define RTC_TIMESTAMP_LOCK_POS      0
#define RTC_TIMESTAMP_LOCK_LEN      1
#define RTC_TIMESTAMP_LOCK_MASK     0X00000001
#define RTC_TIMESTAMP_LOCK_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_TIMESTAMP_LOCK_SET(w)   w |= ( 0X1 << 0)
#define RTC_TIMESTAMP_LOCK_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : TIMESTAMP_LOCK_SET

#define RTC_TIMESTAMP_LOCK_SET_ADDR      RTC_BASE_ADDR + 0X78
#define RTC_TIMESTAMP_LOCK_SET_RSTVAL    0X0
#define RTC_TIMESTAMP_LOCK_SET_ALL1      0X0
#define RTC_TIMESTAMP_LOCK_SET_ALL0      0X0
#define RTC_TIMESTAMP_LOCK_SET_ALL5A     0X0
#define RTC_TIMESTAMP_LOCK_SET_ALLA5     0X0

// FIELD IN REGISTER : TIMESTAMP_LOCK_SET

#define RTC_TIMESTAMP_LOCK_SET_POS      0
#define RTC_TIMESTAMP_LOCK_SET_LEN      1
#define RTC_TIMESTAMP_LOCK_SET_MASK     0X00000001
#define RTC_TIMESTAMP_LOCK_SET_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_TIMESTAMP_LOCK_SET_SET(w)   w |= ( 0X1 << 0)
#define RTC_TIMESTAMP_LOCK_SET_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : TIMESTAMP_LOCK_CLR

#define RTC_TIMESTAMP_LOCK_CLR_ADDR      RTC_BASE_ADDR + 0X7C
#define RTC_TIMESTAMP_LOCK_CLR_RSTVAL    0X0
#define RTC_TIMESTAMP_LOCK_CLR_ALL1      0X0
#define RTC_TIMESTAMP_LOCK_CLR_ALL0      0X0
#define RTC_TIMESTAMP_LOCK_CLR_ALL5A     0X0
#define RTC_TIMESTAMP_LOCK_CLR_ALLA5     0X0

// FIELD IN REGISTER : TIMESTAMP_LOCK_CLR

#define RTC_TIMESTAMP_LOCK_CLR_POS      0
#define RTC_TIMESTAMP_LOCK_CLR_LEN      1
#define RTC_TIMESTAMP_LOCK_CLR_MASK     0X00000001
#define RTC_TIMESTAMP_LOCK_CLR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_TIMESTAMP_LOCK_CLR_SET(w)   w |= ( 0X1 << 0)
#define RTC_TIMESTAMP_LOCK_CLR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : SEC_TIMESTAMP

#define RTC_SEC_TIMESTAMP_ADDR      RTC_BASE_ADDR + 0X80
#define RTC_SEC_TIMESTAMP_RSTVAL    0X0
#define RTC_SEC_TIMESTAMP_ALL1      0XFF
#define RTC_SEC_TIMESTAMP_ALL0      0X0
#define RTC_SEC_TIMESTAMP_ALL5A     0X5A
#define RTC_SEC_TIMESTAMP_ALLA5     0XA5

// FIELD IN REGISTER : SEC_TIMESTAMP

#define RTC_SEC_TIMESTAMP_POS      0
#define RTC_SEC_TIMESTAMP_LEN      8
#define RTC_SEC_TIMESTAMP_MASK     0X000000FF
#define RTC_SEC_TIMESTAMP_VAL(w)   (((w) & 0X000000FF) >> 0)
#define RTC_SEC_TIMESTAMP_SET(w)   w |= ( 0XFF << 0)
#define RTC_SEC_TIMESTAMP_CLR(w)   w &= ~( 0XFF << 0)

// REGISTER : MIN_TIMESTAMP

#define RTC_MIN_TIMESTAMP_ADDR      RTC_BASE_ADDR + 0X84
#define RTC_MIN_TIMESTAMP_RSTVAL    0X0
#define RTC_MIN_TIMESTAMP_ALL1      0X3F
#define RTC_MIN_TIMESTAMP_ALL0      0X0
#define RTC_MIN_TIMESTAMP_ALL5A     0X1A
#define RTC_MIN_TIMESTAMP_ALLA5     0X25

// FIELD IN REGISTER : MIN_TIMESTAMP

#define RTC_MIN_TIMESTAMP_POS      0
#define RTC_MIN_TIMESTAMP_LEN      6
#define RTC_MIN_TIMESTAMP_MASK     0X0000003F
#define RTC_MIN_TIMESTAMP_VAL(w)   (((w) & 0X0000003F) >> 0)
#define RTC_MIN_TIMESTAMP_SET(w)   w |= ( 0X3F << 0)
#define RTC_MIN_TIMESTAMP_CLR(w)   w &= ~( 0X3F << 0)

// REGISTER : HOUR_TIMESTAMP

#define RTC_HOUR_TIMESTAMP_ADDR      RTC_BASE_ADDR + 0X88
#define RTC_HOUR_TIMESTAMP_RSTVAL    0X0
#define RTC_HOUR_TIMESTAMP_ALL1      0X1F
#define RTC_HOUR_TIMESTAMP_ALL0      0X0
#define RTC_HOUR_TIMESTAMP_ALL5A     0X1A
#define RTC_HOUR_TIMESTAMP_ALLA5     0X5

// FIELD IN REGISTER : HOUR_TIMESTAMP

#define RTC_HOUR_TIMESTAMP_POS      0
#define RTC_HOUR_TIMESTAMP_LEN      5
#define RTC_HOUR_TIMESTAMP_MASK     0X0000001F
#define RTC_HOUR_TIMESTAMP_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_HOUR_TIMESTAMP_SET(w)   w |= ( 0X1F << 0)
#define RTC_HOUR_TIMESTAMP_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : DAY_TIMESTAMP

#define RTC_DAY_TIMESTAMP_ADDR      RTC_BASE_ADDR + 0X8C
#define RTC_DAY_TIMESTAMP_RSTVAL    0X0
#define RTC_DAY_TIMESTAMP_ALL1      0XFFFF
#define RTC_DAY_TIMESTAMP_ALL0      0X0
#define RTC_DAY_TIMESTAMP_ALL5A     0X5A5A
#define RTC_DAY_TIMESTAMP_ALLA5     0XA5A5

// FIELD IN REGISTER : DAY_TIMESTAMP

#define RTC_DAY_TIMESTAMP_POS      0
#define RTC_DAY_TIMESTAMP_LEN      16
#define RTC_DAY_TIMESTAMP_MASK     0X0000FFFF
#define RTC_DAY_TIMESTAMP_VAL(w)   (((w) & 0X0000FFFF) >> 0)
#define RTC_DAY_TIMESTAMP_SET(w)   w |= ( 0XFFFF << 0)
#define RTC_DAY_TIMESTAMP_CLR(w)   w &= ~( 0XFFFF << 0)

// REGISTER : SEC_MATCH

#define RTC_SEC_MATCH_ADDR      RTC_BASE_ADDR + 0X90
#define RTC_SEC_MATCH_RSTVAL    0XFF
#define RTC_SEC_MATCH_ALL1      0XFF
#define RTC_SEC_MATCH_ALL0      0X0
#define RTC_SEC_MATCH_ALL5A     0X5A
#define RTC_SEC_MATCH_ALLA5     0XA5

// FIELD IN REGISTER : SEC_MATCH

#define RTC_SEC_MATCH_POS      0
#define RTC_SEC_MATCH_LEN      8
#define RTC_SEC_MATCH_MASK     0X000000FF
#define RTC_SEC_MATCH_VAL(w)   (((w) & 0X000000FF) >> 0)
#define RTC_SEC_MATCH_SET(w)   w |= ( 0XFF << 0)
#define RTC_SEC_MATCH_CLR(w)   w &= ~( 0XFF << 0)

// REGISTER : SEC_MATCH_SET

#define RTC_SEC_MATCH_SET_ADDR      RTC_BASE_ADDR + 0X94
#define RTC_SEC_MATCH_SET_RSTVAL    0X0
#define RTC_SEC_MATCH_SET_ALL1      0X0
#define RTC_SEC_MATCH_SET_ALL0      0X0
#define RTC_SEC_MATCH_SET_ALL5A     0X0
#define RTC_SEC_MATCH_SET_ALLA5     0X0

// FIELD IN REGISTER : SEC_MATCH_SET

#define RTC_SEC_MATCH_SET_POS      0
#define RTC_SEC_MATCH_SET_LEN      8
#define RTC_SEC_MATCH_SET_MASK     0X000000FF
#define RTC_SEC_MATCH_SET_VAL(w)   (((w) & 0X000000FF) >> 0)
#define RTC_SEC_MATCH_SET_SET(w)   w |= ( 0XFF << 0)
#define RTC_SEC_MATCH_SET_CLR(w)   w &= ~( 0XFF << 0)

// REGISTER : SEC_MATCH_CLR

#define RTC_SEC_MATCH_CLR_ADDR      RTC_BASE_ADDR + 0X98
#define RTC_SEC_MATCH_CLR_RSTVAL    0X0
#define RTC_SEC_MATCH_CLR_ALL1      0X0
#define RTC_SEC_MATCH_CLR_ALL0      0X0
#define RTC_SEC_MATCH_CLR_ALL5A     0X0
#define RTC_SEC_MATCH_CLR_ALLA5     0X0

// FIELD IN REGISTER : SEC_MATCH_CLR

#define RTC_SEC_MATCH_CLR_POS      0
#define RTC_SEC_MATCH_CLR_LEN      8
#define RTC_SEC_MATCH_CLR_MASK     0X000000FF
#define RTC_SEC_MATCH_CLR_VAL(w)   (((w) & 0X000000FF) >> 0)
#define RTC_SEC_MATCH_CLR_SET(w)   w |= ( 0XFF << 0)
#define RTC_SEC_MATCH_CLR_CLR(w)   w &= ~( 0XFF << 0)

// REGISTER : MIN_MATCH

#define RTC_MIN_MATCH_ADDR      RTC_BASE_ADDR + 0X9C
#define RTC_MIN_MATCH_RSTVAL    0X3F
#define RTC_MIN_MATCH_ALL1      0X3F
#define RTC_MIN_MATCH_ALL0      0X0
#define RTC_MIN_MATCH_ALL5A     0X1A
#define RTC_MIN_MATCH_ALLA5     0X25

// FIELD IN REGISTER : MIN_MATCH

#define RTC_MIN_MATCH_POS      0
#define RTC_MIN_MATCH_LEN      6
#define RTC_MIN_MATCH_MASK     0X0000003F
#define RTC_MIN_MATCH_VAL(w)   (((w) & 0X0000003F) >> 0)
#define RTC_MIN_MATCH_SET(w)   w |= ( 0X3F << 0)
#define RTC_MIN_MATCH_CLR(w)   w &= ~( 0X3F << 0)

// REGISTER : MIN_MATCH_SET

#define RTC_MIN_MATCH_SET_ADDR      RTC_BASE_ADDR + 0XA0
#define RTC_MIN_MATCH_SET_RSTVAL    0X0
#define RTC_MIN_MATCH_SET_ALL1      0X0
#define RTC_MIN_MATCH_SET_ALL0      0X0
#define RTC_MIN_MATCH_SET_ALL5A     0X0
#define RTC_MIN_MATCH_SET_ALLA5     0X0

// FIELD IN REGISTER : MIN_MATCH_SET

#define RTC_MIN_MATCH_SET_POS      0
#define RTC_MIN_MATCH_SET_LEN      6
#define RTC_MIN_MATCH_SET_MASK     0X0000003F
#define RTC_MIN_MATCH_SET_VAL(w)   (((w) & 0X0000003F) >> 0)
#define RTC_MIN_MATCH_SET_SET(w)   w |= ( 0X3F << 0)
#define RTC_MIN_MATCH_SET_CLR(w)   w &= ~( 0X3F << 0)

// REGISTER : MIN_MATCH_CLR

#define RTC_MIN_MATCH_CLR_ADDR      RTC_BASE_ADDR + 0XA4
#define RTC_MIN_MATCH_CLR_RSTVAL    0X0
#define RTC_MIN_MATCH_CLR_ALL1      0X0
#define RTC_MIN_MATCH_CLR_ALL0      0X0
#define RTC_MIN_MATCH_CLR_ALL5A     0X0
#define RTC_MIN_MATCH_CLR_ALLA5     0X0

// FIELD IN REGISTER : MIN_MATCH_CLR

#define RTC_MIN_MATCH_CLR_POS      0
#define RTC_MIN_MATCH_CLR_LEN      6
#define RTC_MIN_MATCH_CLR_MASK     0X0000003F
#define RTC_MIN_MATCH_CLR_VAL(w)   (((w) & 0X0000003F) >> 0)
#define RTC_MIN_MATCH_CLR_SET(w)   w |= ( 0X3F << 0)
#define RTC_MIN_MATCH_CLR_CLR(w)   w &= ~( 0X3F << 0)

// REGISTER : HOUR_MATCH

#define RTC_HOUR_MATCH_ADDR      RTC_BASE_ADDR + 0XA8
#define RTC_HOUR_MATCH_RSTVAL    0X1F
#define RTC_HOUR_MATCH_ALL1      0X1F
#define RTC_HOUR_MATCH_ALL0      0X0
#define RTC_HOUR_MATCH_ALL5A     0X1A
#define RTC_HOUR_MATCH_ALLA5     0X5

// FIELD IN REGISTER : HOUR_MATCH

#define RTC_HOUR_MATCH_POS      0
#define RTC_HOUR_MATCH_LEN      5
#define RTC_HOUR_MATCH_MASK     0X0000001F
#define RTC_HOUR_MATCH_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_HOUR_MATCH_SET(w)   w |= ( 0X1F << 0)
#define RTC_HOUR_MATCH_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : HOUR_MATCH_SET

#define RTC_HOUR_MATCH_SET_ADDR      RTC_BASE_ADDR + 0XAC
#define RTC_HOUR_MATCH_SET_RSTVAL    0X0
#define RTC_HOUR_MATCH_SET_ALL1      0X0
#define RTC_HOUR_MATCH_SET_ALL0      0X0
#define RTC_HOUR_MATCH_SET_ALL5A     0X0
#define RTC_HOUR_MATCH_SET_ALLA5     0X0

// FIELD IN REGISTER : HOUR_MATCH_SET

#define RTC_HOUR_MATCH_SET_POS      0
#define RTC_HOUR_MATCH_SET_LEN      5
#define RTC_HOUR_MATCH_SET_MASK     0X0000001F
#define RTC_HOUR_MATCH_SET_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_HOUR_MATCH_SET_SET(w)   w |= ( 0X1F << 0)
#define RTC_HOUR_MATCH_SET_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : HOUR_MATCH_CLR

#define RTC_HOUR_MATCH_CLR_ADDR      RTC_BASE_ADDR + 0XB0
#define RTC_HOUR_MATCH_CLR_RSTVAL    0X0
#define RTC_HOUR_MATCH_CLR_ALL1      0X0
#define RTC_HOUR_MATCH_CLR_ALL0      0X0
#define RTC_HOUR_MATCH_CLR_ALL5A     0X0
#define RTC_HOUR_MATCH_CLR_ALLA5     0X0

// FIELD IN REGISTER : HOUR_MATCH_CLR

#define RTC_HOUR_MATCH_CLR_POS      0
#define RTC_HOUR_MATCH_CLR_LEN      5
#define RTC_HOUR_MATCH_CLR_MASK     0X0000001F
#define RTC_HOUR_MATCH_CLR_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_HOUR_MATCH_CLR_SET(w)   w |= ( 0X1F << 0)
#define RTC_HOUR_MATCH_CLR_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : DAY_MATCH

#define RTC_DAY_MATCH_ADDR      RTC_BASE_ADDR + 0XB4
#define RTC_DAY_MATCH_RSTVAL    0XFFFF
#define RTC_DAY_MATCH_ALL1      0XFFFF
#define RTC_DAY_MATCH_ALL0      0X0
#define RTC_DAY_MATCH_ALL5A     0X5A5A
#define RTC_DAY_MATCH_ALLA5     0XA5A5

// FIELD IN REGISTER : DAY_MATCH

#define RTC_DAY_MATCH_POS      0
#define RTC_DAY_MATCH_LEN      16
#define RTC_DAY_MATCH_MASK     0X0000FFFF
#define RTC_DAY_MATCH_VAL(w)   (((w) & 0X0000FFFF) >> 0)
#define RTC_DAY_MATCH_SET(w)   w |= ( 0XFFFF << 0)
#define RTC_DAY_MATCH_CLR(w)   w &= ~( 0XFFFF << 0)

// REGISTER : DAY_MATCH_SET

#define RTC_DAY_MATCH_SET_ADDR      RTC_BASE_ADDR + 0XB8
#define RTC_DAY_MATCH_SET_RSTVAL    0X0
#define RTC_DAY_MATCH_SET_ALL1      0X0
#define RTC_DAY_MATCH_SET_ALL0      0X0
#define RTC_DAY_MATCH_SET_ALL5A     0X0
#define RTC_DAY_MATCH_SET_ALLA5     0X0

// FIELD IN REGISTER : DAY_MATCH_SET

#define RTC_DAY_MATCH_SET_POS      0
#define RTC_DAY_MATCH_SET_LEN      16
#define RTC_DAY_MATCH_SET_MASK     0X0000FFFF
#define RTC_DAY_MATCH_SET_VAL(w)   (((w) & 0X0000FFFF) >> 0)
#define RTC_DAY_MATCH_SET_SET(w)   w |= ( 0XFFFF << 0)
#define RTC_DAY_MATCH_SET_CLR(w)   w &= ~( 0XFFFF << 0)

// REGISTER : DAY_MATCH_CLR

#define RTC_DAY_MATCH_CLR_ADDR      RTC_BASE_ADDR + 0XBC
#define RTC_DAY_MATCH_CLR_RSTVAL    0X0
#define RTC_DAY_MATCH_CLR_ALL1      0X0
#define RTC_DAY_MATCH_CLR_ALL0      0X0
#define RTC_DAY_MATCH_CLR_ALL5A     0X0
#define RTC_DAY_MATCH_CLR_ALLA5     0X0

// FIELD IN REGISTER : DAY_MATCH_CLR

#define RTC_DAY_MATCH_CLR_POS      0
#define RTC_DAY_MATCH_CLR_LEN      16
#define RTC_DAY_MATCH_CLR_MASK     0X0000FFFF
#define RTC_DAY_MATCH_CLR_VAL(w)   (((w) & 0X0000FFFF) >> 0)
#define RTC_DAY_MATCH_CLR_SET(w)   w |= ( 0XFFFF << 0)
#define RTC_DAY_MATCH_CLR_CLR(w)   w &= ~( 0XFFFF << 0)

// REGISTER : MATCH_START

#define RTC_MATCH_START_ADDR      RTC_BASE_ADDR + 0XC0
#define RTC_MATCH_START_RSTVAL    0X0
#define RTC_MATCH_START_ALL1      0X0
#define RTC_MATCH_START_ALL0      0X0
#define RTC_MATCH_START_ALL5A     0X0
#define RTC_MATCH_START_ALLA5     0X0

// FIELD IN REGISTER : MATCH_START

#define RTC_MATCH_START_POS      0
#define RTC_MATCH_START_LEN      1
#define RTC_MATCH_START_MASK     0X00000001
#define RTC_MATCH_START_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_MATCH_START_SET(w)   w |= ( 0X1 << 0)
#define RTC_MATCH_START_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : MATCH_START_SET

#define RTC_MATCH_START_SET_ADDR      RTC_BASE_ADDR + 0XC4
#define RTC_MATCH_START_SET_RSTVAL    0X0
#define RTC_MATCH_START_SET_ALL1      0X0
#define RTC_MATCH_START_SET_ALL0      0X0
#define RTC_MATCH_START_SET_ALL5A     0X0
#define RTC_MATCH_START_SET_ALLA5     0X0

// FIELD IN REGISTER : MATCH_START_SET

#define RTC_MATCH_START_SET_POS      0
#define RTC_MATCH_START_SET_LEN      1
#define RTC_MATCH_START_SET_MASK     0X00000001
#define RTC_MATCH_START_SET_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_MATCH_START_SET_SET(w)   w |= ( 0X1 << 0)
#define RTC_MATCH_START_SET_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : MATCH_START_CLR

#define RTC_MATCH_START_CLR_ADDR      RTC_BASE_ADDR + 0XC8
#define RTC_MATCH_START_CLR_RSTVAL    0X0
#define RTC_MATCH_START_CLR_ALL1      0X0
#define RTC_MATCH_START_CLR_ALL0      0X0
#define RTC_MATCH_START_CLR_ALL5A     0X0
#define RTC_MATCH_START_CLR_ALLA5     0X0

// FIELD IN REGISTER : MATCH_START_CLR

#define RTC_MATCH_START_CLR_POS      0
#define RTC_MATCH_START_CLR_LEN      1
#define RTC_MATCH_START_CLR_MASK     0X00000001
#define RTC_MATCH_START_CLR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_MATCH_START_CLR_SET(w)   w |= ( 0X1 << 0)
#define RTC_MATCH_START_CLR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_RSTAT

#define RTC_ALARM_RSTAT_ADDR      RTC_BASE_ADDR + 0XCC
#define RTC_ALARM_RSTAT_RSTVAL    0X0
#define RTC_ALARM_RSTAT_ALL1      0X1
#define RTC_ALARM_RSTAT_ALL0      0X0
#define RTC_ALARM_RSTAT_ALL5A     0X0
#define RTC_ALARM_RSTAT_ALLA5     0X1

// FIELD IN REGISTER : ALARM_RSTAT

#define RTC_ALARM_RSTAT_POS      0
#define RTC_ALARM_RSTAT_LEN      1
#define RTC_ALARM_RSTAT_MASK     0X00000001
#define RTC_ALARM_RSTAT_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_RSTAT_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_RSTAT_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_INTR

#define RTC_ALARM_INTR_ADDR      RTC_BASE_ADDR + 0XD0
#define RTC_ALARM_INTR_RSTVAL    0X0
#define RTC_ALARM_INTR_ALL1      0X1
#define RTC_ALARM_INTR_ALL0      0X0
#define RTC_ALARM_INTR_ALL5A     0X0
#define RTC_ALARM_INTR_ALLA5     0X1

// FIELD IN REGISTER : ALARM_INTR

#define RTC_ALARM_INTR_POS      0
#define RTC_ALARM_INTR_LEN      1
#define RTC_ALARM_INTR_MASK     0X00000001
#define RTC_ALARM_INTR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_INTR_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_INTR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_INTR_EN

#define RTC_ALARM_INTR_EN_ADDR      (RTC_BASE_ADDR + 0XD4)
#define RTC_ALARM_INTR_EN_RSTVAL    0X1
#define RTC_ALARM_INTR_EN_ALL1      0X1
#define RTC_ALARM_INTR_EN_ALL0      0X0
#define RTC_ALARM_INTR_EN_ALL5A     0X0
#define RTC_ALARM_INTR_EN_ALLA5     0X1

// FIELD IN REGISTER : ALARM_INTR_EN

#define RTC_ALARM_INTR_EN_POS      0
#define RTC_ALARM_INTR_EN_LEN      1
#define RTC_ALARM_INTR_EN_MASK     0X00000001
#define RTC_ALARM_INTR_EN_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_INTR_EN_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_INTR_EN_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_INTR_EN_SET

#define RTC_ALARM_INTR_EN_SET_ADDR      RTC_BASE_ADDR + 0XD8
#define RTC_ALARM_INTR_EN_SET_RSTVAL    0X0
#define RTC_ALARM_INTR_EN_SET_ALL1      0X0
#define RTC_ALARM_INTR_EN_SET_ALL0      0X0
#define RTC_ALARM_INTR_EN_SET_ALL5A     0X0
#define RTC_ALARM_INTR_EN_SET_ALLA5     0X0

// FIELD IN REGISTER : ALARM_INTR_EN_SET

#define RTC_ALARM_INTR_EN_SET_POS      0
#define RTC_ALARM_INTR_EN_SET_LEN      1
#define RTC_ALARM_INTR_EN_SET_MASK     0X00000001
#define RTC_ALARM_INTR_EN_SET_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_INTR_EN_SET_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_INTR_EN_SET_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_INTR_EN_CLR

#define RTC_ALARM_INTR_EN_CLR_ADDR      RTC_BASE_ADDR + 0XDC
#define RTC_ALARM_INTR_EN_CLR_RSTVAL    0X0
#define RTC_ALARM_INTR_EN_CLR_ALL1      0X0
#define RTC_ALARM_INTR_EN_CLR_ALL0      0X0
#define RTC_ALARM_INTR_EN_CLR_ALL5A     0X0
#define RTC_ALARM_INTR_EN_CLR_ALLA5     0X0

// FIELD IN REGISTER : ALARM_INTR_EN_CLR

#define RTC_ALARM_INTR_EN_CLR_POS      0
#define RTC_ALARM_INTR_EN_CLR_LEN      1
#define RTC_ALARM_INTR_EN_CLR_MASK     0X00000001
#define RTC_ALARM_INTR_EN_CLR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_INTR_EN_CLR_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_INTR_EN_CLR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_CLR_INTR

#define RTC_ALARM_CLR_INTR_ADDR      RTC_BASE_ADDR + 0XE0
#define RTC_ALARM_CLR_INTR_RSTVAL    0X0
#define RTC_ALARM_CLR_INTR_ALL1      0X0
#define RTC_ALARM_CLR_INTR_ALL0      0X0
#define RTC_ALARM_CLR_INTR_ALL5A     0X0
#define RTC_ALARM_CLR_INTR_ALLA5     0X0

// FIELD IN REGISTER : ALARM_CLR_INTR

#define RTC_ALARM_CLR_INTR_POS      0
#define RTC_ALARM_CLR_INTR_LEN      1
#define RTC_ALARM_CLR_INTR_MASK     0X00000001
#define RTC_ALARM_CLR_INTR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_CLR_INTR_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_CLR_INTR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_CLR_INTR_SET

#define RTC_ALARM_CLR_INTR_SET_ADDR      RTC_BASE_ADDR + 0XE4
#define RTC_ALARM_CLR_INTR_SET_RSTVAL    0X0
#define RTC_ALARM_CLR_INTR_SET_ALL1      0X0
#define RTC_ALARM_CLR_INTR_SET_ALL0      0X0
#define RTC_ALARM_CLR_INTR_SET_ALL5A     0X0
#define RTC_ALARM_CLR_INTR_SET_ALLA5     0X0

// FIELD IN REGISTER : ALARM_CLR_INTR_SET

#define RTC_ALARM_CLR_INTR_SET_POS      0
#define RTC_ALARM_CLR_INTR_SET_LEN      1
#define RTC_ALARM_CLR_INTR_SET_MASK     0X00000001
#define RTC_ALARM_CLR_INTR_SET_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_CLR_INTR_SET_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_CLR_INTR_SET_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_CLR_INTR_CLR

#define RTC_ALARM_CLR_INTR_CLR_ADDR      RTC_BASE_ADDR + 0XE8
#define RTC_ALARM_CLR_INTR_CLR_RSTVAL    0X0
#define RTC_ALARM_CLR_INTR_CLR_ALL1      0X0
#define RTC_ALARM_CLR_INTR_CLR_ALL0      0X0
#define RTC_ALARM_CLR_INTR_CLR_ALL5A     0X0
#define RTC_ALARM_CLR_INTR_CLR_ALLA5     0X0

// FIELD IN REGISTER : ALARM_CLR_INTR_CLR

#define RTC_ALARM_CLR_INTR_CLR_POS      0
#define RTC_ALARM_CLR_INTR_CLR_LEN      1
#define RTC_ALARM_CLR_INTR_CLR_MASK     0X00000001
#define RTC_ALARM_CLR_INTR_CLR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_CLR_INTR_CLR_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_CLR_INTR_CLR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_INTR_MASK

#define RTC_ALARM_INTR_MASK_ADDR      RTC_BASE_ADDR + 0XEC
#define RTC_ALARM_INTR_MASK_RSTVAL    0X0
#define RTC_ALARM_INTR_MASK_ALL1      0X1
#define RTC_ALARM_INTR_MASK_ALL0      0X0
#define RTC_ALARM_INTR_MASK_ALL5A     0X0
#define RTC_ALARM_INTR_MASK_ALLA5     0X1

// FIELD IN REGISTER : ALARM_INTR_MASK

#define RTC_ALARM_INTR_MASK_POS      0
#define RTC_ALARM_INTR_MASK_LEN      1
#define RTC_ALARM_INTR_MASK_MASK     0X00000001
#define RTC_ALARM_INTR_MASK_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_INTR_MASK_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_INTR_MASK_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_INTR_MASK_SET

#define RTC_ALARM_INTR_MASK_SET_ADDR      RTC_BASE_ADDR + 0XF0
#define RTC_ALARM_INTR_MASK_SET_RSTVAL    0X0
#define RTC_ALARM_INTR_MASK_SET_ALL1      0X0
#define RTC_ALARM_INTR_MASK_SET_ALL0      0X0
#define RTC_ALARM_INTR_MASK_SET_ALL5A     0X0
#define RTC_ALARM_INTR_MASK_SET_ALLA5     0X0

// FIELD IN REGISTER : ALARM_INTR_MASK_SET

#define RTC_ALARM_INTR_MASK_SET_POS      0
#define RTC_ALARM_INTR_MASK_SET_LEN      1
#define RTC_ALARM_INTR_MASK_SET_MASK     0X00000001
#define RTC_ALARM_INTR_MASK_SET_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_INTR_MASK_SET_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_INTR_MASK_SET_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : ALARM_INTR_MASK_CLR

#define RTC_ALARM_INTR_MASK_CLR_ADDR      RTC_BASE_ADDR + 0XF4
#define RTC_ALARM_INTR_MASK_CLR_RSTVAL    0X0
#define RTC_ALARM_INTR_MASK_CLR_ALL1      0X0
#define RTC_ALARM_INTR_MASK_CLR_ALL0      0X0
#define RTC_ALARM_INTR_MASK_CLR_ALL5A     0X0
#define RTC_ALARM_INTR_MASK_CLR_ALLA5     0X0

// FIELD IN REGISTER : ALARM_INTR_MASK_CLR

#define RTC_ALARM_INTR_MASK_CLR_POS      0
#define RTC_ALARM_INTR_MASK_CLR_LEN      1
#define RTC_ALARM_INTR_MASK_CLR_MASK     0X00000001
#define RTC_ALARM_INTR_MASK_CLR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_ALARM_INTR_MASK_CLR_SET(w)   w |= ( 0X1 << 0)
#define RTC_ALARM_INTR_MASK_CLR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : CFG_VALID_RSTAT

#define RTC_CFG_VALID_RSTAT_ADDR      RTC_BASE_ADDR + 0XF8
#define RTC_CFG_VALID_RSTAT_RSTVAL    0X0
#define RTC_CFG_VALID_RSTAT_ALL1      0X3F
#define RTC_CFG_VALID_RSTAT_ALL0      0X0
#define RTC_CFG_VALID_RSTAT_ALL5A     0X1A
#define RTC_CFG_VALID_RSTAT_ALLA5     0X25

// FIELD IN REGISTER : CFG_VALID_RSTAT

#define RTC_CFG_VALID_RSTAT_POS      0
#define RTC_CFG_VALID_RSTAT_LEN      6
#define RTC_CFG_VALID_RSTAT_MASK     0X0000003F
#define RTC_CFG_VALID_RSTAT_VAL(w)   (((w) & 0X0000003F) >> 0)
#define RTC_CFG_VALID_RSTAT_SET(w)   w |= ( 0X3F << 0)
#define RTC_CFG_VALID_RSTAT_CLR(w)   w &= ~( 0X3F << 0)

// REGISTER : CFG_VALID_INTR

#define RTC_CFG_VALID_INTR_ADDR      RTC_BASE_ADDR + 0XFC
#define RTC_CFG_VALID_INTR_RSTVAL    0X0
#define RTC_CFG_VALID_INTR_ALL1      0X1F
#define RTC_CFG_VALID_INTR_ALL0      0X0
#define RTC_CFG_VALID_INTR_ALL5A     0X1A
#define RTC_CFG_VALID_INTR_ALLA5     0X25

// FIELD IN REGISTER : CFG_VALID_INTR

#define RTC_CFG_VALID_INTR_POS      0
#define RTC_CFG_VALID_INTR_LEN      5
#define RTC_CFG_VALID_INTR_MASK     0X0000001F
#define RTC_CFG_VALID_INTR_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_CFG_VALID_INTR_SET(w)   w |= ( 0X1F << 0)
#define RTC_CFG_VALID_INTR_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : CFG_VALID_INTR_EN

#define RTC_CFG_VALID_INTR_EN_ADDR      RTC_BASE_ADDR + 0X100
#define RTC_CFG_VALID_INTR_EN_RSTVAL    0X1F
#define RTC_CFG_VALID_INTR_EN_ALL1      0X1F
#define RTC_CFG_VALID_INTR_EN_ALL0      0X0
#define RTC_CFG_VALID_INTR_EN_ALL5A     0X1A
#define RTC_CFG_VALID_INTR_EN_ALLA5     0X25

// FIELD IN REGISTER : CFG_VALID_INTR_EN

#define RTC_CFG_VALID_INTR_EN_POS      0
#define RTC_CFG_VALID_INTR_EN_LEN      5
#define RTC_CFG_VALID_INTR_EN_MASK     0X0000001F
#define RTC_CFG_VALID_INTR_EN_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_CFG_VALID_INTR_EN_SET(w)   w |= ( 0X1F << 0)
#define RTC_CFG_VALID_INTR_EN_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : CFG_VALID_INTR_EN_SET

#define RTC_CFG_VALID_INTR_EN_SET_ADDR      RTC_BASE_ADDR + 0X104
#define RTC_CFG_VALID_INTR_EN_SET_RSTVAL    0X0
#define RTC_CFG_VALID_INTR_EN_SET_ALL1      0X0
#define RTC_CFG_VALID_INTR_EN_SET_ALL0      0X0
#define RTC_CFG_VALID_INTR_EN_SET_ALL5A     0X0
#define RTC_CFG_VALID_INTR_EN_SET_ALLA5     0X0

// FIELD IN REGISTER : CFG_VALID_INTR_EN_SET

#define RTC_CFG_VALID_INTR_EN_SET_POS      0
#define RTC_CFG_VALID_INTR_EN_SET_LEN      5
#define RTC_CFG_VALID_INTR_EN_SET_MASK     0X0000001F
#define RTC_CFG_VALID_INTR_EN_SET_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_CFG_VALID_INTR_EN_SET_SET(w)   w |= ( 0X1F << 0)
#define RTC_CFG_VALID_INTR_EN_SET_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : CFG_VALID_INTR_EN_CLR

#define RTC_CFG_VALID_INTR_EN_CLR_ADDR      RTC_BASE_ADDR + 0X108
#define RTC_CFG_VALID_INTR_EN_CLR_RSTVAL    0X0
#define RTC_CFG_VALID_INTR_EN_CLR_ALL1      0X0
#define RTC_CFG_VALID_INTR_EN_CLR_ALL0      0X0
#define RTC_CFG_VALID_INTR_EN_CLR_ALL5A     0X0
#define RTC_CFG_VALID_INTR_EN_CLR_ALLA5     0X0

// FIELD IN REGISTER : CFG_VALID_INTR_EN_CLR

#define RTC_CFG_VALID_INTR_EN_CLR_POS      0
#define RTC_CFG_VALID_INTR_EN_CLR_LEN      5
#define RTC_CFG_VALID_INTR_EN_CLR_MASK     0X0000001F
#define RTC_CFG_VALID_INTR_EN_CLR_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_CFG_VALID_INTR_EN_CLR_SET(w)   w |= ( 0X1F << 0)
#define RTC_CFG_VALID_INTR_EN_CLR_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : CFG_VALID_CLR_INTR

#define RTC_CFG_VALID_CLR_INTR_ADDR      RTC_BASE_ADDR + 0X10C
#define RTC_CFG_VALID_CLR_INTR_RSTVAL    0X0
#define RTC_CFG_VALID_CLR_INTR_ALL1      0X0
#define RTC_CFG_VALID_CLR_INTR_ALL0      0X0
#define RTC_CFG_VALID_CLR_INTR_ALL5A     0X0
#define RTC_CFG_VALID_CLR_INTR_ALLA5     0X0

// FIELD IN REGISTER : CFG_VALID_CLR_INTR

#define RTC_CFG_VALID_CLR_INTR_POS      0
#define RTC_CFG_VALID_CLR_INTR_LEN      5
#define RTC_CFG_VALID_CLR_INTR_MASK     0X0000001F
#define RTC_CFG_VALID_CLR_INTR_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_CFG_VALID_CLR_INTR_SET(w)   w |= ( 0X1F << 0)
#define RTC_CFG_VALID_CLR_INTR_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : CFG_VALID_CLR_INTR_SET

#define RTC_CFG_VALID_CLR_INTR_SET_ADDR      RTC_BASE_ADDR + 0X110
#define RTC_CFG_VALID_CLR_INTR_SET_RSTVAL    0X0
#define RTC_CFG_VALID_CLR_INTR_SET_ALL1      0X0
#define RTC_CFG_VALID_CLR_INTR_SET_ALL0      0X0
#define RTC_CFG_VALID_CLR_INTR_SET_ALL5A     0X0
#define RTC_CFG_VALID_CLR_INTR_SET_ALLA5     0X0

// FIELD IN REGISTER : CFG_VALID_CLR_INTR_SET

#define RTC_CFG_VALID_CLR_INTR_SET_POS      0
#define RTC_CFG_VALID_CLR_INTR_SET_LEN      5
#define RTC_CFG_VALID_CLR_INTR_SET_MASK     0X0000001F
#define RTC_CFG_VALID_CLR_INTR_SET_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_CFG_VALID_CLR_INTR_SET_SET(w)   w |= ( 0X1F << 0)
#define RTC_CFG_VALID_CLR_INTR_SET_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : CFG_VALID_CLR_INTR_CLR

#define RTC_CFG_VALID_CLR_INTR_CLR_ADDR      RTC_BASE_ADDR + 0X114
#define RTC_CFG_VALID_CLR_INTR_CLR_RSTVAL    0X0
#define RTC_CFG_VALID_CLR_INTR_CLR_ALL1      0X0
#define RTC_CFG_VALID_CLR_INTR_CLR_ALL0      0X0
#define RTC_CFG_VALID_CLR_INTR_CLR_ALL5A     0X0
#define RTC_CFG_VALID_CLR_INTR_CLR_ALLA5     0X0

// FIELD IN REGISTER : CFG_VALID_CLR_INTR_CLR

#define RTC_CFG_VALID_CLR_INTR_CLR_POS      0
#define RTC_CFG_VALID_CLR_INTR_CLR_LEN      5
#define RTC_CFG_VALID_CLR_INTR_CLR_MASK     0X0000001F
#define RTC_CFG_VALID_CLR_INTR_CLR_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_CFG_VALID_CLR_INTR_CLR_SET(w)   w |= ( 0X1F << 0)
#define RTC_CFG_VALID_CLR_INTR_CLR_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : CFG_VALID_INTR_MASK

#define RTC_CFG_VALID_INTR_MASK_ADDR      RTC_BASE_ADDR + 0X118
#define RTC_CFG_VALID_INTR_MASK_RSTVAL    0X0
#define RTC_CFG_VALID_INTR_MASK_ALL1      0X1F
#define RTC_CFG_VALID_INTR_MASK_ALL0      0X0
#define RTC_CFG_VALID_INTR_MASK_ALL5A     0X1A
#define RTC_CFG_VALID_INTR_MASK_ALLA5     0X25

// FIELD IN REGISTER : CFG_VALID_INTR_MASK

#define RTC_CFG_VALID_INTR_MASK_POS      0
#define RTC_CFG_VALID_INTR_MASK_LEN      5
#define RTC_CFG_VALID_INTR_MASK_MASK     0X0000001F
#define RTC_CFG_VALID_INTR_MASK_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_CFG_VALID_INTR_MASK_SET(w)   w |= ( 0X1F << 0)
#define RTC_CFG_VALID_INTR_MASK_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : CFG_VALID_INTR_MASK_SET

#define RTC_CFG_VALID_INTR_MASK_SET_ADDR      RTC_BASE_ADDR + 0X11C
#define RTC_CFG_VALID_INTR_MASK_SET_RSTVAL    0X0
#define RTC_CFG_VALID_INTR_MASK_SET_ALL1      0X0
#define RTC_CFG_VALID_INTR_MASK_SET_ALL0      0X0
#define RTC_CFG_VALID_INTR_MASK_SET_ALL5A     0X0
#define RTC_CFG_VALID_INTR_MASK_SET_ALLA5     0X0

// FIELD IN REGISTER : CFG_VALID_INTR_MASK_SET

#define RTC_CFG_VALID_INTR_MASK_SET_POS      0
#define RTC_CFG_VALID_INTR_MASK_SET_LEN      5
#define RTC_CFG_VALID_INTR_MASK_SET_MASK     0X0000001F
#define RTC_CFG_VALID_INTR_MASK_SET_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_CFG_VALID_INTR_MASK_SET_SET(w)   w |= ( 0X1F << 0)
#define RTC_CFG_VALID_INTR_MASK_SET_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : CFG_VALID_INTR_MASK_CLR

#define RTC_CFG_VALID_INTR_MASK_CLR_ADDR      RTC_BASE_ADDR + 0X120
#define RTC_CFG_VALID_INTR_MASK_CLR_RSTVAL    0X0
#define RTC_CFG_VALID_INTR_MASK_CLR_ALL1      0X0
#define RTC_CFG_VALID_INTR_MASK_CLR_ALL0      0X0
#define RTC_CFG_VALID_INTR_MASK_CLR_ALL5A     0X0
#define RTC_CFG_VALID_INTR_MASK_CLR_ALLA5     0X0

// FIELD IN REGISTER : CFG_VALID_INTR_MASK_CLR

#define RTC_CFG_VALID_INTR_MASK_CLR_POS      0
#define RTC_CFG_VALID_INTR_MASK_CLR_LEN      5
#define RTC_CFG_VALID_INTR_MASK_CLR_MASK     0X0000001F
#define RTC_CFG_VALID_INTR_MASK_CLR_VAL(w)   (((w) & 0X0000001F) >> 0)
#define RTC_CFG_VALID_INTR_MASK_CLR_SET(w)   w |= ( 0X1F << 0)
#define RTC_CFG_VALID_INTR_MASK_CLR_CLR(w)   w &= ~( 0X1F << 0)

// REGISTER : X32K_XIN

#define RTC_X32K_XIN_ADDR      RTC_BASE_ADDR + 0X124
#define RTC_X32K_XIN_RSTVAL    0X1F
#define RTC_X32K_XIN_ALL1      0X1F
#define RTC_X32K_XIN_ALL0      0X0
#define RTC_X32K_XIN_ALL5A     0X1A
#define RTC_X32K_XIN_ALLA5     0X5

// FIELD IN REGISTER : X32K_XIN

#define RTC_X32K_XIN_XE_POS      4
#define RTC_X32K_XIN_XE_LEN      1
#define RTC_X32K_XIN_XE_MASK     0X00000010
#define RTC_X32K_XIN_XE_VAL(w)   (((w) & 0X00000010) >> 4)
#define RTC_X32K_XIN_XE_SET(w)   w |= ( 0X1 << 4)
#define RTC_X32K_XIN_XE_CLR(w)   w &= ~( 0X1 << 4)

#define RTC_X32K_XIN_RF_POS      3
#define RTC_X32K_XIN_RF_LEN      1
#define RTC_X32K_XIN_RF_MASK     0X00000008
#define RTC_X32K_XIN_RF_VAL(w)   (((w) & 0X00000008) >> 3)
#define RTC_X32K_XIN_RF_SET(w)   w |= ( 0X1 << 3)
#define RTC_X32K_XIN_RF_CLR(w)   w &= ~( 0X1 << 3)

#define RTC_X32K_XIN_DS2_POS      2
#define RTC_X32K_XIN_DS2_LEN      1
#define RTC_X32K_XIN_DS2_MASK     0X00000004
#define RTC_X32K_XIN_DS2_VAL(w)   (((w) & 0X00000004) >> 2)
#define RTC_X32K_XIN_DS2_SET(w)   w |= ( 0X1 << 2)
#define RTC_X32K_XIN_DS2_CLR(w)   w &= ~( 0X1 << 2)

#define RTC_X32K_XIN_DS1_POS      1
#define RTC_X32K_XIN_DS1_LEN      1
#define RTC_X32K_XIN_DS1_MASK     0X00000002
#define RTC_X32K_XIN_DS1_VAL(w)   (((w) & 0X00000002) >> 1)
#define RTC_X32K_XIN_DS1_SET(w)   w |= ( 0X1 << 1)
#define RTC_X32K_XIN_DS1_CLR(w)   w &= ~( 0X1 << 1)

#define RTC_X32K_XIN_DS0_POS      0
#define RTC_X32K_XIN_DS0_LEN      1
#define RTC_X32K_XIN_DS0_MASK     0X00000001
#define RTC_X32K_XIN_DS0_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_X32K_XIN_DS0_SET(w)   w |= ( 0X1 << 0)
#define RTC_X32K_XIN_DS0_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : X32K_XIN_SET

#define RTC_X32K_XIN_SET_ADDR      RTC_BASE_ADDR + 0X128
#define RTC_X32K_XIN_SET_RSTVAL    0X0
#define RTC_X32K_XIN_SET_ALL1      0X0
#define RTC_X32K_XIN_SET_ALL0      0X0
#define RTC_X32K_XIN_SET_ALL5A     0X0
#define RTC_X32K_XIN_SET_ALLA5     0X0

// FIELD IN REGISTER : X32K_XIN_SET

#define RTC_X32K_XIN_XE_SET_POS      4
#define RTC_X32K_XIN_XE_SET_LEN      1
#define RTC_X32K_XIN_XE_SET_MASK     0X00000010
#define RTC_X32K_XIN_XE_SET_VAL(w)   (((w) & 0X00000010) >> 4)
#define RTC_X32K_XIN_XE_SET_SET(w)   w |= ( 0X1 << 4)
#define RTC_X32K_XIN_XE_SET_CLR(w)   w &= ~( 0X1 << 4)

#define RTC_X32K_XIN_RF_SET_POS      3
#define RTC_X32K_XIN_RF_SET_LEN      1
#define RTC_X32K_XIN_RF_SET_MASK     0X00000008
#define RTC_X32K_XIN_RF_SET_VAL(w)   (((w) & 0X00000008) >> 3)
#define RTC_X32K_XIN_RF_SET_SET(w)   w |= ( 0X1 << 3)
#define RTC_X32K_XIN_RF_SET_CLR(w)   w &= ~( 0X1 << 3)

#define RTC_X32K_XIN_DS2_SET_POS      2
#define RTC_X32K_XIN_DS2_SET_LEN      1
#define RTC_X32K_XIN_DS2_SET_MASK     0X00000004
#define RTC_X32K_XIN_DS2_SET_VAL(w)   (((w) & 0X00000004) >> 2)
#define RTC_X32K_XIN_DS2_SET_SET(w)   w |= ( 0X1 << 2)
#define RTC_X32K_XIN_DS2_SET_CLR(w)   w &= ~( 0X1 << 2)

#define RTC_X32K_XIN_DS1_SET_POS      1
#define RTC_X32K_XIN_DS1_SET_LEN      1
#define RTC_X32K_XIN_DS1_SET_MASK     0X00000002
#define RTC_X32K_XIN_DS1_SET_VAL(w)   (((w) & 0X00000002) >> 1)
#define RTC_X32K_XIN_DS1_SET_SET(w)   w |= ( 0X1 << 1)
#define RTC_X32K_XIN_DS1_SET_CLR(w)   w &= ~( 0X1 << 1)

#define RTC_X32K_XIN_DS0_SET_POS      0
#define RTC_X32K_XIN_DS0_SET_LEN      1
#define RTC_X32K_XIN_DS0_SET_MASK     0X00000001
#define RTC_X32K_XIN_DS0_SET_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_X32K_XIN_DS0_SET_SET(w)   w |= ( 0X1 << 0)
#define RTC_X32K_XIN_DS0_SET_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : X32K_XIN_CLR

#define RTC_X32K_XIN_CLR_ADDR      RTC_BASE_ADDR + 0X12C
#define RTC_X32K_XIN_CLR_RSTVAL    0X0
#define RTC_X32K_XIN_CLR_ALL1      0X0
#define RTC_X32K_XIN_CLR_ALL0      0X0
#define RTC_X32K_XIN_CLR_ALL5A     0X0
#define RTC_X32K_XIN_CLR_ALLA5     0X0

// FIELD IN REGISTER : X32K_XIN_CLR

#define RTC_X32K_XIN_XE_CLR_POS      4
#define RTC_X32K_XIN_XE_CLR_LEN      1
#define RTC_X32K_XIN_XE_CLR_MASK     0X00000010
#define RTC_X32K_XIN_XE_CLR_VAL(w)   (((w) & 0X00000010) >> 4)
#define RTC_X32K_XIN_XE_CLR_SET(w)   w |= ( 0X1 << 4)
#define RTC_X32K_XIN_XE_CLR_CLR(w)   w &= ~( 0X1 << 4)

#define RTC_X32K_XIN_RF_CLR_POS      3
#define RTC_X32K_XIN_RF_CLR_LEN      1
#define RTC_X32K_XIN_RF_CLR_MASK     0X00000008
#define RTC_X32K_XIN_RF_CLR_VAL(w)   (((w) & 0X00000008) >> 3)
#define RTC_X32K_XIN_RF_CLR_SET(w)   w |= ( 0X1 << 3)
#define RTC_X32K_XIN_RF_CLR_CLR(w)   w &= ~( 0X1 << 3)

#define RTC_X32K_XIN_DS2_CLR_POS      2
#define RTC_X32K_XIN_DS2_CLR_LEN      1
#define RTC_X32K_XIN_DS2_CLR_MASK     0X00000004
#define RTC_X32K_XIN_DS2_CLR_VAL(w)   (((w) & 0X00000004) >> 2)
#define RTC_X32K_XIN_DS2_CLR_SET(w)   w |= ( 0X1 << 2)
#define RTC_X32K_XIN_DS2_CLR_CLR(w)   w &= ~( 0X1 << 2)

#define RTC_X32K_XIN_DS1_CLR_POS      1
#define RTC_X32K_XIN_DS1_CLR_LEN      1
#define RTC_X32K_XIN_DS1_CLR_MASK     0X00000002
#define RTC_X32K_XIN_DS1_CLR_VAL(w)   (((w) & 0X00000002) >> 1)
#define RTC_X32K_XIN_DS1_CLR_SET(w)   w |= ( 0X1 << 1)
#define RTC_X32K_XIN_DS1_CLR_CLR(w)   w &= ~( 0X1 << 1)

#define RTC_X32K_XIN_DS0_CLR_POS      0
#define RTC_X32K_XIN_DS0_CLR_LEN      1
#define RTC_X32K_XIN_DS0_CLR_MASK     0X00000001
#define RTC_X32K_XIN_DS0_CLR_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_X32K_XIN_DS0_CLR_SET(w)   w |= ( 0X1 << 0)
#define RTC_X32K_XIN_DS0_CLR_CLR(w)   w &= ~( 0X1 << 0)

// REGISTER : REG_LDO08_LV

#define RTC_REG_LDO08_LV       RTC_BASE_ADDR + 0X130

// FIELD IN REGISTER : REG_LDO08_LV
#define RTC_REG_LDO08_LV_RSTVAL       0X8


// REGISTER : REG_LDO08_LV_SET

#define RTC_REG_LDO08_LV_SET   RTC_BASE_ADDR + 0X134

// FIELD IN REGISTER : REG_LDO08_LV_SET
#define RTC_REG_LDO08_LV_SET_RSTVAL   0X0

// REGISTER : REG_LDO08_LV_CLR

#define RTC_REG_LDO08_LV_CLR   RTC_BASE_ADDR + 0X138

// FIELD IN REGISTER : REG_LDO08_LV_CLR
#define RTC_REG_LDO08_LV_CLR_RSTVAL   0X0

// REGISTER : REG_LDO18_LV

#define RTC_REG_LDO18_LV       RTC_BASE_ADDR + 0X13C

// FIELD IN REGISTER : REG_LDO18_LV
#define RTC_REG_LDO18_LV_RSTVAL       0X8

// REGISTER : REG_LDO18_LV_SET

#define RTC_REG_LDO18_LV_SET   RTC_BASE_ADDR + 0X140

// FIELD IN REGISTER : REG_LDO18_LV_SET
#define RTC_REG_LDO18_LV_SET_RSTVAL   0X0

// REGISTER : REG_LDO18_LV_CLR

#define RTC_REG_LDO18_LV_CLR   RTC_BASE_ADDR + 0X144

// FIELD IN REGISTER : REG_LDO18_LV_CLR
#define RTC_REG_LDO18_LV_CLR_RSTVAL   0X0

// REGISTER : DUMMY_SW

#define RTC_DUMMY_SW_ADDR      RTC_BASE_ADDR + 0X148
#define RTC_DUMMY_SW_RSTVAL    0XFF00
#define RTC_DUMMY_SW_ALL1      0XFFFF
#define RTC_DUMMY_SW_ALL0      0X0
#define RTC_DUMMY_SW_ALL5A     0X5A5A
#define RTC_DUMMY_SW_ALLA5     0XA5A5

// FIELD IN REGISTER : DUMMY_SW

#define RTC_DUMMY_SW_POS      0
#define RTC_DUMMY_SW_LEN      16
#define RTC_DUMMY_SW_MASK     0X0000FFFF
#define RTC_DUMMY_SW_VAL(w)   (((w) & 0X0000FFFF) >> 0)
#define RTC_DUMMY_SW_SET(w)   w |= ( 0XFFFF << 0)
#define RTC_DUMMY_SW_CLR(w)   w &= ~( 0XFFFF << 0)

// REGISTER : DUMMY_SPARE_IN

#define RTC_DUMMY_SPARE_IN_ADDR      RTC_BASE_ADDR + 0X14C
#define RTC_DUMMY_SPARE_IN_RSTVAL    0X0
#define RTC_DUMMY_SPARE_IN_ALL1      0XFFFFFFFF
#define RTC_DUMMY_SPARE_IN_ALL0      0X0
#define RTC_DUMMY_SPARE_IN_ALL5A     0X5A5A5A5A
#define RTC_DUMMY_SPARE_IN_ALLA5     0XA5A5A5A5

// FIELD IN REGISTER : DUMMY_SPARE_IN

#define RTC_DUMMY_SPARE_IN_POS      0
#define RTC_DUMMY_SPARE_IN_LEN      32
#define RTC_DUMMY_SPARE_IN_MASK     0XFFFFFFFF
#define RTC_DUMMY_SPARE_IN_VAL(w)   (((w) & 0XFFFFFFFF) >> 0)
#define RTC_DUMMY_SPARE_IN_SET(w)   w |= ( 0XFFFFFFFF << 0)
#define RTC_DUMMY_SPARE_IN_CLR(w)   w &= ~( 0XFFFFFFFF << 0)

// REGISTER : DUMMY_SPARE_OUT

#define RTC_DUMMY_SPARE_OUT_ADDR      RTC_BASE_ADDR + 0X150
#define RTC_DUMMY_SPARE_OUT_RSTVAL    0X0
#define RTC_DUMMY_SPARE_OUT_ALL1      0XFFFFFFFF
#define RTC_DUMMY_SPARE_OUT_ALL0      0X0
#define RTC_DUMMY_SPARE_OUT_ALL5A     0X5A5A5A5A
#define RTC_DUMMY_SPARE_OUT_ALLA5     0XA5A5A5A5

// FIELD IN REGISTER : DUMMY_SPARE_OUT

#define RTC_DUMMY_SPARE_OUT_POS      0
#define RTC_DUMMY_SPARE_OUT_LEN      32
#define RTC_DUMMY_SPARE_OUT_MASK     0XFFFFFFFF
#define RTC_DUMMY_SPARE_OUT_VAL(w)   (((w) & 0XFFFFFFFF) >> 0)
#define RTC_DUMMY_SPARE_OUT_SET(w)   w |= ( 0XFFFFFFFF << 0)
#define RTC_DUMMY_SPARE_OUT_CLR(w)   w &= ~( 0XFFFFFFFF << 0)

// REGISTER : DUMMY_EN

#define RTC_DUMMY_EN_ADDR      RTC_BASE_ADDR + 0X154
#define RTC_DUMMY_EN_RSTVAL    0X0
#define RTC_DUMMY_EN_ALL1      0X1
#define RTC_DUMMY_EN_ALL0      0X0
#define RTC_DUMMY_EN_ALL5A     0X0
#define RTC_DUMMY_EN_ALLA5     0X1

// FIELD IN REGISTER : DUMMY_EN

#define RTC_DUMMY_EN_POS      0
#define RTC_DUMMY_EN_LEN      1
#define RTC_DUMMY_EN_MASK     0X00000001
#define RTC_DUMMY_EN_VAL(w)   (((w) & 0X00000001) >> 0)
#define RTC_DUMMY_EN_SET(w)   w |= ( 0X1 << 0)
#define RTC_DUMMY_EN_CLR(w)   w &= ~( 0X1 << 0)

#endif
