#!/bin/sh

while getopts "a:b:c:o:r:s:t:p:" arg
do
    case "$arg" in
        a)
            echo "reserved start address: $OPTARG"
            RESERVED_START=$OPTARG
            ;;
        b)
            echo "bootargs: $OPTARG"
            BOOT_ARGS=$OPTARG
            ;;
        c)
            echo "cmm args: $OPTARG"
            CMM_ARGS=$OPTARG
            ;;
        o)
            echo "dest file: $OPTARG"
            DEST_FILE=$OPTARG
            ;;
        r)
            echo "recycle cmm: $OPTARG"
            RECYCLE_CMM=$OPTARG
            ;;
        s)
            echo "reserved size: $OPTARG"
            RESERVED_SIZE=$OPTARG
            ;;
        t)
            echo "type: $OPTARG"
            FIRMWARE_TYPE=$OPTARG
            ;;
        p)
            echo "support atf: $OPTARG"
            SUPPORT_ATF=$OPTARG
            ;;
    esac
done

IS_ATF="ATF"
IS_TEE="TEE"
IS_RAMDISK="RAMDISK"
IS_DTB="DTB"
IS_RISCV="RISCV"
IS_RISCV_LOG_MEM="RISCV_LOG_MEM"
IS_ISP_IMAGE="ISP_IMAGE"
IS_RAMDISK_HEADER="RAMDISK_HEADER"
IS_MODEL_DATA="MODEL_DATA"
IS_CMM="CMM"
IS_RECYCLE_CMM="RECYCLE_CMM"
IS_DDR_RETRAIN="DDR_RETRAIN"

if [[ $SUPPORT_ATF = "FALSE" ]]
then
	sed -i 's/#define SUPPORT_ATF/#undef SUPPORT_ATF/g' $DEST_FILE
fi

if [[ $FIRMWARE_TYPE = $IS_ATF ]]
then
	ATF_RES_START_LOW=$(printf "0x%x\n" $(($RESERVED_START & 0xFFFFFFFF)))
	ATF_RES_START_HIGH=$(printf "0x%x\n" $(($RESERVED_START >> 32)))
	ATF_RES_SIZE_LOW=$(printf "0x%x\n" $(($RESERVED_SIZE & 0xFFFFFFFF)))
	ATF_RES_SIZE_HIGH=$(printf "0x%x\n" $(($RESERVED_SIZE >> 32)))
	echo "sed -i "s/ATF_RESERVED_START_HI/ATF_RESERVED_START_HI $ATF_RES_START_HIGH/g" $DEST_FILE"
	sed -i "s/ATF_RESERVED_START_HI/ATF_RESERVED_START_HI $ATF_RES_START_HIGH/g" $DEST_FILE
	sed -i "s/ATF_RESERVED_START_LO/ATF_RESERVED_START_LO $ATF_RES_START_LOW/g" $DEST_FILE
	sed -i "s/ATF_RESERVED_SIZE_HI/ATF_RESERVED_SIZE_HI $ATF_RES_SIZE_HIGH/g" $DEST_FILE
	sed -i "s/ATF_RESERVED_SIZE_LO/ATF_RESERVED_SIZE_LO $ATF_RES_SIZE_LOW/g" $DEST_FILE
elif [[ $FIRMWARE_TYPE = $IS_RISCV ]]
then
	sed -i '/#ifdef\s\+SUPPORT_RISCV/i #define SUPPORT_RISCV' $DEST_FILE
	RISCV_RES_START_LOW=$(printf "0x%x\n" $(($RESERVED_START & 0xFFFFFFFF)))
	RISCV_RES_START_HIGH=$(printf "0x%x\n" $(($RESERVED_START >> 32)))
	RISCV_RES_SIZE_LOW=$(printf "0x%x\n" $(($RESERVED_SIZE & 0xFFFFFFFF)))
	RISCV_RES_SIZE_HIGH=$(printf "0x%x\n" $(($RESERVED_SIZE >> 32)))
	sed -i "s/RISCV_RESERVED_START_HI/RISCV_RESERVED_START_HI $RISCV_RES_START_HIGH/g" $DEST_FILE
	sed -i "s/RISCV_RESERVED_START_LO/RISCV_RESERVED_START_LO $RISCV_RES_START_LOW/g" $DEST_FILE
	sed -i "s/RISCV_RESERVED_SIZE_HI/RISCV_RESERVED_SIZE_HI $RISCV_RES_SIZE_HIGH/g" $DEST_FILE
	sed -i "s/RISCV_RESERVED_SIZE_LO/RISCV_RESERVED_SIZE_LO $RISCV_RES_SIZE_LOW/g" $DEST_FILE
elif [[ $FIRMWARE_TYPE = $IS_RISCV_LOG_MEM ]]
then
	sed -i '/#ifdef\s\+SUPPORT_RISCV_LOG_MEM/i #define SUPPORT_RISCV_LOG_MEM' $DEST_FILE
	RISCV_RES_LOG_MEM_START_LOW=$(printf "0x%x\n" $(($RESERVED_START & 0xFFFFFFFF)))
	RISCV_RES_LOG_MEM_START_HIGH=$(printf "0x%x\n" $(($RESERVED_START >> 32)))
	RISCV_RES_LOG_MEM_SIZE_LOW=$(printf "0x%x\n" $(($RESERVED_SIZE & 0xFFFFFFFF)))
	RISCV_RES_LOG_MEM_SIZE_HIGH=$(printf "0x%x\n" $(($RESERVED_SIZE >> 32)))
	sed -i "s/RISCV_LOG_MEM_RESERVED_START_HI/RISCV_LOG_MEM_RESERVED_START_HI $RISCV_RES_LOG_MEM_START_HIGH/g" $DEST_FILE
	sed -i "s/RISCV_LOG_MEM_RESERVED_START_LO/RISCV_LOG_MEM_RESERVED_START_LO $RISCV_RES_LOG_MEM_START_LOW/g" $DEST_FILE
	sed -i "s/RISCV_LOG_MEM_RESERVED_SIZE_HI/RISCV_LOG_MEM_RESERVED_SIZE_HI $RISCV_RES_LOG_MEM_SIZE_HIGH/g" $DEST_FILE
	sed -i "s/RISCV_LOG_MEM_RESERVED_SIZE_LO/RISCV_LOG_MEM_RESERVED_SIZE_LO $RISCV_RES_LOG_MEM_SIZE_LOW/g" $DEST_FILE
elif [[ $FIRMWARE_TYPE = $IS_ISP_IMAGE ]]
then
	sed -i '/#ifdef\s\+SUPPORT_ISP_IMAGE/i #define SUPPORT_ISP_IMAGE' $DEST_FILE
	ISP_IMAGE_RES_START_LOW=$(printf "0x%x\n" $(($RESERVED_START & 0xFFFFFFFF)))
	ISP_IMAGE_RES_START_HIGH=$(printf "0x%x\n" $(($RESERVED_START >> 32)))
	ISP_IMAGE_RES_SIZE_LOW=$(printf "0x%x\n" $(($RESERVED_SIZE & 0xFFFFFFFF)))
	ISP_IMAGE_RES_SIZE_HIGH=$(printf "0x%x\n" $(($RESERVED_SIZE >> 32)))
	sed -i "s/ISP_IMAGE_RESERVED_START_HI/ISP_IMAGE_RESERVED_START_HI $ISP_IMAGE_RES_START_HIGH/g" $DEST_FILE
	sed -i "s/ISP_IMAGE_RESERVED_START_LO/ISP_IMAGE_RESERVED_START_LO $ISP_IMAGE_RES_START_LOW/g" $DEST_FILE
	sed -i "s/ISP_IMAGE_RESERVED_SIZE_HI/ISP_IMAGE_RESERVED_SIZE_HI $ISP_IMAGE_RES_SIZE_HIGH/g" $DEST_FILE
	sed -i "s/ISP_IMAGE_RESERVED_SIZE_LO/ISP_IMAGE_RESERVED_SIZE_LO $ISP_IMAGE_RES_SIZE_LOW/g" $DEST_FILE

elif [[ $FIRMWARE_TYPE = $IS_RAMDISK_HEADER ]]
then
	sed -i '/#ifdef\s\+SUPPORT_RAMDISK_HEADER/i #define SUPPORT_RAMDISK_HEADER' $DEST_FILE
	RAMDISK_HEADER_RES_START_LOW=$(printf "0x%x\n" $(($RESERVED_START & 0xFFFFFFFF)))
	RAMDISK_HEADER_RES_START_HIGH=$(printf "0x%x\n" $(($RESERVED_START >> 32)))
	RAMDISK_HEADER_RES_SIZE_LOW=$(printf "0x%x\n" $(($RESERVED_SIZE & 0xFFFFFFFF)))
	RAMDISK_HEADER_RES_SIZE_HIGH=$(printf "0x%x\n" $(($RESERVED_SIZE >> 32)))
	sed -i "s/RAMDISK_HEADER_RESERVED_START_HI/RAMDISK_HEADER_RESERVED_START_HI $RAMDISK_HEADER_RES_START_HIGH/g" $DEST_FILE
	sed -i "s/RAMDISK_HEADER_RESERVED_START_LO/RAMDISK_HEADER_RESERVED_START_LO $RAMDISK_HEADER_RES_START_LOW/g" $DEST_FILE
	sed -i "s/RAMDISK_HEADER_RESERVED_SIZE_HI/RAMDISK_HEADER_RESERVED_SIZE_HI $RAMDISK_HEADER_RES_SIZE_HIGH/g" $DEST_FILE
	sed -i "s/RAMDISK_HEADER_RESERVED_SIZE_LO/RAMDISK_HEADER_RESERVED_SIZE_LO $RAMDISK_HEADER_RES_SIZE_LOW/g" $DEST_FILE

elif [[ $FIRMWARE_TYPE = $IS_MODEL_DATA ]]
then
	sed -i '/#ifdef\s\+SUPPORT_MODEL_DATA/i #define SUPPORT_MODEL_DATA' $DEST_FILE
	MODEL_DATA_RES_START_LOW=$(printf "0x%x\n" $(($RESERVED_START & 0xFFFFFFFF)))
	MODEL_DATA_RES_START_HIGH=$(printf "0x%x\n" $(($RESERVED_START >> 32)))
	MODEL_DATA_RES_SIZE_LOW=$(printf "0x%x\n" $(($RESERVED_SIZE & 0xFFFFFFFF)))
	MODEL_DATA_RES_SIZE_HIGH=$(printf "0x%x\n" $(($RESERVED_SIZE >> 32)))
	sed -i "s/MODEL_DATA_RESERVED_START_HI/MODEL_DATA_RESERVED_START_HI $MODEL_DATA_RES_START_HIGH/g" $DEST_FILE
	sed -i "s/MODEL_DATA_RESERVED_START_LO/MODEL_DATA_RESERVED_START_LO $MODEL_DATA_RES_START_LOW/g" $DEST_FILE
	sed -i "s/MODEL_DATA_RESERVED_SIZE_HI/MODEL_DATA_RESERVED_SIZE_HI $MODEL_DATA_RES_SIZE_HIGH/g" $DEST_FILE
	sed -i "s/MODEL_DATA_RESERVED_SIZE_LO/MODEL_DATA_RESERVED_SIZE_LO $MODEL_DATA_RES_SIZE_LOW/g" $DEST_FILE

elif [[ $FIRMWARE_TYPE = $IS_TEE ]]
then
	sed -i '/#ifdef\s\+OPTEE_BOOT/i #define OPTEE_BOOT' $DEST_FILE
	OPTEE_RES_START_LOW=$(printf "0x%x\n" $(($RESERVED_START & 0xFFFFFFFF)))
	OPTEE_RES_START_HIGH=$(printf "0x%x\n" $(($RESERVED_START >> 32)))
	OPTEE_RES_SIZE_LOW=$(printf "0x%x\n" $(($RESERVED_SIZE & 0xFFFFFFFF)))
	OPTEE_RES_SIZE_HIGH=$(printf "0x%x\n" $(($RESERVED_SIZE >> 32)))
	sed -i "s/OPTEE_RESERVED_START_HI/OPTEE_RESERVED_START_HI $OPTEE_RES_START_HIGH/g" $DEST_FILE
	sed -i "s/OPTEE_RESERVED_START_LO/OPTEE_RESERVED_START_LO $OPTEE_RES_START_LOW/g" $DEST_FILE
	sed -i "s/OPTEE_RESERVED_SIZE_HI/OPTEE_RESERVED_SIZE_HI $OPTEE_RES_SIZE_HIGH/g" $DEST_FILE
	sed -i "s/OPTEE_RESERVED_SIZE_LO/OPTEE_RESERVED_SIZE_LO $OPTEE_RES_SIZE_LOW/g" $DEST_FILE
elif [[ $FIRMWARE_TYPE = $IS_RAMDISK ]]
then
	sed -i '/#ifdef\s\+SUPPORT_RAMDISK/i #define SUPPORT_RAMDISK' $DEST_FILE
	sed -i "s/RAMDISK_START_ADDR/RAMDISK_START_ADDR $RESERVED_START/g" $DEST_FILE
	sed -i "s/RAMDISK_SIZE/RAMDISK_SIZE $RESERVED_SIZE/g" $DEST_FILE
	sed -i "s#BOOTARGS \"bootargs\"#BOOTARGS \"$BOOT_ARGS\"#g" $DEST_FILE
elif [[ $FIRMWARE_TYPE = $IS_DTB ]]
then
	sed -i "s#BOOTARGS \"bootargs\"#BOOTARGS \"$BOOT_ARGS\"#g" $DEST_FILE
elif [[ $FIRMWARE_TYPE = $IS_CMM ]]
then
	sed -i "s#CMM_ARGS \"cmmargs\"#CMM_ARGS \"$CMM_ARGS\"#g" $DEST_FILE
elif [[ $FIRMWARE_TYPE = $IS_RECYCLE_CMM ]]
then
	sed -i '/#ifdef\s\+SUPPORT_RECYCLE_CMM/i #define SUPPORT_RECYCLE_CMM' $DEST_FILE
	sed -i "s/CMM_RECYCLE_START_ADDR/CMM_RECYCLE_START_ADDR $RESERVED_START/g" $DEST_FILE
	sed -i "s/CMM_RECYCLE_SIZE/CMM_RECYCLE_SIZE $RESERVED_SIZE/g" $DEST_FILE
elif [[ $FIRMWARE_TYPE = $IS_DDR_RETRAIN ]]
then
	sed -i '/#ifdef\s\+AX630C_DDR4_RETRAIN/i #define AX630C_DDR4_RETRAIN' $DEST_FILE
	sed -i "s/DDR_RETRAIN_START/DDR_RETRAIN_START $RESERVED_START/g" $DEST_FILE
	sed -i "s/DDR_RETRAIN_SIZE/DDR_RETRAIN_SIZE $RESERVED_SIZE/g" $DEST_FILE
fi
