
#ifndef __AX_REG_DPHY_H
#define __AX_REG_DPHY_H

/* Base Address 0X23F1000 */

/* Register : DPHY_TX0_reg0 */
#define DPHY_TX0_REG0_ADDR 0x0
#define DPHY_TX0_REG0_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG0 */
#define DPHY_TX0_REG0_DPHYTX0_RG_PLL_FBK_INT_MSK 8
#define DPHY_TX0_REG0_DPHYTX0_RG_PLL_FBK_INT_LSB 0
#define DPHY_TX0_REG0_DPHYTX0_RG_PLL_FBK_INT_DEFAULT 0x0

/* Register : DPHY_TX0_reg1 */
#define DPHY_TX0_REG1_ADDR 0x4
#define DPHY_TX0_REG1_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG1 */
#define DPHY_TX0_REG1_DPHYTX0_RG_PLL_FBK_FRA_MSK 23
#define DPHY_TX0_REG1_DPHYTX0_RG_PLL_FBK_FRA_LSB 0
#define DPHY_TX0_REG1_DPHYTX0_RG_PLL_FBK_FRA_DEFAULT 0x0

/* Register : DPHY_TX0_reg2 */
#define DPHY_TX0_REG2_ADDR 0x8
#define DPHY_TX0_REG2_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG2 */
#define DPHY_TX0_REG2_DPHYTX0_RG_PLL_PRE_DIV_MSK 1
#define DPHY_TX0_REG2_DPHYTX0_RG_PLL_PRE_DIV_LSB 0
#define DPHY_TX0_REG2_DPHYTX0_RG_PLL_PRE_DIV_DEFAULT 0x0

/* Register : DPHY_TX0_reg3 */
#define DPHY_TX0_REG3_ADDR 0xC

/* Field in register : DPHY_TX0_REG3 */
#define DPHY_TX0_REG3_DPHYTX0_RG_PLL_POS_DIV_MSK 0x7

/* Register : DPHY_TX0_reg4 */
#define DPHY_TX0_REG4_ADDR 0x10
#define DPHY_TX0_REG4_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG4 */
#define DPHY_TX0_REG4_DPHYTX0_RG_PLL_SSC_DELTA_MSK 0x3FF

/* Register : DPHY_TX0_reg5 */
#define DPHY_TX0_REG5_ADDR 0x14
#define DPHY_TX0_REG5_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG5 */
#define DPHY_TX0_REG5_DPHYTX0_RG_PLL_SSC_DELTA_INIT_MSK 0x3FF

/* Register : DPHY_TX0_reg6 */
#define DPHY_TX0_REG6_ADDR 0x18

/* Field in register : DPHY_TX0_REG6 */
#define DPHY_TX0_REG6_DPHYTX0_RG_PLL_SSC_PRD_MSK 9
#define DPHY_TX0_REG6_DPHYTX0_RG_PLL_SSC_PRD_LSB 0
#define DPHY_TX0_REG6_DPHYTX0_RG_PLL_SSC_PRD_DEFAULT 0x0

/* Register : DPHY_TX0_reg7 */
#define DPHY_TX0_REG7_ADDR 0x1C

/* Field in register : DPHY_TX0_REG7 */
#define DPHYTX0_RG_PLL_SSC_EN BIT(0)

/* Register : DPHY_TX0_reg8 */
#define DPHY_TX0_REG8_ADDR 0x20
#define DPHY_TX0_REG8_DEFAULT 0x1

/* Field in register : DPHY_TX0_REG8 */
#define DPHY_TX0_REG8_DPHYTX0_REFCLK_IN_SEL_MSK 0x7

/* Register : DPHY_TX0_reg9 */
#define DPHY_TX0_REG9_ADDR 0x24

/* Field in register : DPHY_TX0_REG9 */
#define DPHY_TX0_REG9_DPHYTX0_RG_EXTD_CYCLE_SEL_MSK 0x7

/* Register : DPHY_TX0_reg10 */
#define DPHY_TX0_REG10_ADDR 0x28

/* Field in register : DPHY_TX0_REG10 */
#define DPHY_TX0_REG10_DPHYTX0_RG_DLANE_HS_PRE_TIME_MSK 0xFF

/* Register : DPHY_TX0_reg11 */
#define DPHY_TX0_REG11_ADDR 0x2C

/* Field in register : DPHY_TX0_REG11 */
#define DPHY_TX0_REG11_DPHYTX0_RG_DLANE_HS_ZERO_TIME_MSK 0xFF

/* Register : DPHY_TX0_reg12 */
#define DPHY_TX0_REG12_ADDR 0x30

/* Field in register : DPHY_TX0_REG12 */
#define DPHY_TX0_REG12_DPHYTX0_RG_DLANE_HS_TRAIL_TIME_MSK 0xFF

/* Register : DPHY_TX0_reg13 */
#define DPHY_TX0_REG13_ADDR 0x34

/* Field in register : DPHY_TX0_REG13 */
#define DPHY_TX0_REG13_DPHYTX0_RG_CLANE_HS_PRE_TIME_MSK 0xFF

/* Register : DPHY_TX0_reg14 */
#define DPHY_TX0_REG14_ADDR 0x38

/* Field in register : DPHY_TX0_REG14 */
#define DPHY_TX0_REG14_DPHYTX0_RG_CLANE_HS_ZERO_TIME_MSK 0xFF

/* Register : DPHY_TX0_reg15 */
#define DPHY_TX0_REG15_ADDR 0x3C

/* Field in register : DPHY_TX0_REG15 */
#define DPHY_TX0_REG15_DPHYTX0_RG_CLANE_HS_TRAIL_TIME_MSK 0xFF

/* Register : DPHY_TX0_reg16 */
#define DPHY_TX0_REG16_ADDR 0x40

/* Field in register : DPHY_TX0_REG16 */
#define DPHY_TX0_REG16_DPHYTX0_RG_CLANE_HS_CLK_PRE_TIME_MSK 0xFF

/* Register : DPHY_TX0_reg17 */
#define DPHY_TX0_REG17_ADDR 0x44

/* Field in register : DPHY_TX0_REG17 */
#define DPHY_TX0_REG17_DPHYTX0_RG_CLANE_HS_CLK_POST_TIME_MSK 0xFF

/* Register : DPHY_TX0_reg18 */
#define DPHY_TX0_REG18_ADDR 0x48

/* Field in register : DPHY_TX0_REG18 */
#define DPHYTX0_CFG_DATABUS16_SEL BIT(0)

/* Register : DPHY_TX0_reg19 */
#define DPHY_TX0_REG19_ADDR 0x4C
#define DPHY_TX0_REG19_DEFAULT 0x10

/* Field in register : DPHY_TX0_REG19 */
#define DPHY_TX0_REG19_DPHYTX0_CFG_CKLANE_SET_MSK 4
#define DPHY_TX0_REG19_DPHYTX0_CFG_CKLANE_SET_LSB 0
#define DPHY_TX0_REG19_DPHYTX0_CFG_CKLANE_SET_DEFAULT 0x10

/* Register : DPHY_TX0_reg20 */
#define DPHY_TX0_REG20_ADDR 0x50
#define DPHY_TX0_REG20_DEFAULT 0x3

/* Field in register : DPHY_TX0_REG20 */
#define DPHY_TX0_REG20_DPHYTX0_CFG_L4_SWAP_SEL_MSK 0x7

/* Register : DPHY_TX0_reg21 */
#define DPHY_TX0_REG21_ADDR 0x54
#define DPHY_TX0_REG21_DEFAULT 0x2

/* Field in register : DPHY_TX0_REG21 */
#define DPHY_TX0_REG21_DPHYTX0_CFG_L3_SWAP_SEL_MSK 0x7

/* Register : DPHY_TX0_reg22 */
#define DPHY_TX0_REG22_ADDR 0x58
#define DPHY_TX0_REG22_DEFAULT 0x4

/* Field in register : DPHY_TX0_REG22 */
#define DPHY_TX0_REG22_DPHYTX0_CFG_L2_SWAP_SEL_MSK 0x7
#define DPHY_TX0_REG22_DPHYTX0_CFG_L2_SWAP_SEL_LSB 0
#define DPHY_TX0_REG22_DPHYTX0_CFG_L2_SWAP_SEL_DEFAULT 0x4

/* Register : DPHY_TX0_reg23 */
#define DPHY_TX0_REG23_ADDR 0x5C
#define DPHY_TX0_REG23_DEFAULT 0x1

/* Field in register : DPHY_TX0_REG23 */
#define DPHY_TX0_REG23_DPHYTX0_CFG_L1_SWAP_SEL_MSK 0x7
#define DPHY_TX0_REG23_DPHYTX0_CFG_L1_SWAP_SEL_LSB 0
#define DPHY_TX0_REG23_DPHYTX0_CFG_L1_SWAP_SEL_DEFAULT 0x1

/* Register : DPHY_TX0_reg24 */
#define DPHY_TX0_REG24_ADDR 0x60
#define DPHY_TX0_REG24_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG24 */
#define DPHY_TX0_REG24_DPHYTX0_CFG_L0_SWAP_SEL_MSK 0x7
#define DPHY_TX0_REG24_DPHYTX0_CFG_L0_SWAP_SEL_LSB 0
#define DPHY_TX0_REG24_DPHYTX0_CFG_L0_SWAP_SEL_DEFAULT 0x0

/* Register : DPHY_TX0_reg25 */
#define DPHY_TX0_REG25_ADDR 0x64
#define DPHY_TX0_REG25_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG25 */
#define DPHY_TX0_REG25_DPHYTX0_CFG_DPDN_SWAP_MSK 4
#define DPHY_TX0_REG25_DPHYTX0_CFG_DPDN_SWAP_LSB 0
#define DPHY_TX0_REG25_DPHYTX0_CFG_DPDN_SWAP_DEFAULT 0x0

/* Register : DPHY_TX0_reg26 */
#define DPHY_TX0_REG26_ADDR 0x68
#define DPHY_TX0_REG26_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG26 */
#define DPHY_TX0_REG26_DPHYTX0_VCONTROL_MSK 4
#define DPHY_TX0_REG26_DPHYTX0_VCONTROL_LSB 0
#define DPHY_TX0_REG26_DPHYTX0_VCONTROL_DEFAULT 0x0

/* Register : DPHY_TX0_reg27 */
#define DPHY_TX0_REG27_ADDR 0x6C
#define DPHY_TX0_REG27_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG27 */
#define DPHY_TX0_REG27_DPHYTX0_MPOSV_L_MSK 31
#define DPHY_TX0_REG27_DPHYTX0_MPOSV_L_LSB 0
#define DPHY_TX0_REG27_DPHYTX0_MPOSV_L_DEFAULT 0x0

/* Register : DPHY_TX0_reg28 */
#define DPHY_TX0_REG28_ADDR 0x70
#define DPHY_TX0_REG28_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG28 */
#define DPHY_TX0_REG28_DPHYTX0_MPOSV_H_MSK 14
#define DPHY_TX0_REG28_DPHYTX0_MPOSV_H_LSB 0
#define DPHY_TX0_REG28_DPHYTX0_MPOSV_H_DEFAULT 0x0

/* Register : DPHY_TX0_reg29 */
#define DPHY_TX0_REG29_ADDR 0x74
#define DPHY_TX0_REG29_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG29 */
#define DPHY_TX0_REG29_DPHYTX0_DBG1_MUX_SEL_MSK 4
#define DPHY_TX0_REG29_DPHYTX0_DBG1_MUX_SEL_LSB 0
#define DPHY_TX0_REG29_DPHYTX0_DBG1_MUX_SEL_DEFAULT 0x0

/* Register : DPHY_TX0_reg30 */
#define DPHY_TX0_REG30_ADDR 0x78
#define DPHY_TX0_REG30_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG30 */
#define DPHY_TX0_REG30_DPHYTX0_DBG2_MUX_SEL_MSK 4
#define DPHY_TX0_REG30_DPHYTX0_DBG2_MUX_SEL_LSB 0
#define DPHY_TX0_REG30_DPHYTX0_DBG2_MUX_SEL_DEFAULT 0x0

/* Register : DPHY_TX0_reg31 */
#define DPHY_TX0_REG31_ADDR 0x7C

/* Field in register : DPHY_TX0_REG31 */
#define DPHY_TX0_REG31_DPHYTX0_DBG1_MUX_DOUT_MSK 0xFF

/* Register : DPHY_TX0_reg32 */
#define DPHY_TX0_REG32_ADDR 0x80

/* Field in register : DPHY_TX0_REG32 */
#define DPHY_TX0_REG32_DPHYTX0_DBG2_MUX_DOUT_MSK 0xFF

/* Register : DPHY_TX0_reg33 */
#define DPHY_TX0_REG33_ADDR 0x84
#define DPHY_TX0_REG33_DEFAULT 0x87654321

/* Field in register : DPHY_TX0_REG33 */
#define DPHY_TX0_REG33_DPHYTX0_XCFGI_DW00_MSK 31

/* Register : DPHY_TX0_reg34 */
#define DPHY_TX0_REG34_ADDR 0x88
#define DPHY_TX0_REG34_DEFAULT 0xFEDCBA9

/* Field in register : DPHY_TX0_REG34 */

/* Register : DPHY_TX0_reg35 */
#define DPHY_TX0_REG35_ADDR 0x8C

/* Field in register : DPHY_TX0_REG35 */

/* Register : DPHY_TX0_reg36 */
#define DPHY_TX0_REG36_ADDR 0x90

/* Field in register : DPHY_TX0_REG36 */

/* Register : DPHY_TX0_reg37 */
#define DPHY_TX0_REG37_ADDR 0x94

/* Field in register : DPHY_TX0_REG37 */

/* Register : DPHY_TX0_reg38 */
#define DPHY_TX0_REG38_ADDR 0x98

/* Field in register : DPHY_TX0_REG38 */

/* Register : DPHY_TX0_reg39 */
#define DPHY_TX0_REG39_ADDR 0x9C

/* Field in register : DPHY_TX0_REG39 */

/* Register : DPHY_TX0_reg40 */
#define DPHY_TX0_REG40_ADDR 0xA0
#define DPHY_TX0_REG40_DEFAULT 0x21084210

/* Field in register : DPHY_TX0_REG40 */

/* Register : DPHY_TX0_reg41 */
#define DPHY_TX0_REG41_ADDR 0xA4
#define DPHY_TX0_REG41_DEFAULT 0x84210

/* Field in register : DPHY_TX0_REG41 */

/* Register : DPHY_TX0_reg42 */
#define DPHY_TX0_REG42_ADDR 0xA8
#define DPHY_TX0_REG42_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG42 */
#define DPHY_TX0_REG42_DPHYTX0_XCFGI_DW09_MSK 31
#define DPHY_TX0_REG42_DPHYTX0_XCFGI_DW09_LSB 0
#define DPHY_TX0_REG42_DPHYTX0_XCFGI_DW09_DEFAULT 0x0

/* Register : DPHY_TX0_reg43 */
#define DPHY_TX0_REG43_ADDR 0xAC
#define DPHY_TX0_REG43_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG43 */
#define DPHY_TX0_REG43_DPHYTX0_GPIO_MODE_MSK 4
#define DPHY_TX0_REG43_DPHYTX0_GPIO_MODE_LSB 0
#define DPHY_TX0_REG43_DPHYTX0_GPIO_MODE_DEFAULT 0x0

/* Register : DPHY_TX0_reg44 */
#define DPHY_TX0_REG44_ADDR 0xB0
#define DPHY_TX0_REG44_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG44 */
#define DPHY_TX0_REG44_DPHYTX0_GPIO_DP_I_MSK 4
#define DPHY_TX0_REG44_DPHYTX0_GPIO_DP_I_LSB 0
#define DPHY_TX0_REG44_DPHYTX0_GPIO_DP_I_DEFAULT 0x0

/* Register : DPHY_TX0_reg45 */
#define DPHY_TX0_REG45_ADDR 0xB4
#define DPHY_TX0_REG45_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG45 */
#define DPHY_TX0_REG45_DPHYTX0_GPIO_DN_I_MSK 4
#define DPHY_TX0_REG45_DPHYTX0_GPIO_DN_I_LSB 0
#define DPHY_TX0_REG45_DPHYTX0_GPIO_DN_I_DEFAULT 0x0

/* Register : DPHY_TX0_reg46 */
#define DPHY_TX0_REG46_ADDR 0xB8
#define DPHY_TX0_REG46_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG46 */
#define DPHY_TX0_REG46_DPHYTX0_GPIO_DP_OE_MSK 4
#define DPHY_TX0_REG46_DPHYTX0_GPIO_DP_OE_LSB 0
#define DPHY_TX0_REG46_DPHYTX0_GPIO_DP_OE_DEFAULT 0x0

/* Register : DPHY_TX0_reg47 */
#define DPHY_TX0_REG47_ADDR 0xBC
#define DPHY_TX0_REG47_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG47 */
#define DPHY_TX0_REG47_DPHYTX0_GPIO_DN_OE_MSK 4
#define DPHY_TX0_REG47_DPHYTX0_GPIO_DN_OE_LSB 0
#define DPHY_TX0_REG47_DPHYTX0_GPIO_DN_OE_DEFAULT 0x0

/* Register : DPHY_TX0_reg48 */
#define DPHY_TX0_REG48_ADDR 0xC0
#define DPHY_TX0_REG48_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG48 */
#define DPHY_TX0_REG48_DPHYTX0_GPIO_DP_PULLDOWN_MSK 4
#define DPHY_TX0_REG48_DPHYTX0_GPIO_DP_PULLDOWN_LSB 0
#define DPHY_TX0_REG48_DPHYTX0_GPIO_DP_PULLDOWN_DEFAULT 0x0

/* Register : DPHY_TX0_reg49 */
#define DPHY_TX0_REG49_ADDR 0xC4
#define DPHY_TX0_REG49_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG49 */
#define DPHY_TX0_REG49_DPHYTX0_GPIO_DN_PULLDOWN_MSK 4
#define DPHY_TX0_REG49_DPHYTX0_GPIO_DN_PULLDOWN_LSB 0
#define DPHY_TX0_REG49_DPHYTX0_GPIO_DN_PULLDOWN_DEFAULT 0x0

/* Register : DPHY_TX0_reg50 */
#define DPHY_TX0_REG50_ADDR 0xC8
#define DPHY_TX0_REG50_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG50 */
#define DPHY_TX0_REG50_DPHYTX0_GPIO_DP_IE_LANE0_MSK 0
#define DPHY_TX0_REG50_DPHYTX0_GPIO_DP_IE_LANE0_LSB 0
#define DPHY_TX0_REG50_DPHYTX0_GPIO_DP_IE_LANE0_DEFAULT 0x0

/* Register : DPHY_TX0_reg51 */
#define DPHY_TX0_REG51_ADDR 0xCF
#define DPHY_TX0_REG51_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG51 */
#define DPHY_TX0_REG51_DPHYTX0_GPIO_DN_IE_LANE0_MSK 0
#define DPHY_TX0_REG51_DPHYTX0_GPIO_DN_IE_LANE0_LSB 0
#define DPHY_TX0_REG51_DPHYTX0_GPIO_DN_IE_LANE0_DEFAULT 0x0

/* Register : DPHY_TX0_reg52 */
#define DPHY_TX0_REG52_ADDR 0xD0
#define DPHY_TX0_REG52_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG52 */
#define DPHY_TX0_REG52_DPHYTX0_GPIO_DP_C_LANE0_MSK 0
#define DPHY_TX0_REG52_DPHYTX0_GPIO_DP_C_LANE0_LSB 0
#define DPHY_TX0_REG52_DPHYTX0_GPIO_DP_C_LANE0_DEFAULT 0x0

/* Register : DPHY_TX0_reg53 */
#define DPHY_TX0_REG53_ADDR 0xD4
#define DPHY_TX0_REG53_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG53 */
#define DPHY_TX0_REG53_DPHYTX0_GPIO_DN_C_LANE0_MSK 0
#define DPHY_TX0_REG53_DPHYTX0_GPIO_DN_C_LANE0_LSB 0
#define DPHY_TX0_REG53_DPHYTX0_GPIO_DN_C_LANE0_DEFAULT 0x0

/* Register : DPHY_TX0_reg54 */
#define DPHY_TX0_REG54_ADDR 0xD8
#define DPHY_TX0_REG54_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG54 */
#define DPHY_TX0_REG54_DPHYTX0_RG_SCAN_PLL_EN1_MSK 0
#define DPHY_TX0_REG54_DPHYTX0_RG_SCAN_PLL_EN1_LSB 0
#define DPHY_TX0_REG54_DPHYTX0_RG_SCAN_PLL_EN1_DEFAULT 0x0

/* Register : DPHY_TX0_reg55 */
#define DPHY_TX0_REG55_ADDR 0xDC
#define DPHY_TX0_REG55_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG55 */
#define DPHY_TX0_REG55_DPHYTX0_RG_SCAN_PLL_EN2_MSK 0
#define DPHY_TX0_REG55_DPHYTX0_RG_SCAN_PLL_EN2_LSB 0
#define DPHY_TX0_REG55_DPHYTX0_RG_SCAN_PLL_EN2_DEFAULT 0x0

/* Register : DPHY_TX0_reg56 */
#define DPHY_TX0_REG56_ADDR 0xE0
#define DPHY_TX0_REG56_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG56 */
#define DPHY_TX0_REG56_DPHYTX0_RG_SCAN_PLL_EN3_MSK 0
#define DPHY_TX0_REG56_DPHYTX0_RG_SCAN_PLL_EN3_LSB 0
#define DPHY_TX0_REG56_DPHYTX0_RG_SCAN_PLL_EN3_DEFAULT 0x0

/* Register : DPHY_TX0_reg57 */
#define DPHY_TX0_REG57_ADDR 0xE4
#define DPHY_TX0_REG57_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG57 */
#define DPHY_TX0_REG57_DPHYTX0_PLL_RST_N_MSK 0
#define DPHY_TX0_REG57_DPHYTX0_PLL_RST_N_LSB 0
#define DPHY_TX0_REG57_DPHYTX0_PLL_RST_N_DEFAULT 0x0

/* Register : DPHY_TX0_reg58 */
#define DPHY_TX0_REG58_ADDR 0xE8
#define DPHY_TX0_REG58_DEFAULT 0x1

/* Field in register : DPHY_TX0_REG58 */
#define DPHY_TX0_REG58_DPHYTX0_PLL_BYPASS_MSK 0
#define DPHY_TX0_REG58_DPHYTX0_PLL_BYPASS_LSB 0
#define DPHY_TX0_REG58_DPHYTX0_PLL_BYPASS_DEFAULT 0x1

/* Register : DPHY_TX0_reg59 */
#define DPHY_TX0_REG59_ADDR 0xEC
#define DPHY_TX0_REG59_DEFAULT 0x0

/* Register : DPHY_TX0_reg60 */
#define DPHY_TX0_REG60_ADDR 0xF0
#define DPHY_TX0_REG60_DEFAULT 0x0

/* Register : DPHY_TX0_reg61 */
#define DPHY_TX0_REG61_ADDR 0xF4
#define DPHY_TX0_REG61_DEFAULT 0x0

/* Register : DPHY_TX0_reg62 */
#define DPHY_TX0_REG62_ADDR 0xF8
#define DPHY_TX0_REG62_DEFAULT 0x1


/* Register : ppi_reg_0 */
#define DPHY_PPI_REG_0_ADDR 0xFC
#define DPHY_PPI_REG_0_DEFAULT 0x0

/* Field in register : PPI_REG_0 */
#define DPHY_PPI_REG_0_DPHYTX0_PPI_TURNDISABLE_LAN0_MSK 0
#define DPHY_PPI_REG_0_DPHYTX0_PPI_TURNDISABLE_LAN0_LSB 0
#define DPHY_PPI_REG_0_DPHYTX0_PPI_TURNDISABLE_LAN0_DEFAULT 0x0

/* Register : ppi_reg_1 */
#define DPHY_PPI_REG_1_ADDR 0x100
#define DPHY_PPI_REG_1_DEFAULT 0x0

/* Field in register : PPI_REG_1 */
#define DPHY_PPI_REG_1_DPHYTX0_PPI_FORCERXMODE_LAN0_MSK 0
#define DPHY_PPI_REG_1_DPHYTX0_PPI_FORCERXMODE_LAN0_LSB 0
#define DPHY_PPI_REG_1_DPHYTX0_PPI_FORCERXMODE_LAN0_DEFAULT 0x0

/* Register : ppi_reg_2 */
#define DPHY_PPI_REG_2_ADDR 0x104
#define DPHY_PPI_REG_2_DEFAULT 0x0

/* Field in register : PPI_REG_2 */
#define DPHY_PPI_REG_2_DPHYTX0_PPI_ENABLE_CLK0_MSK 0
#define DPHY_PPI_REG_2_DPHYTX0_PPI_ENABLE_CLK0_LSB 0
#define DPHY_PPI_REG_2_DPHYTX0_PPI_ENABLE_CLK0_DEFAULT 0x0

/* Register : ppi_reg_3 */
#define DPHY_PPI_REG_3_ADDR 0x108
#define DPHY_PPI_REG_3_DEFAULT 0x0

/* Field in register : PPI_REG_3 */
#define DPHY_PPI_REG_3_DPHYTX0_PPI_ENABLE_LAN_MSK 3
#define DPHY_PPI_REG_3_DPHYTX0_PPI_ENABLE_LAN_LSB 0
#define DPHY_PPI_REG_3_DPHYTX0_PPI_ENABLE_LAN_DEFAULT 0x0

/* Register : MIPITX_EN */
#define DPHY_MIPITX0_EN_ADDR 0x10C
#define DPHY_MIPITX0_EN_DEFAULT 0x0

/* Register : DPHY_TX0_reg0_set */
#define DPHY_TX0_REG0_SET_ADDR 0x110

/* Field in register : DPHY_TX0_REG0_SET */
#define DPHY_TX0_REG0_SET_DPHYTX0_RG_PLL_FBK_INT_SET_MSK 0x1FF

/* Register : DPHY_TX0_reg0_clr */
#define DPHY_TX0_REG0_CLR_ADDR 0x114

/* Field in register : DPHY_TX0_REG0_CLR */
#define DPHY_TX0_REG0_CLR_DPHYTX0_RG_PLL_FBK_INT_CLR_MSK 0x1FF
#define DPHY_TX0_REG0_CLR_DPHYTX0_RG_PLL_FBK_INT_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg1_set */
#define DPHY_TX0_REG1_SET_ADDR 0x118

/* Field in register : DPHY_TX0_REG1_SET */
#define DPHY_TX0_REG1_SET_DPHYTX0_RG_PLL_FBK_FRA_SET_MSK 0xFFFFFF

/* Register : DPHY_TX0_reg1_clr */
#define DPHY_TX0_REG1_CLR_ADDR 0x11C

/* Field in register : DPHY_TX0_REG1_CLR */
#define DPHY_TX0_REG1_CLR_DPHYTX0_RG_PLL_FBK_FRA_CLR_MSK 0xFFFFFF

/* Register : DPHY_TX0_reg2_set */
#define DPHY_TX0_REG2_SET_ADDR 0x120

/* Field in register : DPHY_TX0_REG2_SET */
#define DPHY_TX0_REG2_SET_DPHYTX0_RG_PLL_PRE_DIV_SET_MSK 0x3

/* Register : DPHY_TX0_reg2_clr */
#define DPHY_TX0_REG2_CLR_ADDR 0x124

/* Field in register : DPHY_TX0_REG2_CLR */
#define DPHY_TX0_REG2_CLR_DPHYTX0_RG_PLL_PRE_DIV_CLR_MSK 0x3

/* Register : DPHY_TX0_reg3_set */
#define DPHY_TX0_REG3_SET_ADDR 0x128
#define DPHY_TX0_REG3_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG3_SET */
#define DPHY_TX0_REG3_SET_DPHYTX0_RG_PLL_POS_DIV_SET_MSK 0x7

/* Register : DPHY_TX0_reg3_clr */
#define DPHY_TX0_REG3_CLR_ADDR 0x12C
#define DPHY_TX0_REG3_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG3_CLR */
#define DPHY_TX0_REG3_CLR_DPHYTX0_RG_PLL_POS_DIV_CLR_MSK 0x7

/* Register : DPHY_TX0_reg4_set */
#define DPHY_TX0_REG4_SET_ADDR 0x130
#define DPHY_TX0_REG4_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG4_SET */
#define DPHY_TX0_REG4_SET_DPHYTX0_RG_PLL_SSC_DELTA_SET_MSK 0x3ffff

/* Register : DPHY_TX0_reg4_clr */
#define DPHY_TX0_REG4_CLR_ADDR 0x134

/* Field in register : DPHY_TX0_REG4_CLR */
#define DPHY_TX0_REG4_CLR_DPHYTX0_RG_PLL_SSC_DELTA_CLR_MSK 0x3ffff

/* Register : DPHY_TX0_reg5_set */
#define DPHY_TX0_REG5_SET_ADDR 0x138

/* Field in register : DPHY_TX0_REG5_SET */
#define DPHY_TX0_REG5_SET_DPHYTX0_RG_PLL_SSC_DELTA_INIT_SET_MSK 0x3FFFF

/* Register : DPHY_TX0_reg5_clr */
#define DPHY_TX0_REG5_CLR_ADDR 0x13C

/* Field in register : DPHY_TX0_REG5_CLR */
#define DPHY_TX0_REG5_CLR_DPHYTX0_RG_PLL_SSC_DELTA_INIT_CLR_MSK 0x3FFFF

/* Register : DPHY_TX0_reg6_set */
#define DPHY_TX0_REG6_SET_ADDR 0x140

/* Field in register : DPHY_TX0_REG6_SET */
#define DPHY_TX0_REG6_SET_DPHYTX0_RG_PLL_SSC_PRD_SET_MSK 0x3FF

/* Register : DPHY_TX0_reg6_clr */
#define DPHY_TX0_REG6_CLR_ADDR 0x144

/* Field in register : DPHY_TX0_REG6_CLR */
#define DPHY_TX0_REG6_CLR_DPHYTX0_RG_PLL_SSC_PRD_CLR_MSK 0x3FF

/* Register : DPHY_TX0_reg7_set */
#define DPHY_TX0_REG7_SET_ADDR 0x148
#define DPHY_TX0_REG7_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG7_SET */
#define DPHYTX0_RG_PLL_SSC_EN_SET BIT(0)

/* Register : DPHY_TX0_reg7_clr */
#define DPHY_TX0_REG7_CLR_ADDR 0x14C

/* Field in register : DPHY_TX0_REG7_CLR */
#define DPHYTX0_RG_PLL_SSC_EN_CLR BIT(0)

/* Register : DPHY_TX0_reg8_set */
#define DPHY_TX0_REG8_SET_ADDR 0x150

/* Field in register : DPHY_TX0_REG8_SET */
#define DPHYTX0_REFCLK_IN_SEL_SET_MSK 0x7

/* Register : DPHY_TX0_reg8_clr */
#define DPHY_TX0_REG8_CLR_ADDR 0x154

/* Field in register : DPHY_TX0_REG8_CLR */
#define DPHYTX0_REFCLK_IN_SEL_CLR_MSK 0x7

/* Register : DPHY_TX0_reg9_set */
#define DPHY_TX0_REG9_SET_ADDR 0x158

/* Field in register : DPHY_TX0_REG9_SET */
#define DPHYTX0_RG_EXTD_CYCLE_SEL_SET_MSK 0x7

/* Register : DPHY_TX0_reg9_clr */
#define DPHY_TX0_REG9_CLR_ADDR 0x15C

/* Field in register : DPHY_TX0_REG9_CLR */
#define DPHYTX0_RG_EXTD_CYCLE_SEL_CLR_MSK 0x7

/* Register : DPHY_TX0_reg10_set */
#define DPHY_TX0_REG10_SET_ADDR 0x160

/* Field in register : DPHY_TX0_REG10_SET */
#define DPHYTX0_RG_DLANE_HS_PRE_TIME_SET_MSK 0xFF

/* Register : DPHY_TX0_reg10_clr */
#define DPHY_TX0_REG10_CLR_ADDR 0x164

/* Field in register : DPHY_TX0_REG10_CLR */
#define DPHYTX0_RG_DLANE_HS_PRE_TIME_CLR_MSK 0xFF

/* Register : DPHY_TX0_reg11_set */
#define DPHY_TX0_REG11_SET_ADDR 0x168

/* Field in register : DPHY_TX0_REG11_SET */
#define DPHYTX0_RG_DLANE_HS_ZERO_TIME_SET_MSK 0xFF

/* Register : DPHY_TX0_reg11_clr */
#define DPHY_TX0_REG11_CLR_ADDR 0x16C

/* Field in register : DPHY_TX0_REG11_CLR */
#define DPHYTX0_RG_DLANE_HS_ZERO_TIME_CLR_MSK 0xFF

/* Register : DPHY_TX0_reg12_set */
#define DPHY_TX0_REG12_SET_ADDR 0x170

/* Field in register : DPHY_TX0_REG12_SET */
#define DPHYTX0_RG_DLANE_HS_TRAIL_TIME_SET_MSK 0xFF

/* Register : DPHY_TX0_reg12_clr */
#define DPHY_TX0_REG12_CLR_ADDR 0x174

/* Field in register : DPHY_TX0_REG12_CLR */
#define DPHYTX0_RG_DLANE_HS_TRAIL_TIME_CLR_MSK 0xFF

/* Register : DPHY_TX0_reg13_set */
#define DPHY_TX0_REG13_SET_ADDR 0x178

/* Field in register : DPHY_TX0_REG13_SET */
#define DPHY_TX0_REG13_SET_DPHYTX0_RG_CLANE_HS_PRE_TIME_SET_MSK 0xFF

/* Register : DPHY_TX0_reg13_clr */
#define DPHY_TX0_REG13_CLR_ADDR 0x17C

/* Field in register : DPHY_TX0_REG13_CLR */
#define DPHYTX0_RG_CLANE_HS_PRE_TIME_CLR_MSK 0xFF

/* Register : DPHY_TX0_reg14_set */
#define DPHY_TX0_REG14_SET_ADDR 0x180

/* Field in register : DPHY_TX0_REG14_SET */
#define DPHYTX0_RG_CLANE_HS_ZERO_TIME_SET_MSK 0xFF

/* Register : DPHY_TX0_reg14_clr */

#define DPHY_TX0_REG14_CLR_ADDR 0x184

/* Field in register : DPHY_TX0_REG14_CLR */
#define DPHYTX0_RG_CLANE_HS_ZERO_TIME_CLR_MSK 0xFF

/* Register : DPHY_TX0_reg15_set */

#define DPHY_TX0_REG15_SET_ADDR 0x188

/* Field in register : DPHY_TX0_REG15_SET */
#define DPHYTX0_RG_CLANE_HS_TRAIL_TIME_SET_MSK 0xFF

/* Register : DPHY_TX0_reg15_clr */
#define DPHY_TX0_REG15_CLR_ADDR 0x18C

/* Field in register : DPHY_TX0_REG15_CLR */
#define DPHYTX0_RG_CLANE_HS_TRAIL_TIME_CLR_MSK 0xFF

/* Register : DPHY_TX0_reg16_set */
#define DPHY_TX0_REG16_SET_ADDR 0x190

/* Field in register : DPHY_TX0_REG16_SET */

#define DPHYTX0_RG_CLANE_HS_CLK_PRE_TIME_SET_MSK 0xFF

/* Register : DPHY_TX0_reg16_clr */
#define DPHY_TX0_REG16_CLR_ADDR 0x194

/* Field in register : DPHY_TX0_REG16_CLR */
#define DPHYTX0_RG_CLANE_HS_CLK_PRE_TIME_CLR_MSK 0xFF

/* Register : DPHY_TX0_reg17_set */
#define DPHY_TX0_REG17_SET_ADDR 0x198

/* Field in register : DPHY_TX0_REG17_SET */
#define DPHYTX0_RG_CLANE_HS_CLK_POST_TIME_SET_MSK 0xFF

/* Register : DPHY_TX0_reg17_clr */
#define DPHY_TX0_REG17_CLR_ADDR 0x19C

/* Field in register : DPHY_TX0_REG17_CLR */
#define DPHYTX0_RG_CLANE_HS_CLK_POST_TIME_CLR_MSK 0xFF

/* Register : DPHY_TX0_reg18_set */
#define DPHY_TX0_REG18_SET_ADDR 0x1A0

/* Field in register : DPHY_TX0_REG18_SET */
#define DPHYTX0_CFG_DATABUS16_SEL_SET_MSK 0

/* Register : DPHY_TX0_reg18_clr */
#define DPHY_TX0_REG18_CLR_ADDR 0x1A4

/* Field in register : DPHY_TX0_REG18_CLR */
#define DPHYTX0_CFG_DATABUS16_SEL_CLR BIT(0)

/* Register : DPHY_TX0_reg19_set */
#define DPHY_TX0_REG19_SET_ADDR 0x1A8

/* Field in register : DPHY_TX0_REG19_SET */
#define DPHYTX0_CFG_CKLANE_SET_SET_MSK 0x1F

/* Register : DPHY_TX0_reg19_clr */
#define DPHY_TX0_REG19_CLR_ADDR 0x1AC

/* Field in register : DPHY_TX0_REG19_CLR */
#define DPHYTX0_CFG_CKLANE_SET_CLR_MSK 0x1F

/* Register : DPHY_TX0_reg20_set */
#define DPHY_TX0_REG20_SET_ADDR 0x1B0

/* Field in register : DPHY_TX0_REG20_SET */
#define DPHYTX0_CFG_L4_SWAP_SEL_SET_MSK 0x7

/* Register : DPHY_TX0_reg20_clr */
#define DPHY_TX0_REG20_CLR_ADDR 0x1B4

/* Field in register : DPHY_TX0_REG20_CLR */
#define DPHYTX0_CFG_L4_SWAP_SEL_CLR_MSK 0x7

/* Register : DPHY_TX0_reg21_set */
#define DPHY_TX0_REG21_SET_ADDR 0x1B8

/* Field in register : DPHY_TX0_REG21_SET */
#define DPHY_TX0_REG21_SET_DPHYTX0_CFG_L3_SWAP_SEL_SET_MSK 0x7

/* Register : DPHY_TX0_reg21_clr */
#define DPHY_TX0_REG21_CLR_ADDR 0x1BC

/* Field in register : DPHY_TX0_REG21_CLR */
#define DPHY_TX0_REG21_CLR_DPHYTX0_CFG_L3_SWAP_SEL_CLR_MSK 0x7

/* Register : DPHY_TX0_reg22_set */
#define DPHY_TX0_REG22_SET_ADDR 0x1C0

/* Field in register : DPHY_TX0_REG22_SET */
#define DPHY_TX0_REG22_SET_DPHYTX0_CFG_L2_SWAP_SEL_SET_MSK 0x7

/* Register : DPHY_TX0_reg22_clr */
#define DPHY_TX0_REG22_CLR_ADDR 0x1C4

/* Field in register : DPHY_TX0_REG22_CLR */
#define DPHY_TX0_REG22_CLR_DPHYTX0_CFG_L2_SWAP_SEL_CLR_MSK 0x7

/* Register : DPHY_TX0_reg23_set */
#define DPHY_TX0_REG23_SET_ADDR 0x1C8

/* Field in register : DPHY_TX0_REG23_SET */
#define DPHY_TX0_REG23_SET_DPHYTX0_CFG_L1_SWAP_SEL_SET_MSK 0x7

/* Register : DPHY_TX0_reg23_clr */
#define DPHY_TX0_REG23_CLR_ADDR 0x1CC

/* Field in register : DPHY_TX0_REG23_CLR */
#define DPHY_TX0_REG23_CLR_DPHYTX0_CFG_L1_SWAP_SEL_CLR_MSK 0x7

/* Register : DPHY_TX0_reg24_set */
#define DPHY_TX0_REG24_SET_ADDR 0x1D0

/* Field in register : DPHY_TX0_REG24_SET */
#define DPHY_TX0_REG24_SET_DPHYTX0_CFG_L0_SWAP_SEL_SET_MSK 0x7

/* Register : DPHY_TX0_reg24_clr */
#define DPHY_TX0_REG24_CLR_ADDR 0x1D4

/* Field in register : DPHY_TX0_REG24_CLR */
#define DPHY_TX0_REG24_CLR_DPHYTX0_CFG_L0_SWAP_SEL_CLR_MSK 0x7

/* Register : DPHY_TX0_reg25_set */
#define DPHY_TX0_REG25_SET_ADDR 0x1D8

/* Field in register : DPHY_TX0_REG25_SET */
#define DPHY_TX0_REG25_SET_DPHYTX0_CFG_DPDN_SWAP_SET_MSK 0x7

/* Register : DPHY_TX0_reg25_clr */
#define DPHY_TX0_REG25_CLR_ADDR 0x1DC
#define DPHY_TX0_REG25_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG25_CLR */
#define DPHY_TX0_REG25_CLR_DPHYTX0_CFG_DPDN_SWAP_CLR_MSK 4
#define DPHY_TX0_REG25_CLR_DPHYTX0_CFG_DPDN_SWAP_CLR_LSB 0
#define DPHY_TX0_REG25_CLR_DPHYTX0_CFG_DPDN_SWAP_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg26_set */
#define DPHY_TX0_REG26_SET_ADDR 0x1E0
#define DPHY_TX0_REG26_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG26_SET */
#define DPHY_TX0_REG26_SET_DPHYTX0_VCONTROL_SET_MSK 4
#define DPHY_TX0_REG26_SET_DPHYTX0_VCONTROL_SET_LSB 0
#define DPHY_TX0_REG26_SET_DPHYTX0_VCONTROL_SET_DEFAULT 0x0

/* Register : DPHY_TX0_reg26_clr */
#define DPHY_TX0_REG26_CLR_ADDR 0x1E4
#define DPHY_TX0_REG26_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG26_CLR */
#define DPHY_TX0_REG26_CLR_DPHYTX0_VCONTROL_CLR_MSK 4
#define DPHY_TX0_REG26_CLR_DPHYTX0_VCONTROL_CLR_LSB 0
#define DPHY_TX0_REG26_CLR_DPHYTX0_VCONTROL_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg29_set */
#define DPHY_TX0_REG29_SET_ADDR 0x1E8
#define DPHY_TX0_REG29_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG29_SET */
#define DPHY_TX0_REG29_SET_DPHYTX0_DBG1_MUX_SEL_SET_MSK 4
#define DPHY_TX0_REG29_SET_DPHYTX0_DBG1_MUX_SEL_SET_LSB 0
#define DPHY_TX0_REG29_SET_DPHYTX0_DBG1_MUX_SEL_SET_DEFAULT 0x0

/* Register : DPHY_TX0_reg29_clr */
#define DPHY_TX0_REG29_CLR_ADDR 0x1EC
#define DPHY_TX0_REG29_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG29_CLR */
#define DPHY_TX0_REG29_CLR_DPHYTX0_DBG1_MUX_SEL_CLR_MSK 4
#define DPHY_TX0_REG29_CLR_DPHYTX0_DBG1_MUX_SEL_CLR_LSB 0
#define DPHY_TX0_REG29_CLR_DPHYTX0_DBG1_MUX_SEL_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg30_set */
#define DPHY_TX0_REG30_SET_ADDR 0x1F0
#define DPHY_TX0_REG30_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG30_SET */
#define DPHY_TX0_REG30_SET_DPHYTX0_DBG2_MUX_SEL_SET_MSK 4
#define DPHY_TX0_REG30_SET_DPHYTX0_DBG2_MUX_SEL_SET_LSB 0
#define DPHY_TX0_REG30_SET_DPHYTX0_DBG2_MUX_SEL_SET_DEFAULT 0x0

/* Register : DPHY_TX0_reg30_clr */
#define DPHY_TX0_REG30_CLR_ADDR 0x1F4
#define DPHY_TX0_REG30_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG30_CLR */
#define DPHY_TX0_REG30_CLR_DPHYTX0_DBG2_MUX_SEL_CLR_MSK 4
#define DPHY_TX0_REG30_CLR_DPHYTX0_DBG2_MUX_SEL_CLR_LSB 0
#define DPHY_TX0_REG30_CLR_DPHYTX0_DBG2_MUX_SEL_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg33_set */
#define DPHY_TX0_REG33_SET_ADDR 0x1F8

/* Register : DPHY_TX0_reg33_clr */
#define DPHY_TX0_REG33_CLR_ADDR 0x1FC


/* Register : DPHY_TX0_reg34_set */
#define DPHY_TX0_REG34_SET_ADDR 0x200


/* Register : DPHY_TX0_reg34_clr */
#define DPHY_TX0_REG34_CLR_ADDR 0x204

/* Register : DPHY_TX0_reg35_set */
#define DPHY_TX0_REG35_SET_ADDR 0x208

/* Field in register : DPHY_TX0_REG35_SET */

/* Register : DPHY_TX0_reg35_clr */
#define DPHY_TX0_REG35_CLR_ADDR 0x20C

/* Field in register : DPHY_TX0_REG35_CLR */

/* Register : DPHY_TX0_reg36_set */
#define DPHY_TX0_REG36_SET_ADDR 0x210

/* Field in register : DPHY_TX0_REG36_SET */

/* Register : DPHY_TX0_reg36_clr */
#define DPHY_TX0_REG36_CLR_ADDR 0x214
#define DPHY_TX0_REG36_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG36_CLR */

/* Register : DPHY_TX0_reg37_set */
#define DPHY_TX0_REG37_SET_ADDR 0x218

/* Field in register : DPHY_TX0_REG37_SET */

/* Register : DPHY_TX0_reg37_clr */
#define DPHY_TX0_REG37_CLR_ADDR 0x21C
#define DPHY_TX0_REG37_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG37_CLR */

/* Register : DPHY_TX0_reg38_set */
#define DPHY_TX0_REG38_SET_ADDR 0x220

/* Field in register : DPHY_TX0_REG38_SET */

/* Register : DPHY_TX0_reg38_clr */
#define DPHY_TX0_REG38_CLR_ADDR 0x224

/* Field in register : DPHY_TX0_REG38_CLR */

/* Register : DPHY_TX0_reg39_set */
#define DPHY_TX0_REG39_SET_ADDR 0x228

/* Field in register : DPHY_TX0_REG39_SET */

/* Register : DPHY_TX0_reg39_clr */
#define DPHY_TX0_REG39_CLR_ADDR 0x22C

/* Register : DPHY_TX0_reg40_set */
#define DPHY_TX0_REG40_SET_ADDR 0x230

/* Register : DPHY_TX0_reg40_clr */
#define DPHY_TX0_REG40_CLR_ADDR 0x234

/* Register : DPHY_TX0_reg41_set */
#define DPHY_TX0_REG41_SET_ADDR 0x238

/* Field in register : DPHY_TX0_REG41_SET */

/* Register : DPHY_TX0_reg41_clr */
#define DPHY_TX0_REG41_CLR_ADDR 0x23C

/* Field in register : DPHY_TX0_REG41_CLR */

/* Register : DPHY_TX0_reg42_set */
#define DPHY_TX0_REG42_SET_ADDR 0x240

/* Field in register : DPHY_TX0_REG42_SET */

/* Register : DPHY_TX0_reg42_clr */
#define DPHY_TX0_REG42_CLR_ADDR 0x244

/* Field in register : DPHY_TX0_REG42_CLR */

/* Register : DPHY_TX0_reg43_set */
#define DPHY_TX0_REG43_SET_ADDR 0x248

/* Field in register : DPHY_TX0_REG43_SET */
#define DPHY_TX0_REG43_SET_DPHYTX0_GPIO_MODE_SET_MSK 0x1F

/* Register : DPHY_TX0_reg43_clr */
#define DPHY_TX0_REG43_CLR_ADDR 0x24C

/* Field in register : DPHY_TX0_REG43_CLR */
#define DPHY_TX0_REG43_CLR_DPHYTX0_GPIO_MODE_CLR_MSK 0x1F

/* Register : DPHY_TX0_reg44_set */
#define DPHY_TX0_REG44_SET_ADDR 0x250

/* Field in register : DPHY_TX0_REG44_SET */
#define DPHY_TX0_REG44_SET_DPHYTX0_GPIO_DP_I_SET_MSK 0x1F

/* Register : DPHY_TX0_reg44_clr */
#define DPHY_TX0_REG44_CLR_ADDR 0x254

/* Field in register : DPHY_TX0_REG44_CLR */
#define DPHY_TX0_REG44_CLR_DPHYTX0_GPIO_DP_I_CLR_MSK 0x1F

/* Register : DPHY_TX0_reg45_set */
#define DPHY_TX0_REG45_SET_ADDR 0x258
#define DPHY_TX0_REG45_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG45_SET */
#define DPHY_TX0_REG45_SET_DPHYTX0_GPIO_DN_I_SET_MSK 0x1F

/* Register : DPHY_TX0_reg45_clr */
#define DPHY_TX0_REG45_CLR_ADDR 0x25C

/* Field in register : DPHY_TX0_REG45_CLR */
#define DPHY_TX0_REG45_CLR_DPHYTX0_GPIO_DN_I_CLR_MSK 0x1F

/* Register : DPHY_TX0_reg46_set */
#define DPHY_TX0_REG46_SET_ADDR 0x260

/* Field in register : DPHY_TX0_REG46_SET */
#define DPHY_TX0_REG46_SET_DPHYTX0_GPIO_DP_OE_SET_MSK 0x1F

/* Register : DPHY_TX0_reg46_clr */
#define DPHY_TX0_REG46_CLR_ADDR 0x264

/* Field in register : DPHY_TX0_REG46_CLR */
#define DPHY_TX0_REG46_CLR_DPHYTX0_GPIO_DP_OE_CLR_MSK 0x1F

/* Register : DPHY_TX0_reg47_set */
#define DPHY_TX0_REG47_SET_ADDR 0x268

/* Field in register : DPHY_TX0_REG47_SET */
#define DPHY_TX0_REG47_SET_DPHYTX0_GPIO_DN_OE_SET_MSK 0x1F

/* Register : DPHY_TX0_reg47_clr */
#define DPHY_TX0_REG47_CLR_ADDR 0x26C

/* Field in register : DPHY_TX0_REG47_CLR */
#define DPHY_TX0_REG47_CLR_DPHYTX0_GPIO_DN_OE_CLR_MSK 0x1F

/* Register : DPHY_TX0_reg48_set */
#define DPHY_TX0_REG48_SET_ADDR 0x270

/* Field in register : DPHY_TX0_REG48_SET */
#define DPHY_TX0_REG48_SET_DPHYTX0_GPIO_DP_PULLDOWN_SET_MSK 0x1F

/* Register : DPHY_TX0_reg48_clr */
#define DPHY_TX0_REG48_CLR_ADDR 0x274

/* Field in register : DPHY_TX0_REG48_CLR */
#define DPHY_TX0_REG48_CLR_DPHYTX0_GPIO_DP_PULLDOWN_CLR_MSK 0x1F

/* Register : DPHY_TX0_reg49_set */
#define DPHY_TX0_REG49_SET_ADDR 0x278

/* Field in register : DPHY_TX0_REG49_SET */
#define DPHY_TX0_REG49_SET_DPHYTX0_GPIO_DN_PULLDOWN_SET_MSK 0x1F

/* Register : DPHY_TX0_reg49_clr */
#define DPHY_TX0_REG49_CLR_ADDR 0x27C

/* Field in register : DPHY_TX0_REG49_CLR */
#define DPHY_TX0_REG49_CLR_DPHYTX0_GPIO_DN_PULLDOWN_CLR_MSK 0x1F

/*Register : DPHY_TX0_reg50_set */
#define DPHY_TX0_REG50_SET_ADDR 0x280

/* Field in register : DPHY_TX0_REG50_SET */
#define DPHYTX0_GPIO_DP_IE_LANE0_SET BIT(0)

/* Register : DPHY_TX0_reg50_clr */
#define DPHY_TX0_REG50_CLR_ADDR 0x284
#define DPHY_TX0_REG50_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG50_CLR */
#define DPHY_TX0_REG50_CLR_DPHYTX0_GPIO_DP_IE_LANE0_CLR_MSK BIT(0)
#define DPHY_TX0_REG50_CLR_DPHYTX0_GPIO_DP_IE_LANE0_CLR_LSB 0
#define DPHY_TX0_REG50_CLR_DPHYTX0_GPIO_DP_IE_LANE0_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg51_set */
#define DPHY_TX0_REG51_SET_ADDR 0x288
#define DPHY_TX0_REG51_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG51_SET */
#define DPHY_TX0_REG51_SET_DPHYTX0_GPIO_DN_IE_LANE0_SET_MSK BIT(0)
#define DPHY_TX0_REG51_SET_DPHYTX0_GPIO_DN_IE_LANE0_SET_LSB 0
#define DPHY_TX0_REG51_SET_DPHYTX0_GPIO_DN_IE_LANE0_SET_DEFAULT 0x0

/* Register : DPHY_TX0_reg51_clr */
#define DPHY_TX0_REG51_CLR_ADDR 0x28C
#define DPHY_TX0_REG51_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG51_CLR */
#define DPHY_TX0_REG51_CLR_DPHYTX0_GPIO_DN_IE_LANE0_CLR_MSK BIT(0)
#define DPHY_TX0_REG51_CLR_DPHYTX0_GPIO_DN_IE_LANE0_CLR_LSB 0
#define DPHY_TX0_REG51_CLR_DPHYTX0_GPIO_DN_IE_LANE0_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg54_set */
#define DPHY_TX0_REG54_SET_ADDR 0x290
#define DPHY_TX0_REG54_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG54_SET */
#define DPHY_TX0_REG54_SET_DPHYTX0_RG_SCAN_PLL_EN1_SET_MSK 0
#define DPHY_TX0_REG54_SET_DPHYTX0_RG_SCAN_PLL_EN1_SET_LSB 0
#define DPHY_TX0_REG54_SET_DPHYTX0_RG_SCAN_PLL_EN1_SET_DEFAULT 0x0

/* Register : DPHY_TX0_reg54_clr */
#define DPHY_TX0_REG54_CLR_ADDR 0x294
#define DPHY_TX0_REG54_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG54_CLR */
#define DPHY_TX0_REG54_CLR_DPHYTX0_RG_SCAN_PLL_EN1_CLR_MSK 0
#define DPHY_TX0_REG54_CLR_DPHYTX0_RG_SCAN_PLL_EN1_CLR_LSB 0
#define DPHY_TX0_REG54_CLR_DPHYTX0_RG_SCAN_PLL_EN1_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg55_set */
#define DPHY_TX0_REG55_SET_ADDR 0x298
#define DPHY_TX0_REG55_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG55_SET */
#define DPHY_TX0_REG55_SET_DPHYTX0_RG_SCAN_PLL_EN2_SET_MSK 0
#define DPHY_TX0_REG55_SET_DPHYTX0_RG_SCAN_PLL_EN2_SET_LSB 0
#define DPHY_TX0_REG55_SET_DPHYTX0_RG_SCAN_PLL_EN2_SET_DEFAULT 0x0

/* Register : DPHY_TX0_reg55_clr */
#define DPHY_TX0_REG55_CLR_ADDR 0x29C
#define DPHY_TX0_REG55_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG55_CLR */
#define DPHY_TX0_REG55_CLR_DPHYTX0_RG_SCAN_PLL_EN2_CLR_MSK 0
#define DPHY_TX0_REG55_CLR_DPHYTX0_RG_SCAN_PLL_EN2_CLR_LSB 0
#define DPHY_TX0_REG55_CLR_DPHYTX0_RG_SCAN_PLL_EN2_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg56_set */
#define DPHY_TX0_REG56_SET_ADDR 0x2A0
#define DPHY_TX0_REG56_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG56_SET */
#define DPHY_TX0_REG56_SET_DPHYTX0_RG_SCAN_PLL_EN3_SET_MSK 0
#define DPHY_TX0_REG56_SET_DPHYTX0_RG_SCAN_PLL_EN3_SET_LSB 0
#define DPHY_TX0_REG56_SET_DPHYTX0_RG_SCAN_PLL_EN3_SET_DEFAULT 0x0

/* Register : DPHY_TX0_reg56_clr */
#define DPHY_TX0_REG56_CLR_ADDR 0x2A4
#define DPHY_TX0_REG56_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG56_CLR */
#define DPHY_TX0_REG56_CLR_DPHYTX0_RG_SCAN_PLL_EN3_CLR_MSK 0
#define DPHY_TX0_REG56_CLR_DPHYTX0_RG_SCAN_PLL_EN3_CLR_LSB 0
#define DPHY_TX0_REG56_CLR_DPHYTX0_RG_SCAN_PLL_EN3_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg57_set */
#define DPHY_TX0_REG57_SET_ADDR 0x2A8
#define DPHY_TX0_REG57_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG57_SET */
#define DPHY_TX0_REG57_SET_DPHYTX0_PLL_RST_N_SET_MSK 0
#define DPHY_TX0_REG57_SET_DPHYTX0_PLL_RST_N_SET_LSB 0
#define DPHY_TX0_REG57_SET_DPHYTX0_PLL_RST_N_SET_DEFAULT 0x0

/* Register : DPHY_TX0_reg57_clr */
#define DPHY_TX0_REG57_CLR_ADDR 0x2AC
#define DPHY_TX0_REG57_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG57_CLR */
#define DPHY_TX0_REG57_CLR_DPHYTX0_PLL_RST_N_CLR_MSK 0
#define DPHY_TX0_REG57_CLR_DPHYTX0_PLL_RST_N_CLR_LSB 0
#define DPHY_TX0_REG57_CLR_DPHYTX0_PLL_RST_N_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg58_set */
#define DPHY_TX0_REG58_SET_ADDR 0x2B0
#define DPHY_TX0_REG58_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG58_SET */
#define DPHY_TX0_REG58_SET_DPHYTX0_PLL_BYPASS_SET_MSK 0
#define DPHY_TX0_REG58_SET_DPHYTX0_PLL_BYPASS_SET_LSB 0
#define DPHY_TX0_REG58_SET_DPHYTX0_PLL_BYPASS_SET_DEFAULT 0x0

/* Register : DPHY_TX0_reg58_clr */
#define DPHY_TX0_REG58_CLR_ADDR 0x2B4
#define DPHY_TX0_REG58_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG58_CLR */
#define DPHY_TX0_REG58_CLR_DPHYTX0_PLL_BYPASS_CLR_MSK 0
#define DPHY_TX0_REG58_CLR_DPHYTX0_PLL_BYPASS_CLR_LSB 0
#define DPHY_TX0_REG58_CLR_DPHYTX0_PLL_BYPASS_CLR_DEFAULT 0x0

/* Register : DPHY_TX0_reg59_set */
#define DPHY_TX0_REG59_SET_ADDR 0x2B8
#define DPHY_TX0_REG59_SET_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG59_SET */
#define DPHY_TX0_REG59_SET_RG_LVDS_BIAS_EN_SET_MSK 0
#define DPHY_TX0_REG59_SET_RG_LVDS_BIAS_EN_SET_LSB 0
#define DPHY_TX0_REG59_SET_RG_LVDS_BIAS_EN_SET_DEFAULT 0x0

/* Register : DPHY_TX0_reg59_clr */
#define DPHY_TX0_REG59_CLR_ADDR 0x2BC
#define DPHY_TX0_REG59_CLR_DEFAULT 0x0

/* Field in register : DPHY_TX0_REG59_CLR */
#define DPHY_TX0_REG59_CLR_RG_LVDS_BIAS_EN_CLR_MSK 0
#define DPHY_TX0_REG59_CLR_RG_LVDS_BIAS_EN_CLR_LSB 0
#define DPHY_TX0_REG59_CLR_RG_LVDS_BIAS_EN_CLR_DEFAULT 0x0


/* Register : DPHYTX0_reg60_set */
#define DPHY_TX0_REG60_SET_ADDR 0x2C0
#define DPHY_TX0_REG60_SET_DEFAULT 0x0

/* Field in register : DPHYTX0_REG60_SET */
#define DPHY_TX0_REG60_SET_RG_LVDS_CLOCK_EN_SET_MSK 0
#define DPHY_TX0_REG60_SET_RG_LVDS_CLOCK_EN_SET_LSB 0
#define DPHY_TX0_REG60_SET_RG_LVDS_CLOCK_EN_SET_DEFAULT 0x0

/* Register : DPHYTX0_reg60_clr */
#define DPHY_TX0_REG60_CLR_ADDR 0x2C4
#define DPHY_TX0_REG60_CLR_DEFAULT 0x0

/* Field in register : DPHYTX0_REG60_CLR */
#define DPHY_TX0_REG60_CLR_RG_LVDS_CLOCK_EN_CLR_MSK 0
#define DPHY_TX0_REG60_CLR_RG_LVDS_CLOCK_EN_CLR_LSB 0
#define DPHY_TX0_REG60_CLR_RG_LVDS_CLOCK_EN_CLR_DEFAULT 0x0

/* Register : DPHYTX0_reg61_set */
#define DPHY_TX0_REG61_SET_ADDR 0x2C8
#define DPHY_TX0_REG61_SET_DEFAULT 0x0

/* Field in register : DPHYTX0_REG61_SET */
#define DPHY_TX0_REG61_SET_RG_PLL_FBK_FRA_CHG_SET_MSK 0
#define DPHY_TX0_REG61_SET_RG_PLL_FBK_FRA_CHG_SET_LSB 0
#define DPHY_TX0_REG61_SET_RG_PLL_FBK_FRA_CHG_SET_DEFAULT 0x0

/* Register : DPHYTX0_reg61_clr */
#define DPHY_TX0_REG61_CLR_ADDR 0x2CC
#define DPHY_TX0_REG61_CLR_DEFAULT 0x0

/* Field in register : DPHYTX0_REG61_CLR */
#define DPHY_TX0_REG61_CLR_RG_PLL_FBK_FRA_CHG_CLR_MSK 0
#define DPHY_TX0_REG61_CLR_RG_PLL_FBK_FRA_CHG_CLR_LSB 0
#define DPHY_TX0_REG61_CLR_RG_PLL_FBK_FRA_CHG_CLR_DEFAULT 0x0

/* Register : DPHYTX0_reg62_set */
#define DPHY_TX0_REG62_SET_ADDR 0x2D0
#define DPHY_TX0_REG62_SET_DEFAULT 0x0

/* Field in register : DPHYTX1_REG62_SET */
#define DPHY_TX0_REG62_SET_HSTX_DATA_VALID_SET_MSK 0
#define DPHY_TX0_REG62_SET_HSTX_DATA_VALID_SET_SET_LSB 0
#define DPHY_TX0_REG62_SET_HSTX_DATA_VALID_SET_SET_DEFAULT 0x0

/* Register : DPHYTX0_reg62_clr */
#define DPHY_TX0_REG62_CLR_ADDR 0x2D4

/* Register : ppi_reg_0_set */
#define DPHY_PPI_REG_0_SET_ADDR 0x2D8
#define DPHY_PPI_REG_0_SET_DEFAULT 0x0

/* Field in register : PPI_REG_0_SET */
#define DPHY_PPI_REG_0_SET_DPHYTX0_PPI_TURNDISABLE_LAN0_SET_MSK 0
#define DPHY_PPI_REG_0_SET_DPHYTX0_PPI_TURNDISABLE_LAN0_SET_LSB 0
#define DPHY_PPI_REG_0_SET_DPHYTX0_PPI_TURNDISABLE_LAN0_SET_DEFAULT 0x0

/* Register : ppi_reg_0_clr */
#define DPHY_PPI_REG_0_CLR_ADDR 0x2DC
#define DPHY_PPI_REG_0_CLR_DEFAULT 0x0

/* Field in register : PPI_REG_0_CLR */
#define DPHY_PPI_REG_0_CLR_DPHYTX0_PPI_TURNDISABLE_LAN0_CLR_MSK 0
#define DPHY_PPI_REG_0_CLR_DPHYTX0_PPI_TURNDISABLE_LAN0_CLR_LSB 0
#define DPHY_PPI_REG_0_CLR_DPHYTX0_PPI_TURNDISABLE_LAN0_CLR_DEFAULT 0x0

/* Register : ppi_reg_1_set */
#define DPHY_PPI_REG_1_SET_ADDR 0x2E0
#define DPHY_PPI_REG_1_SET_DEFAULT 0x0

/* Field in register : PPI_REG_1_SET */
#define DPHY_PPI_REG_1_SET_DPHYTX0_PPI_FORCERXMODE_LAN0_SET_MSK 0
#define DPHY_PPI_REG_1_SET_DPHYTX0_PPI_FORCERXMODE_LAN0_SET_LSB 0
#define DPHY_PPI_REG_1_SET_DPHYTX0_PPI_FORCERXMODE_LAN0_SET_DEFAULT 0x0

/* Register : ppi_reg_1_clr */
#define DPHY_PPI_REG_1_CLR_ADDR 0x2E4
#define DPHY_PPI_REG_1_CLR_DEFAULT 0x0

/* Field in register : PPI_REG_1_CLR */
#define DPHY_PPI_REG_1_CLR_DPHYTX0_PPI_FORCERXMODE_LAN0_CLR_MSK 0
#define DPHY_PPI_REG_1_CLR_DPHYTX0_PPI_FORCERXMODE_LAN0_CLR_LSB 0
#define DPHY_PPI_REG_1_CLR_DPHYTX0_PPI_FORCERXMODE_LAN0_CLR_DEFAULT 0x0

/* Register : ppi_reg_2_set */
#define DPHY_PPI_REG_2_SET_ADDR 0x2E8
#define DPHY_PPI_REG_2_SET_DEFAULT 0x0

/* Field in register : PPI_REG_2_SET */
#define DPHY_PPI_REG_2_SET_DPHYTX0_PPI_ENABLE_CLK0_SET_MSK 0
#define DPHY_PPI_REG_2_SET_DPHYTX0_PPI_ENABLE_CLK0_SET_LSB 0
#define DPHY_PPI_REG_2_SET_DPHYTX0_PPI_ENABLE_CLK0_SET_DEFAULT 0x0

/* Register : ppi_reg_2_clr */
#define DPHY_PPI_REG_2_CLR_ADDR 0x2EC
#define DPHY_PPI_REG_2_CLR_DEFAULT 0x0

/* Field in register : PPI_REG_2_CLR */
#define DPHY_PPI_REG_2_CLR_DPHYTX0_PPI_ENABLE_CLK0_CLR_MSK 0
#define DPHY_PPI_REG_2_CLR_DPHYTX0_PPI_ENABLE_CLK0_CLR_LSB 0
#define DPHY_PPI_REG_2_CLR_DPHYTX0_PPI_ENABLE_CLK0_CLR_DEFAULT 0x0

/* Register : ppi_reg_3_set */
#define DPHY_PPI_REG_3_SET_ADDR 0x2F0
#define DPHY_PPI_REG_3_SET_DEFAULT 0x0

/* Field in register : PPI_REG_3_SET */
#define DPHY_PPI_REG_3_SET_DPHYTX0_PPI_ENABLE_LAN_SET_MSK 3
#define DPHY_PPI_REG_3_SET_DPHYTX0_PPI_ENABLE_LAN_SET_LSB 0
#define DPHY_PPI_REG_3_SET_DPHYTX0_PPI_ENABLE_LAN_SET_DEFAULT 0x0

/* Register : ppi_reg_3_clr */
#define DPHY_PPI_REG_3_CLR_ADDR 0x2F4
#define DPHY_PPI_REG_3_CLR_DEFAULT 0x0

/* Field in register : PPI_REG_3_CLR */
#define DPHY_PPI_REG_3_CLR_DPHYTX0_PPI_ENABLE_LAN_CLR_MSK 3
#define DPHY_PPI_REG_3_CLR_DPHYTX0_PPI_ENABLE_LAN_CLR_LSB 0
#define DPHY_PPI_REG_3_CLR_DPHYTX0_PPI_ENABLE_LAN_CLR_DEFAULT 0x0

/* Register : MIPITX0_EN_set */
#define DPHY_MIPITX0_EN_SET_ADDR 0x2F8
#define DPHY_MIPITX0_EN_SET_DEFAULT 0x0

/* Field in register : MIPITX0_EN_set */
#define DPHY_MIPITX0_EN_SET_MSK 0
#define DPHY_MIPITX0_EN_SET_LSB 0
#define DPHY_MIPITX0_EN_SET_DEFAULT 0x0

/* Register : MIPITX0_EN_clr */
#define DPHY_MIPITX0_EN_CLR_ADDR 0x2FC
#define DPHY_MIPITX0_EN_CLR_DEFAULT 0x0

/* Field in register : MIPITX0_EN_clr */
#define DPHY_MIPITX0_EN_CLR_MSK 0
#define DPHY_MIPITX0_EN_CLR_LSB 0
#define DPHY_MIPITX0_EN_CLR_DEFAULT 0x0

/*chip top**/

/*mm sys global addr */
#define MM_GLB_BASE_ADDR 0x4430000
#define MM_CLK_DIV_0_ADDR 0x8
#define MM_CLK_MUX_0_ADDR 0x0

#define MM_SYS_BASE_ADDR 0x4400000

#define MM_GLB_BASE_ADDR_OFFSET 0
#define MM_DSI_TX1_ADDR_OFFSET 0x10000
#define MM_DSI_TX0_ADDR_OFFSET 0
/*DISPC_SYS_GLB end*/


/*COMM_SYS_GLB start. Base Address 0X2340000*/

/* Register : dphy_power_off */
#define DPHY_POWER_OFF_ADDR 0x1E8
#define DPHY_POWER_OFF_DEFAULT 0x0

/* Register : dphy_power_off_set */
#define DPHY_POWER_OFF_SET_ADDR 0x1EC

/* Register : dphy_power_off_clr */
#define DPHY_POWER_OFF_CLR_ADDR 0x1F0

/* Field in register : dphy_power_off */
#define DPHYTX0_PWR_OFF_BIT BIT(1)
#define DPHYRX0_PWR_OFF_BIT BIT(0)

/* Register : dphy_power_ready */
#define DPHY_POWER_READY_ADDR 0x1F4
#define DPHY_POWER_READY_DEFAULT 0x2

/* Register : dphy_power_ready_set */
#define DPHY_POWER_READY_SET_ADDR 0x1F8

/* Register : dphy_power_ready_clr */
#define DPHY_POWER_READY_CLR_ADDR 0x1FC

/* Field in register : dphy_power_ready */
#define DPHYTX0_AON_POWER_READY_N_BIT BIT(1)
#define DPHYRX0_AON_POWER_READY_N_BIT BIT(0)

/*COMM_SYS_GLB end */
#endif /* __AX_REG_DPHY_H */

