axera-drm-y := ax_drm_drv.o ax_drm_crtc.o ax_drm_gem.o ax_drm_plane.o ax_drm_fb.o ax_drm_vfb.o
axera-drm-y += ax_drm_virt_connector.o ax_drm_mipi.o ax_cdns_dsi.o ax_display_hal.o ax_drm_lvds.o ax_dsi_dphy.o ax_lvds_dphy.o

obj-$(CONFIG_DRM_AXERA) += axera-drm.o

