#ifndef __DTS_AX620E_RESERVE_MEM_DEFINE_H
#define __DTS_AX620E_RESERVE_MEM_DEFINE_H


#define ATF_RESERVED_START_HI
#define ATF_RESERVED_START_LO
#define ATF_RESERVED_SIZE_HI
#define ATF_RESERVED_SIZE_LO

#define SUPPORT_ATF

#ifdef OPTEE_BOOT
#define OPTEE_RESERVED_START_HI
#define OPTEE_RESERVED_START_LO
#define OPTEE_RESERVED_SIZE_HI
#define OPTEE_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_RISCV
#define RISCV_RESERVED_START_HI
#define RISCV_RESERVED_START_LO
#define RISCV_RESERVED_SIZE_HI
#define RISCV_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_RISCV_LOG_MEM
#define RISCV_LOG_MEM_RESERVED_START_HI
#define RISCV_LOG_MEM_RESERVED_START_LO
#define RISCV_LOG_MEM_RESERVED_SIZE_HI
#define RISCV_LOG_MEM_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_ISP_IMAGE
#define ISP_IMAGE_RESERVED_START_HI
#define ISP_IMAGE_RESERVED_START_LO
#define ISP_IMAGE_RESERVED_SIZE_HI
#define ISP_IMAGE_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_RAMDISK_HEADER
#define RAMDISK_HEADER_RESERVED_START_HI
#define RAMDISK_HEADER_RESERVED_START_LO
#define RAMDISK_HEADER_RESERVED_SIZE_HI
#define RAMDISK_HEADER_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_MODEL_DATA
#define MODEL_DATA_RESERVED_START_HI
#define MODEL_DATA_RESERVED_START_LO
#define MODEL_DATA_RESERVED_SIZE_HI
#define MODEL_DATA_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_RAMDISK
#define RAMDISK_START_ADDR
#define RAMDISK_SIZE
#endif

#ifdef SUPPORT_RECYCLE_CMM
#define CMM_RECYCLE_START_ADDR
#define CMM_RECYCLE_SIZE
#endif

#define BOOTARGS "bootargs"
#define CMM_ARGS "cmmargs"

#endif /* __DTS_AX620E_RESERVE_MEM_DEFINE_H */
