# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_CRYPTO_DEV_AXERA) += ax_cipher.o
ax_cipher-objs += ax_cipher_adapt.o ax_cipher_crypto.o ax_cipher_device.o ax_cipher_ioctl.o ax_cipher_proc.o eip130_drv.o
